### ISSUE TITLE
Keyword navigation using Ctrl +B and inline prompting of Selenium keywords not working with recent update of Selenium library

### ISSUE THREAD

**Issue by Sjain01** [robotframework/SeleniumLibrary#1010]
I recently updated my Selenium library and suddenly the keyword navigation using Ctrl +B has stopped working. With this, the inline prompting of Selenium keywords has also stopped.

For example when I type in Open keyword - it is not recognised and shows me an error stating definition not imported. something like this :-
![image](https://user-images.githubusercontent.com/28809161/33630751-baefd95a-da08-11e7-9ee8-0d2ac797afe2.png)

Following is the snapshot of all concerned versions available :-
![image](https://user-images.githubusercontent.com/28809161/33630678-850c6830-da08-11e7-843a-0721670b8344.png)

Could someone please guide how can I make the auto-prompt work again.

**Comment by aaltat** [comment]
The library internal architecture moved to use Robot Framework dynamic library API in 3.0.0 release. It seems that many IDE do not support dynamic library API. Please raise issue to your plugin provider. 

As a workaround, example Sublime Text 3 Robot Framework Assistant plugin and the Eclipse RED plugin do support dynamic library API.

Because this is not SeleniumLibrary issue, I am closing the issue.
