### ISSUE TITLE
"Input Text" keyword bug when I input a float num

### ISSUE THREAD

**Issue by baikaishuipp** [robotframework/SeleniumLibrary#1109]
I found a bug when I try input a float num into an input element, it will FAIL: TypeError: object of type 'float' has no len().

I changed "Input Text" and "Input Password" keywords' codes to change the text format from float to string before input it 

addon codes below:

Input Text
`text = str(text) if type(text) == float else text`

Input Password
`password = str(password) if type(password) == float else password`

and problem solved

**Comment by pekkaklarck** [comment]
The main question is that should these keywords in general work with non-string values. This has been discussed lately with another kw (don't remember which) that used to work with non-strings but due to changes in v3.0 didn't anymore. Changing any single kw is easy, but it would be inconsistent if all aren't changed. That's obviously a rather big task.

If we'd decide to change all kws, then the code should handle all non-string values. Handling only floats, not even ints, would be inconsistent.

If this was to be implemented, it would make sense to do it in generic manner and somehow automatically. In practise that would mean doing it on Robot's side before calling the keyword. It would be great to use type annotations to tell Robot which argument type are expected, but because that's Python 3 feature it's not possible with SL that needs ti support Python 2 as well. Probably could use `@keyword` decorator for that somehow. Anyway, this is an issue to Robot itself.

**Comment by aaltat** [comment]
Although this is a separate keyword, this is actually the same issue described in the #1021 and therefore I am closing this issue as duplicate. If you have further comments, please send them to the #1021

**Comment by pekkaklarck** [comment]
#1021 title should be updated. Or new generic issue submitted to replace it.
