### ISSUE TITLE
 WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by Mdvai** [robotframework/SeleniumLibrary#111]
Hi,

When i running my testcases using the selenuim2Library in IE & chrome webdriver,iam getting following error after exceution ,this error is NOT getting in Firfox driver  .

This is happening always before step fails :

FAIL : Login failed 
FAIL : WindowsError: [Error 5] Access is denied

IAM using IE 8 

Regards
Mdvi

**Comment by elizaleong** [comment]
This a problem that selenium fixed recently.  See:
http://code.google.com/p/selenium/issues/detail?id=4310
(selenium/webdriver/chrome/service.py and selenium/webdriver/ie/service.py need to catch WindowsError exception).

**Comment by j1z0** [comment]
If its fixed in selenium can u try upgrading your selenium version?  That should fix the problem. 

Cheers,
Jeremy

**Comment by rtomac** [comment]
I've run into the same thing as well. It is fixed in the Selenium source since 8/21/12, but hasn't made it into a release yet. I've verified that this change will in fact fix the issue in this context once it's released. That said I'm going to close the issue (and anxiously wait for a Selenium release).
