### ISSUE TITLE
selenium all keywords failing

### ISSUE THREAD

**Issue by ghost** [robotframework/SeleniumLibrary#1117]
Input text keyword is failing in robot. Element not found is the error thrown after browser is opened.
Same code tested in python 2.7 / SL 1.8.0 and working 100 %

screenshot
------------------
![2018-05-09 01_01_04-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/28727031/39778766-df96a1b8-5324-11e8-9235-b62ade958836.png)

script code
-------------------
*** Test Cases ***
tc_2
	Open Browser	http://172.19.1.157:9090/im	browser=chrome
	Input text    xpath:.//*[@id='username']    test
	Click element    xpath://*[@id='password-clear']
	Input text    xpath://input[@id='password-password']    test
	Click element    xpath:.//*[@id='loginForm_Login']

version info.
----------------
Webdriver 2.37 and 2.38 tested with chrome 66 on windows 7 64 bit. [all
combinations failed]
 
C:\Windows\system32>pip freeze robotframework
asn1crypto==0.24.0
bcrypt==3.1.4
cffi==1.11.5
cryptography==2.2.2
idna==2.6
paramiko==2.4.1
pyasn1==0.4.2
pycparser==2.18
PyNaCl==1.2.1
robotframework==3.0.4
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==3.1.1
robotframework-sshlibrary==3.0.0
selenium==3.11.0
six==1.11.0

**Comment by aaltat** [comment]
Without seeing the website, it's not possible to say for sure, but generally speaking your problem looks quite typical. With modern websites, it's normal that elements are load dynamically with JavaScript. Because of dynamic loading, browser and therefore Selenium doesn't know when page is loaded fully. This causes that test must wait page load, in simple form, test could wait that the element is present in the page, before doing the interaction with the element (please see the different Wait... keywords in the keyword documentation for more details). There are other possibilities, like waiting that JavaScript is not running or checking internal state of the webpage. But I would start with Wait... keywords.

This doesn't look like a problem with the SeleniumLibrary and it looks like more a support request and therefore I am closing this issue. For support, please read: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support If you think that this is a problem with the SeleniumLibrary, please provide more details why you think in that way.

**Comment by HelioGuilherme66** [comment]
Also the locators start with a '.' meaning start searching xpath from *here* instead from *root*.

**Comment by pekkaklarck** [comment]
Exact same code cannot work in S2L 1.8 simply because it doesn't support `xpath:<value>` syntax, only `xpath=<value>`. Also, if an element has an id, there's no need to use xpath because id alone is enough.

**Comment by ghost** [comment]
Hi Pekka, yes your point was taken care.

Hi @HelioGuilherme66 , yes this is same code that we are currently running on SL 1.8 on Python 2.7 machines.

@aaltat, I will try to run a generic application on both the environments and share a complete dump of both to further isolate the issue.

Thanks

**Comment by ghost** [comment]
Hi @pekkaklarck  @HelioGuilherme66 @aaltat,

greetings. I am gald that i was wrong.

Because we were working on RF 3.0 on py27 and SL 1.8.0 and this application is working seamlessly.
 Just wanted to upgrade this to the latest version.

I tested exact same code by adding this line before entering the username.

wait until element is visible	//input[@id='username']

and it worked. :)

Thanks
joydeep
