### ISSUE TITLE
1.1 should upgrade to selenium 2.25.0

### ISSUE THREAD

**Issue by adwu73** [robotframework/SeleniumLibrary#112]
I have upgraded to use 1.0.1 with selenium 2.25.0, normal functions work great, I have some trouble finding a nice way to close down the new IEDriverServer.exe with test failed though

**Comment by rtomac** [comment]
I'd like to wait on this, actually, until Selenium releases a fix for the issue you mention (also discussed in #111 and #109). If we release 1.1 prior to a Selenium release I'd suggest we DO NOT require 2.25.0. However, if they do release the fix prior to that, I totally agree with you.

**Comment by adwu73** [comment]
I found a serious issue in selenium 2.25.0 which will hang the test, see here: http://code.google.com/p/selenium/issues/detail?id=4590 I believe this bug exists in 2.23 as well. Since I upgrade to 2.25 to locate this bug with the new IEDriver server log feature.

So if possible, I would suggest we hold our 1.1 release until some serious bug in 2.25 been fixed.

**Comment by emanlove** [comment]
On 09/20/2012 10:02 AM, adwu73 wrote:

> I found a serious issue in selenium 2.25.0 which will hang the test, 
> see here: http://code.google.com/p/selenium/issues/detail?id=4590 I 
> believe this bug exists in 2.23 as well. Since I upgrade to 2.25 to 
> locate this bug with the new IEDriver server log feature.
> 
> So if possible, I would suggest we hold our 1.1 release until some 
> serious bug in 2.25 been fixed.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/rtomac/robotframework-selenium2library/issues/112#issuecomment-8728570. 

I'm widening the readership of this discussion to the 
robotframework-devel list as this is important to the developers there 
too.  I'm not sure what you mean by Selenium2Library 1.1 (our next 
release) should upgrade Selenium.  These are two separate products 
developed by two separate teams. Yes, Selenium2Library is the bridge 
between Robot Framework and Selenium but it way too restrictive to so 
tightly tie the versions together.  There is a very broad base of users 
with a broad set of needs and a varying number of current setups; many 
of which I know nothing about.  So to force users into upgrading by 
setting the install_requires on selenium to ">= 2.25.0" is simply not a 
good idea.

What, I think, would be helpful to our users and what we should do is 
list known issues with current or near current versions of Selenium with 
the current version of the Selenium2Library. I would suggest this go 
onto the github wiki (and not within the source code as that would force 
us to release a new version to "Publish" it). We should also publish 
more instructions on how to upgrade/downgrade versions of selenium along 
with the known issues list.

I wouldn't delay the release of Selenium2Library waiting for the 
selenium team to make their next release. We need to release when we are 
ready. I'm open to opposing viewpoints on theses matters but I am hard 
pressed to see how restricting the selenium version would be helpful.

Finally I'll mention here that I, just yesterday, tried out Travis-CI 
which is, for those who don't know, is a continuous integration 
service.  Someone had mentioned trying it out when I was talking about 
Shining Panda, another CI service, but I didn't.  This is a shame 
because it is **_really easy**_ to integrate with a github repository. 
This is important to this thread as it means having each pull request 
checked against our internal unit and acceptance tests for a variety of 
scenarios including various versions of selenium. I'll post more 
information elsewhere but wanted to mention it here.

Ed

**Comment by adwu73** [comment]
Before s2l 1.0.1, I believe we ship a Selenium together with s2l. In 1.0.1, you can change the version of selenium after s2l is installed. However, I am not sure what is our support policy here, i.e., support only one selenium release, or multiple release.

I think it's better that we ship s2l on our own pace, while inform user about issues that we know when working with different releases.

Having a CI setup is a great idea, looking forward to it.

**Comment by emanlove** [comment]
On 09/20/2012 06:53 PM, adwu73 wrote:

> Before s2l 1.0.1, I believe we ship a Selenium together with s2l. In 
> 1.0.1, you can change the version of selenium after s2l is installed. 
> However, I am not sure what is our support policy here, i.e., support 
> only one selenium release, or multiple release.

I want to apologize as I forgot to consider and write about the Windows 
Installer. We should without a doubt within the Windows Installer 
include a version of Selenium as well as the rest of the dependencies.  
We need to, or let me say we have to create a Windows Installer. Ryan 
made a great argument for having a Windows Installer so that the process 
for someone who just been introduced to Selenium2Library / Robot 
Framework / Python can easily install and get started. I completely 
agree with him and strongly believe in making the process as easy and 
straight forward as possible.  So yes within the Windows Installer lets 
bundle all the necessary packages; we can even create ones now with the 
"best" version of selenium and then again when another selenium version 
is released.

Ed

**Comment by j1z0** [comment]
Agreed. 

Cheers,
Jeremy

**Comment by rtomac** [comment]
I've actually made some good progress on this, so I'll try to finish it up here soon for the 1.1 release (like we had originally planned).

**Comment by adwu73** [comment]
if possible, I would really like issue 116 and 92 fixed in 1.1

**Comment by emanlove** [comment]
On 09/20/2012 11:06 PM, Ryan Tomac wrote:

> I've actually made some good progress on this, so I'll try to finish 
> it up here soon for the 1.1 release (like we had originally planned).

Ryan, Great News! Glad to hear it.  - Ed

**Comment by emanlove** [comment]
See issue #55.
