### ISSUE TITLE
Pass a proxy to a remote browser 

### ISSUE THREAD

**Issue by aluneau** [robotframework/SeleniumLibrary#1131]
Hi,
I can't find any information about using a proxy on a remote browser.
In java I did this:
```java
DesiredCapabilities capability = new DesiredCapabilities();
capability.setBrowserName(browserName);
capability.setCapability(CapabilityType.PROXY, new Proxy().setHttpProxy(myProxy).setSslProxy(myProxy))
``` 
That's working fine!

In robot framework I don't know. I tested this:
```robot
Open test browser
	Open browser  about:  firefox
	...  remote_url=${SELENIUM}
	...  desired_capabilities= browser:firefox,version:58.0.1,proxyType:manual,httpProxy:${SERVER_PROXY},sslProxy:${SERVER_PROXY}
```

And it did'nt work.

Does anybody know how I can do to solve my problem ?

**Comment by aaltat** [comment]
The same thing was actually asked few days ago in the Robot Framework user group: https://groups.google.com/forum/m/#!topic/robotframework-users/MdZyPIXKCvc

Because this looks like a support request, I am closing this issue. Please mail to the user group or use the other support request channels. 

If you feel that this is a bug, please explain why you think so and we will reconsider the issue.
