### ISSUE TITLE
Why specify locator follow the documentation, but element not found

### ISSUE THREAD

**Issue by xenogew** [robotframework/SeleniumLibrary#1154]
Here the element I want to select
`<ul role="presentation" class="uib-datepicker-popup dropdown-menu ng-scope" dropdown-nested="" ng-if="isOpen" ng-keydown="keydown($event)" ng-click="$event.stopPropagation()" style="top: 38px; left: 1px;">`

Use this keyword and point to the locator syntax.
`Wait Until Page Contains Element    //ul[@class=uib-datepicker-popup]  timeout=10s`

But it throw
`Element '//ul[@class=uib-datepicker-popup]' did not appear in 10 seconds.`

Even I changed to
*  `'xpath://ul[@class=uib-datepicker-popup]'`
*  `'xpath://ul[@class="uib-datepicker-popup"]'`
*  `'//ul[@class="uib-datepicker-popup"]'`

It still not found what specific at all.

What I missed in the term of usage? Please teach.

**Comment by aaltat** [comment]
Your xpath is incorrect. Example this stack overflow question explain the correct answer: https://stackoverflow.com/questions/1390568/how-can-i-match-on-an-attribute-that-contains-a-certain-string

And here is an another answer how to evaluate your xpath in Chrome: https://stackoverflow.com/questions/22571267/how-to-verify-an-xpath-expression-in-chrome-developers-tool-or-firefoxs-firebug

But because this is not an problem in the SeleniumLibrary and is a support request, I am closing the issue. Support can be found: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
