### ISSUE TITLE
Pop Up Problem with Selenium

### ISSUE THREAD

**Issue by houesmalek** [robotframework/SeleniumLibrary#1157]
Hello everyone, 

I'm making a test that clicks on a button and launches a window to do some other tasks.
My test works perfectly with Firefox and Chrome. However, when it comes to IE, the robot doesn't see the new window launched. 
So when I call these 2 lines in order to change to window,
```
@{Windows}=    Get Window Names
Select Window    @{Windows}[1]	
```

It fails with this error: **List variable '@{Windows}' has no item in index 1.**

Any recommandations please?

**Comment by aaltat** [comment]
With these details it's impossible to say anything concrete. The best educated guess is that launching new IE window takes more time and therefore list contains only one item. To test theory out, put long sleep before the `Get Window Names` keyword.

**Comment by houesmalek** [comment]
Yes I have a sleep 2s just before I'll try to put a longer sleep and get back to you with the results

**Comment by houesmalek** [comment]
@aaltat 
I've tried a `sleep 10 `before `Get Window Names` and a `sleep 2` between the 2 lines and the problem is the same: **List variable '@{Windows}' has no item in index 1**

**Comment by aaltat** [comment]
Is the window opened in 10s?

**Comment by houesmalek** [comment]
Yes sure!

**Comment by aaltat** [comment]
After some reading, it seems that multiple IE instances is not fully supported by Selenium: https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#multiple-instances-of-internetexplorerdriver Therefore this looks like a problem in the IEDriver or IE implementation. SeleniumLibrary is thin wrapper on top of the Selenium and therefore is not anything that we in the SeleniumLibrary side could do to fix it. The Selenium wiki contains few hints how to configure IE to get the multiple instances working and I would seek to that direction.

But because this doesn't look like a SeleniumLibrary issue, I am closing this issue. For more support, please ask from the Selenium side.
