### ISSUE TITLE
Question about site with client certificate

### ISSUE THREAD

**Issue by astrowalker2013** [robotframework/SeleniumLibrary#1159]
HI evry body
I want to test a website where include a client certificate. 
for exemple 
i can connect to website only i have the certificate client I have all certificat format who was generate bye the server. And after I can to navigate to this website with selenium

Wich keyword used, to connect with website with client certificate.
Is it possible to use de rules used with the last version of robotframework-request library

Thanks  in advence for your answer

Best

**Comment by aaltat** [comment]
SeleniumLibrary does not provide support for this, because it is not provided in the Selenium. I do not have good advice for you, because I have not deal with this type of problem before. 

 But this is more a of support question than problem or feature request in the SeleniumLibrary, I am closing the issue. For more support, please see: https://github.com/robotframework/SeleniumLibrary#support
