### ISSUE TITLE
testcase stucked in downloading file from IE after clicked the download button and won't go any further

### ISSUE THREAD

**Issue by lusheldon** [robotframework/SeleniumLibrary#1179]
Hi all,
My testcase is stucked in downloading file from IE after clicked the download button and won't go any further. 
Meanwhile if I click the download button by Exec JavaScript, the testcase would keep running and sending keys to handle the notification bar.
So what's the difference between Click Element and JavaScript click?
Thanks

**Comment by aaltat** [comment]
Selenium offers a blocking type of API, that will wait the page load (or was it on_load, I don't anymore recall) event from the browser when Selenium interacts with the elements. Like clicking element or selecting something from a list. But when executing JavaScript, Selenium doesn't know what that JavaScript does and therefore it doesn't wait for the page load event.

When the download dialogue is opened, (which Selenium doesn't see, because it lives in the operating system side) the page load event is fired by the browser when the dialogue is closed. Therefore Selenium is blocked when the dialogue is open.

**Comment by lusheldon** [comment]
@aaltat Thanks for the reply, you can close this issue now if there is no chance to make any fix!

**Comment by aaltat** [comment]
In the SeleniumLibrary there is not a way to fix it. Closing issue.
