### ISSUE TITLE
Need Mouse Move keyword

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#119]
Seen need for mouse move keyword.

**Comment by adwu73** [comment]
second this thought.

**Comment by just-be-dev** [comment]
Looking at the API it looks like we would have three keywords
- `Move Mouse by Offset`
- `Move Mouse to Element`
- `Move Mouse to Element with Offset`

**Comment by emanlove** [comment]
Seeing that I opened this ticket a while ago and there has not been a lot of rumbling or requests to implement I not sure of the need. Similar to the discussion raised within #344 and elsewhere about keyword overload I question whether we should create these three keywords just for the reason of creating them.

I think @aaltat's point under #344 that some of these additional keywords could actually be implemented using existing keywords but with additional optional arguments is a good one.  We just need to be careful and not create backward compatibility issues or future blockers.

**Comment by just-be-dev** [comment]
The only reason I suggested these is because they directly translate from the Selenium API. It'd pretty much be as simple as `driver.move_by_offset` `driver.move_to_element` `driver.move_to_element_with_offset`. 

See [here](http://selenium-python.readthedocs.org/en/latest/api.html#selenium.webdriver.common.action_chains.ActionChains.move_by_offset).

**Comment by aaltat** [comment]
Although these could be useful keywords, no-one has requested such keywords for a long time. Therefore closing this issue.

**Comment by el-nuru** [comment]
I also would like to have those keywords

**Comment by m3s5ts** [comment]
I need exactly what Click Element at Coordinates provides, but _without_ action.click(); i.e. Move Mouse to Element with Offset. Unfortunately at this time I'm not able to modify the source myself and will end up writing a python script, which is not a desired workaround considering the functionality is available via the Selenium API.

Not all page elements that can be interacted with have identifiers available; e.g. map objects that are rendered down into a single map layer. I can locate the object I need by obtaining coordinates via template matching, but I need the ability to place the mouse of the coordinate pair, _without_ clicking in order to display the element's menu.

**Comment by aaltat** [comment]
Please open a new issue,  this is already cluttered with different kinds of feature requests.
