### ISSUE TITLE
Drop Robot Framework 2.8 support in SeleniumLibrary 3.3.0.

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1197]
The Robot Framework 2.8.7 was released in January 2015. Consider dropping support 2.8 release and support RF 2.9 and 3.0 in the SeleniumLibrary 3.3 release.

**Comment by pceBuildMaster** [comment]
I have no issue dropping 2.x support.  I have been on RF 3.0.2 since when it just about came out.

**Comment by pekkaklarck** [comment]
I'm in general in favor of dropping support of ancient versions even if that the support wouldn't cause much extra work because all that extra work is anyway away from new feature development. If there are users who absolutely need to use those old versions, perhaps they can help with that support by, for example, taking care of setting up and maintaining CI.

The above said, I consider it a bit too late to drop support of RF 2.8.7 in SL 3.2, unless supporting it requires considerable effort. I'd prefer announcing RF 2.8.7 support to be dropped in SL 3.3 and then concentrating on getting SL 3.2 with all the already implemented fixes and features out ASAP. I'd also consider dropping support of RF 2.9.x in SL 3.4 and announcing that now as well.

**Comment by aaltat** [comment]
The #1219 removes RF 2.8.4 configuration from Travis. Go over the code in utils type.py to see can something be removed.

**Comment by aaltat** [comment]
The  #1221 and #1220 removes code that was created for RF 2.8 support. I think that is all and once those gets merged, this issue can be closed.
