### ISSUE TITLE
Ability to set default log level for `Page Should Contain` keywords

### ISSUE THREAD

**Issue by joaonc** [robotframework/SeleniumLibrary#1199]
All the [Page Should Contain](http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Page%20Should%20Contain) keywords (and `Frame Should Contain`, etc.) have a default loglevel of `INFO`.

This causes the logs at `INFO` level to be *huge*, especially if you use the `Wait Until` variants, which log the whole html each time it's checked.

That means that:
1. I live with 5+ MB logs per test case fail (imagine when several tests fail)
or
2. Have to explicitly set the `loglevel` argument each time these keywords are used.

Another option would be to extend SeleniumLibrary and change that default, but I would really like to get away from that.

The request is to add the ability to set the loglevel for this family of keywords.

**Comment by joaonc** [comment]
FYI, we keep logs in a small AWS EC2 instance, so space is not unlimited..  we also copy some to S3 and email them around sometimes as well.

We _really_ prefer the logs to be at `INFO` level, but having the whole DOM being spit out in these keywords makes that impractical, which means the rest of the important information at `INFO` level goes away.

Hope this makes a good case for adding this feature, tx!

**Comment by aaltat** [comment]
So your problem is that if `Page Should Contain` and it's variants fails, it logs the HTML source. This is a problem for you, because it makes the log size big. Am I correct?

If I am correct, there is a similar issue open for table keywords #991 Now days I tend to agree that logging source is not useful. Therefore it would be useful to remove the log source functionality also from these keywords.

Would you be willing to provide PR to change the functionality?

**Comment by joaonc** [comment]
I'll try and give it a shot.

What's your suggestion?
1. Set the default loglevel in all keywords to `NONE` or `DEBUG`
1. Remove logging altogether
1. Somehow add the ability to set the default loglevel once and have that apply to all keywords that dump source? (with a default of `NONE` if no new default is set).

**Comment by pekkaklarck** [comment]
I agree logging the source is not very useful these days. An easy solution would be removing such logging altogether or changing it to use trace level. I wouldn't use debug because that is often a good level to use when running tests and we shouldn't flood the log in that case. On trace level log files easily grow so much anyway that adding some more possibly useful content there isn't an issue.

Do these keyword log something else than the page source? If yes, then their `loglevel` argument could be left as-is and let it affect the other logging. If they only log the source, then a very simple solution would be just changing the default value to `TRACE`. Removing the argument would be backwards incompatible possibly breaking tests and thus require deprecation first. Changing the level doesn't affect tests except when there are failures, and those who want to see the source in that case can change the level or run tests with `--loglevel trace`.

**Comment by joaonc** [comment]
> Do these keyword log something else than the page source?

Yes, but it appears the other messages are hard coded levels. Here's the implementation of `Page Should Contain`:

```
    @keyword
    def page_should_contain(self, text, loglevel='INFO'):
        if not self._page_contains(text):
            self.ctx.log_source(loglevel)
            raise AssertionError("Page should have contained text '%s' "
                                 "but did not." % text)
        self.info("Current page contains text '%s'." % text)
```
`loglevel` is only used to log the source. The other messages are hard coded to `INFO`.

I agree that the simplest solution is to change the default `loglevel` to `TRACE`.

**Comment by aaltat** [comment]
There is a method that takes the loglevel as an argument: https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/base/librarycomponent.py#L36 Try to aim to a solution which removes the source logging all together.

Because the `loglevel` argument comes more or less useless, should we also deprecate the argument? What you think @pekkaklarck ?

**Comment by pekkaklarck** [comment]
Deprecation is so much work that I'd rather consider changing the default to TRACE.

**Comment by aaltat** [comment]
The deprecation is a long path to do. So let's change the default logging level to `trace`. To be constant, it should be changed from all `Page Should Contain` variants keywords. After that, in some future release, we can reconsider, should we drop the logging all together.

**Comment by aaltat** [comment]
Closing this issue because it is replaced by #1259
