### ISSUE TITLE
IE 9 unable to resolve the title of landing web page.

### ISSUE THREAD

**Issue by crazyshru** [robotframework/SeleniumLibrary#121]
************_versions**_*************
Robot framework - 2.7.3
Python - 2.7.3 on win32
OS - Windows 7
IE version - 9.08112.16421
Selenium2Library - 2.9.1

*************_Steps**_*******************************
the test is pretty basic. I am trying to open our application URl, and the landing page is the login page.

*************_Error**_***************************
Title should have been <<our application login page title>> but was 'WebDriver'
The above seen is the actual error but I replaced our actual title page text with <<our application login page title>>, for confidentiality reasons.

I think what is happening is when IE first opens a browser, it is bringing up a page titled "Web Driver". Is there a way to by pass that? is this a known issue?

**Comment by adwu73** [comment]
you may notice a webdriver start page first, and then it will jump to your actual page. This is work by design. However, you should not be able to get the title of the start page.

Can you verify the version number of your s2l and selenium? 2.9.1 is wrong. I suggest to upgrade to latest version of selenium for IE9 testing.

**Comment by zagasilva** [comment]
I have exactly this same issue. How can i test something on Internet Explorer with Robot Framework?
