### ISSUE TITLE
DeprecationWarning in base/robotlibcore.py:115

### ISSUE THREAD

**Issue by adongy** [robotframework/SeleniumLibrary#1212]
I get a lot of DeprecationWarnings when using this library (it's great!) when running it on Python 3.

```
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```

Looking at the documentation, it's a quick-fix as the replacement is nearly drop-in:

https://docs.python.org/3/library/inspect.html#inspect.getfullargspec
https://docs.python.org/2/library/inspect.html#inspect.getargspec

I can submit a PR for this.

**Comment by pekkaklarck** [comment]
Please submit the PR to [PythonLibCore](https://github.com/robotframework/PythonLibCore) project instead. This issue can be a reminder to upgrade `robotlibcore.py`.

The problem would actually be fixed relatively soon anyway,  because PythonLibCore needs to get support for named-only arguments and argument conversion that RF 3.1 is going to introduce. I want to get that 3.1 release into a better shape before looking at PythonLibCore, though.

**Comment by adongy** [comment]
Submitted the PR on the PythonLibCore project.

**Comment by aaltat** [comment]
Thanks for spotting the problem.

Closing this one, because problem is actually else.
