### ISSUE TITLE
Clicking element is not clickable

### ISSUE THREAD

**Issue by buihoanghai** [robotframework/SeleniumLibrary#1214]
Element is not clickable other element would receive the click. But the receive element is parent element. Is it a bug or feature?

![image](https://user-images.githubusercontent.com/6602376/46468210-67194800-c802-11e8-8206-93f6e26146fa.png)

![image](https://user-images.githubusercontent.com/6602376/46468477-181fe280-c803-11e8-92a4-4ef49411a5b9.png)

**Comment by aaltat** [comment]
That error is received from the Selenium side and not in SeleniumLibrary. But it's feature in the Selenium and usually it can be resolved by clicking something else in the DOM.

But because this is more of an support request than a bug report or an enhancement request, I am closing this issue. For support, please see: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
