### ISSUE TITLE
Create Firefox Extensions Installer

### ISSUE THREAD

**Issue by christian-rivera95** [robotframework/SeleniumLibrary#1217]
Im using `sys.modules['selenium.webdriver.firefox.webdriver'].WebDriver()` to create it though my test cases are in robotframework not standard selenium. Installing extensions in firefox, adding them to the firefox profile doesn't seem to work.

**Comment by aaltat** [comment]
I understand you have an issue with the Firefox extension, but I don't quite understand what you are asking. Are you asking an enhanced to a keyword which would allow installing extension? Or are you explaining a problem, that you are not able install Firefox extension with SeleniumLibrary?

In any way, could you explain better the thing you are having? Usually simplified examples and in case of a bug in the SeleniumLibrary full stack trace are useful.

**Comment by aaltat** [comment]
Is this still a problem or can we close the issue?

**Comment by christian-rivera95** [comment]
Hello Tatu,
Thanks for reaching out. My issue is that im using robot framework to test
am extension in chrome. Now that I want to test it on Firefox im stuck
because every approach seems not to be working. If I create a firefox
profile with the webdriver it doesn't intall the extension so that browser
is useless. If I use a different approach it does install the extension but
the browser remain uninteractable.

**Comment by aaltat** [comment]
I don't use Firefox in my testing and therefore I don't have any idea how extension is working. But by reading Selenium API: https://selenium-python.readthedocs.io/api.html#selenium.webdriver.firefox.webdriver.WebDriver.install_addon should do the trick for you. That functionality is not available by a keyword and most likely you need to write a own keyword to open the browser for you. 

But because this is looking like a support issue than a bug or feature request I am closing the issue.  For support,  please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
