### ISSUE TITLE
Browser is not opening with selenium library in linux 7.5 for robot frame work.

### ISSUE THREAD

**Issue by Rohit2387** [robotframework/SeleniumLibrary#1238]
OS : RHEL 7.5
BROWSER : Firefox
SELENIUM VERSION : 2.9.1
ROBOT VERSION : 2.8.1
BROWSER VERSION : It was tried with 60,52.7.0,54,45,32
Python 2.7.5

**Comment by aaltat** [comment]
Selenium 2 is not anymore supported in the latest 3.2 release. Although I would suggest that the problem is with incomparable Selenium, browser driver and browser versions. 

But because you are using not supported Selenium version, I am closing the issue. For more support please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

**Comment by Rohit2387** [comment]
Can you please suggest selenium ,robot,firework version for 7.5 linux?
