### ISSUE TITLE
How to debug the testcases in Robot framework 

### ISSUE THREAD

**Issue by Mdvai** [robotframework/SeleniumLibrary#125]
Hi,
       How can i debug testcases in the Robot framework .Please explain me 

Regards
Madhavi

**Comment by srib4ufrnd** [comment]
Hello Madhavi,

by the way for what purpose u r using the robot framework for web automation or for java appliaction automatiuon or ?

for debugging robot test scripts one best and easy way i know is by having log statements in u r robot test script code and python library code.

if in case u r launching any java application then u should launch the java application (JVM) with remote debugging params so that u can remotely attach to the JVM using eclipse (provided eclipse has the latest source code of the application. from here u can debug the app using eclipse)

if in case u r robot scripts executes some cases which triggers some servlet or bean action on j2EE applicatiopn server then also u have to start the j2EE server with remote debugging options. so that u can attach eclipse to the running server and perform remote debuggging.

i have to see whether we can remotely attach to a running python code or not, if so u can use eclipse to attach to the running python as well.

**Comment by Mdvai** [comment]
Hi Sreedhar,

```
Please can you tel me how can do java application (JVM) with remote
```

debugging params and start the j2EE server with remote debugging options.
so that u can attach eclipse to the running server and perform remote
debuggging.

Please give me step by step to achieve this

Regards

Madhavi
On Thu, Oct 11, 2012 at 2:47 PM, Sreedhar Reddy V
notifications@github.comwrote:

> Hello Madhavi,
> 
> by the way for what purpose u r using the robot framework for web
> automation or for java appliaction automatiuon or ?
> 
> for debugging robot test scripts one best and easy way i know is by having
> log statements in u r robot test script code and python library code.
> 
> if in case u r launching any java application then u should launch the
> java application (JVM) with remote debugging params so that u can remotely
> attach to the JVM using eclipse (provided eclipse has the latest source
> code of the application. from here u can debug the app using eclipse)
> 
> if in case u r robot scripts executes some cases which triggers some
> servlet or bean action on j2EE applicatiopn server then also u have to
> start the j2EE server with remote debugging options. so that u can attach
> eclipse to the running server and perform remote debuggging.
> 
> i have to see whether we can remotely attach to a running python code or
> not, if so u can use eclipse to attach to the running python as well.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rtomac/robotframework-selenium2library/issues/125#issuecomment-9333482.

## 

Thanks & Regards

Madhusudhan.s

**Comment by srib4ufrnd** [comment]
Hello Madhavi

To run u r java app with JVM in debug mode u should strat u r app with some thing like this

java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n YOURAPPNAME

once u do this u r app is ready for debugging remotely. only thiing is now u have to attach eclipse to u r app and use eclipse for debugging.

Any how please check the below links
http://java.dzone.com/articles/how-debug-remote-java-applicat
http://javarevisited.blogspot.in/2011/02/how-to-setup-remote-debugging-in.html
http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Fconcepts%2Fcremdbug.htm
http://stackoverflow.com/questions/975271/remote-debugging-java-application

It is a process which invloves some basic JVM concepts :-) Google is master to answer all ur questions :-)
Please ping me in case.

**Comment by ombre42** [comment]
Closing this as it does not seem to have anything to do with Selenium2Library.
Use the [Robot Framework user group](https://groups.google.com/forum/#!forum/robotframework-users) for general questions about Robot Framework.
