### ISSUE TITLE
Default Capabilities not set correctly if remote_url and desired_capabilities are given

### ISSUE THREAD

**Issue by JoniSaarinen** [robotframework/SeleniumLibrary#1284]
When using Open Browser keyword with remote_url and desired_capabilities then default capabilities are not set.
## Steps to reproduce the issue
Open browser using remote_url and desired_capabilities. For example test below.
```*** Settings ***
Library    SeleniumLibrary

*** Test Cases ***
Missing Capablities
    [Tags]   missing_caps
    SeleniumLibrary.Open Browser
    ...    url=https://www.google.fi
    ...    browser=chrome
    ...    remote_url=http://127.0.0.1:4444/wd/hub
    ...    desired_capabilities=build:10.1
```

## Error messages and additional information
When test is run with SeleniumLibrary 3.3.1 I can see the following lines in RF log file:
```
14:40:08.607	TRACE	Arguments: [ url='https://www.google.fi' | browser='chrome' | remote_url='http://127.0.0.1:4444/wd/hub' | desired_capabilities='build:10.1' ]	
14:40:08.607	INFO	Opening browser 'chrome' to base url 'https://www.google.fi' through remote server at 'http://127.0.0.1:4444/wd/hub'.	
14:40:09.609	DEBUG	POST http://127.0.0.1:4444/wd/hub/session {"capabilities": {"alwaysMatch": {}, "firstMatch": [{}]}, "desiredCapabilities": {"build": "10.1"}}
```
But when same test was run with SeleniumLibrary 3.2.0 the log output was as following
```
14:04:31.678	TRACE	Arguments: [ url='https://www.google.fi' | browser='chrome' | remote_url='http://127.0.0.1:4444/wd/hub' | desired_capabilities='build:10.1' ]	
14:04:31.678	INFO	Opening browser 'chrome' to base url 'https://www.google.fi' through remote server at 'http://127.0.0.1:4444/wd/hub'.	
14:04:32.679	DEBUG	POST http://127.0.0.1:4444/wd/hub/session {"capabilities": {"alwaysMatch": {"browserName": "chrome", "platformName": "any"}, "firstMatch": [{}]}, "desiredCapabilities": {"platform": "ANY", "browserName": "chrome", "version": "", "build": "10.1"}}
```

## Expected behavior and actual behavior

Expected: 
Default capabilities are set and and there is information for grid to know what browser to open.

Actual:
Now when the default capabilities are not set, grid fails to open browser since browserName is not set.

## Environment

Browser: Chrome 70.0.3538.67
Browser driver: Chromedriver
Operating System: Linux
Libraries
- Robot Framework: 3.1
- Selenium: 3.141.0
- SeleniumLibrary: 3.3.1 and 3.2.0
- Interpreter: Python 2.7.14

**Comment by aaltat** [comment]
Yes, this is by design and is backwards incomplete change introduced in 3.3.0 https://github.com/robotframework/SeleniumLibrary/blob/master/docs/SeleniumLibrary-3.3.0.rst#open-browser-keyword-in-3-2-and-most-likely-3-1-too-does-not-work-with-chromium-browser-but-3-0-works-with-chromium-browser-1243

In the current implementation, if desired_capabilities are defined, the `Open Browser` keyword doesn't join the Selenium default capabilities.

I understand that change is quite big and perhaps the chance was made too hastily.

**Comment by JoniSaarinen** [comment]
Oh, my bad. I missed that in changelog.

**Comment by aaltat** [comment]
Because now one must say `Chrome` for the `browser` argument and in the `desired_capabilities` it feels redundant. There are several ways to solve the problem. 

1) Make configurable is the Selenium default capabilities applied on top of the `desired_capabilities`
2) If `browserName` capability is not defined, we could applied. Because it can be derived from the `browser` argument.
3) Restore the old functionality, but that brings back the #1243

None of these are not hard to do. I think 3 is out of the question. And if I would need to choose, I would go with option 1.

**Comment by aaltat** [comment]
@JoniSaarinen is this a big problem for you? Should we consider doing something for the issue?

**Comment by JoniSaarinen** [comment]
Not really issue since I can work around it by setting also the browserName. But just as you mentioned, it feels a bit redundant setting it twice, even thou that is trivial thing to do when setting up new browser.

**Comment by aaltat** [comment]
That is very true. Perhaps I can modify the functionality so that it will set `browserName` if it's not set.

**Comment by aaltat** [comment]
@JoniSaarinen there is fix in the master code line, would you be able to install from the master and give it a try to see does it fix the problem.
