### ISSUE TITLE
Don't able to capture entire page in Screenshot with geckodriver

### ISSUE THREAD

**Issue by antho03** [robotframework/SeleniumLibrary#1311]
Hi, 

I use Robotframework with SeleniumLibrary and i would like the screenshot to be not the viewport, i want entire page screenshot.
I use Selenium2Library KW : "Capture Page Screenshot"

 My Code 
Open Browser	|   https://github.com/   |	ff |	ff_profile_dir=myProfile
Capture Page Screenshot | filename=test.png

RobotFramework : 3.1.1
Selenium : 3.141.0
SeleniumLibrary : 3.3.1
Geckodriver : 0.24

Thx for helping :)

**Comment by HelioGuilherme66** [comment]
@antho03 Are you able to do that with pure Selenium? I don't think it is possible, at least without coding workaround for it.

**Comment by antho03** [comment]
Hey, Thx for your answer

I have to use RobotFramework, but maybe can i change some code in KW "Capture page screenshot" file ? 
Or maybe use one desired capabilities for geckodriver ?

**Comment by aaltat** [comment]
SeleniumLibrary relies on Selenium taking the screen capture and with the modern browsers and browser drivers screen capture is taken only from the visible area. But there is a library which may help you https://github.com/collective/robotframework-selenium2screenshots

**Comment by antho03** [comment]
Hi aaltat, 
I had already seen and tested this library but it's dont work for me :/ it's usefull for crop , add pointer ,highline .. this kind of thing

**Comment by aaltat** [comment]
Then take screen capture of visible area and scroll page length of the visible area.

**Comment by antho03** [comment]
Maybe can u give me an example with scroll page length ? 
It will be with several screenshot for one page so ? Not only in one png file ?

**Comment by aaltat** [comment]
My old colleague did it, but I don't anymore have access to the code. If I would have such need, I would look to the JavaScript direction. 

I would like to remind that this issue tracker is reserved for a bug reports or feature request. Because this is turning more like a support request, than an enhancement or bug report, I am closing this issue. For more support, please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
