### ISSUE TITLE
TIMEOUT exception happens where use Close All Browsers

### ISSUE THREAD

**Issue by wck821829906** [robotframework/SeleniumLibrary#1378]
selenium version: 3.141.59
chrome driver version: 73.0.3683.68
robotframework version: 3.1.1
seleniumlibrary version: 3.2.0

Configurations:
config selenium2grid to release node machine in 300 seconds
Steps:
  1. open browser first time at a random node machine.
  2. open browser second time at a random node machine.
  3. Close All Browsers
Expect:
  Close All Browsers successfully
Current:
  Timeout exception happens
![image](https://user-images.githubusercontent.com/17002975/56875436-86641500-6a73-11e9-9d90-e50a8966d222.png)

**Comment by aaltat** [comment]
The Chrome has lately been buggy, could you test with other browsers, example with Firefox?

**Comment by wck821829906** [comment]
the same as firefox, It seems due to Capture Page Screenshot keyword ?

**Comment by aaltat** [comment]
I think something goes wrong with the closing the browser and run on failure is done. By default `Capture Page Screenshot` keyword is run and I assume that it also fails, because browser is dead, but the error in the screenshot masks the original error. Could you set the disable SeleniumLibrary the run in failure functionality, more details in here http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Run-on-failure%20functionality and rerun the test. Please post the full stack trace and remember to hide any sensitive information.

**Comment by aaltat** [comment]
I fixed the bug in the SeleniumLibrary, which did leave the browser in a incorrect state in the SeleniumLibrary cache. See #1379 for more details.

This doesn't fix the problem, that something went wrong when the browser is closed, but now the run on failure functionality should work better and it should not anymore mask the original error. Would you be able to install the SeleniumLibrary from the source directly and give it a try?

**Comment by aaltat** [comment]
Closing due inactivity.
