### ISSUE TITLE
Keyword performance may suffer if remotedriver delays response

### ISSUE THREAD

**Issue by stdedos** [robotframework/SeleniumLibrary#1405]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues

_I am not sure if this is "strictly" library's fault, but I guess this issue could be abstracted out_

## Steps to reproduce the issue

_Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory._

In _some kind_ of infinite redirections (in my case it was bouncing between at least 2 URLs) **which are not caught by browser's "too many redirects" safety**, it is possible that Keyword execution performance drops to 0.

This was discovered independently in two distinct Keywords: a "benign" `SeleniumLibrary.Get Location` and a more serious `SeleniumLibrary.Wait Until Page Contains` issue.

I have traces of `SeleniumLibrary.Get Location`, but they are equivalent for `SeleniumLibrary.Wait Until Page Contains`

## Error messages and additional information
_If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines._

_Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too._

Execution of `SeleniumLibrary.Get Location`:
```robot
SeleniumLibrary . Get Location
19:51:07.261	DEBUG	GET http://192.168.0.2:4444/wd/hub/session/0d487d85e51eaa406195e102b054d3a7/url {"sessionId": "0d487d85e51eaa406195e102b054d3a7"}	
19:51:07.262	DEBUG	Starting new HTTP connection (1): 192.168.0.2	
19:54:03.576	DEBUG	http://192.168.0.2:4444 "GET /wd/hub/session/0d487d85e51eaa406195e102b054d3a7/url HTTP/1.1" 200 173	
19:54:03.576	DEBUG	Finished Request
```

## Expected behavior and actual behavior

I expect that there would be "some way" to protect against such huge delay.

Especially in the case of `SeleniumLibrary.Wait Until Page Contains`, if I have "some" kind of timeout, I would expect that it would be honored "on all levels".

_Actual behavior is that such "case of redirects" can halt test execution for too much_

## Environment

Browser: `Chromium 72.0.3626.121`
Browser driver: `ChromeDriver 72.0.3626.121`
Operating System: `Alpine 3.9.0`
Libraries
- Robot Framework: `Robot Framework 3.1.1`
- Selenium: `selenium==3.141.0`/`selenium-server-standalone-3.141.59`
- SeleniumLibrary: `robotframework-seleniumlibrary==3.3.1`
- Interpreter: `Python 3.6.8 on linux`

**Comment by aaltat** [comment]
Your observation is correct. The SeleniumLibrary is single threaded application and SeleniumLibrary timeouts are verified only when call to Selenium methods returns. Therefore, as you observed, if calls to Selenium API last longer than the SeleniumLibrary timeout, those calls are not terminated. 

Technical it would be possible to run Selenium calls in a thread and if they last longer than SeleniumLibrary timeout something could be done. But that something is actually quite problematic, because Selenium API is a blocking type of API. This means that the client, the SeleniumLibrary, must wait the method call to return, before new one can be made. New calls are not allowed and last time I tried they don't work either. So this means that browser can not be closed and the drive executable does not close. In practice it would mean that browser and driver executable would be left running until OS is rebooted or by some manual intervention.

I understand that this is problem for you. As a solution, you could try set the Robot Framework level timeouts: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#timeouts or you try to set maximum execution timeout in your CI system. Some CI system are sophisticated enough also to have more fine grained timeouts.

Also I am open to suggestions, how the problem could be solved SeleniumLibrary level. Even better if you pact up the idea with a PR.

**Comment by stdedos** [comment]
Well, if your claim is correct (which I don't object):

> [...] Selenium API is a blocking type of API.

then, this means that there is even probably no reason to solve it within the scope of the library. In CI scope, where environments go up and down it's not a problem, since on CI there is "a way to recover" (i.e. clean up completely), and the end state will be the same (CI will provide a result i.e. `Fail` or `Fail/Timeout`, and CI will be ready to serve again).

In "manual" tests, if the browser is then further undrivable, then that probably means you need to re-provision the environment (or at least kill the whole browser/selenium chain). Which leads back to CI-handling.

I guess I'll take the bug report one step down the stack and see what could be done, if at all possible.

**Comment by aaltat** [comment]
For further information https://github.com/SeleniumHQ/selenium/wiki/Frequently-Asked-Questions#q-is-webdriver-thread-safe

**Comment by aaltat** [comment]
And thank you for clear and easy to understand bug report.
