### ISSUE TITLE
Redirect false in browser

### ISSUE THREAD

**Issue by sakhtar-git** [robotframework/SeleniumLibrary#1414]
https://github.com/robotframework/SeleniumLibrary/blob/de3d1aa650d9650bcd5c67f95ba9ecbcd7022970/atest/acceptance/open_and_close.robot#L77

I am looking for stopping the redirect from siteA to siteB in the browser . Please let  me know.
something like below:
https://github.com/kennethreitz/requests/blob/9a2e5df000691ad28613524ca7f80aa28a94a8d5/requests/api.py

**Comment by aaltat** [comment]
Your description sounds like a solution to a problem and now you are asking how to implement the solution. But could you describe the problem and perhaps then we can tell more is this a missing feature or a bug in the SeleniumLibrary.

**Comment by sakhtar-git** [comment]
Problem: There should be some mechanism to stop redirect of siteA(product) to siteB(loginForm page) when it is opened on a browser chrome using SeleniumLib - open browser 
I think it is a missing feature/ nice to have in seleniumLib
               Open browser  <url> <browser> <redirect=bool>

**Comment by aaltat** [comment]
But why you want the redirection to stop?

**Comment by sakhtar-git** [comment]
want to use access token repeatedly in the multiple test by bypassing login screens

**Comment by aaltat** [comment]
So your problem is that your login is taking long time and you want to minimize the login time to speedup the testing. I don't understand how that relates to redirection. 

But in any case, you could start by asking from your development team, is there a way to bypass the login someway. Perhaps you can inject cookies or something which could make the site think that user has already logged in.

Because this is starting to feel like a support request and not like an feature or bug report, I am closing this issue. For support please read https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

But if you feel that disabling redirection could be useful feature and you have an idea how it can be implemented, please send an update.
