### ISSUE TITLE
Close Browser and Close all Browsers should timeout or handle alerts

### ISSUE THREAD

**Issue by anton264** [robotframework/SeleniumLibrary#1415]
If an alert is open the Close Browser keywords will hang indefinitely. This is not really a fault of seleniumlibrary but in selenium itself.
More details here:
https://stackoverflow.com/questions/48703734/why-does-the-python-selenium-webdriver-quit-not-quit

This can be mitigated by doing:
```
***Keywords***
Suite Teardown
    Go To   about:blank
    Run Keyword And Ignore Error  Handle Alert
    Close All Browsers
```

However, it would be good if seleniumlibrary would check for open alerts and close them before closing the browser to avoid this behaviour.

**Comment by aaltat** [comment]
This is true, we don't check are alerts displayed and blindly call Selenium `driver.quit()`. And because the Selenium `quit` does not return, the keyword will hang forever. I don't like that the `Close Browser` or Close All Browsers` would automatically close alerts, because it can lead to bug's going unnoticed. But the current functionality is not good either. 

Perhaps it would be good to have timeout after the keyword would fail. It can not be same as waiting elements, because that is usually in seconds and sometimes closing browser can take minute or two. Therefore we would need to introduce new timeout in the SeleniumLibrary import and in the keywords.

Should not be hard to implement, would you be interested to provide a PR to fix the problem?

**Comment by anton264** [comment]
Did further testing and not able to reproduce the issue with 
Selenium: Version: 3.141.0
Chromedriver Version: 76.0.3809.87-0ubuntu0.18.04.1
Firefox geckodriver Version: 68.0.1+linuxmint1+tina

```
***Settings***
Library     SeleniumLibrary

***Test Cases***
Test
    Open Browser  tst.html  browser=firefox  alias=None  remote_url=False  desired_capabilities=None  ff_profile_dir=None
    Input Text  name=name  text
    sleep   2
    Close Browser
```

```
<html>
<body>
    Please enter a value for me: <input name="name" >
<script>
    window.onbeforeunload = function(e) {
        return 'Dialog text here.';
    };

</script>
<h2>ask questions on exit</h2>
</body>
</html>
```

I will do some more testing and report back, has selenium fixed this issue? If so does selenium always close alerts?

**Comment by aaltat** [comment]
Closing due inactivity.

**Comment by wesleybl** [comment]
I simply set `window.onbeforeunload = undefined` to avoid the popup:

```robot
Close All Browsers Without Beforeunload
    [Documentation]  Set 'window.onbeforeunload = undefined' to avoid popup when closing the browsers.
    Execute Javascript  window.onbeforeunload = undefined;
    Close All Browsers
```
I'm using Firefox 78.9 and Selenium 3.141.0

@anton264 did you come to any conclusions? Do you know if this has been fixed somewhere?
