### ISSUE TITLE
Add set window size keyword

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#146]
There is a Selenium WebDriver command for setting the window size and it has been requested to have a corresponding Selenium2Library keyword.

**Comment by emanlove** [comment]
Implemented feature using dictionary as parameter/return value for set_window_size/get_window_size (See [change here](https://github.com/emanlove/robotframework-selenium2library/commit/9fa300f35a42aa6a8c4f2275c7e180789b744579)). I am wandering if this should be implemented instead as two parameters or a list of two values so it will not require the Collections library. I am sure having it as a dictionary, thus requiring the Collections library, will trip someone up.

**Comment by ombre42** [comment]
The method you are wrapping takes width and height as separate, required arguments. I think the keyword should be the same except hide the windowHandle argument.

**Comment by emanlove** [comment]
@ombre42 Agreed. Thanks for the feedback.

**Comment by emanlove** [comment]
@ombre42 I've added some [keyword](https://github.com/emanlove/robotframework-selenium2library/blob/get-set-window-size/src/Selenium2Library/keywords/_browsermanagement.py#L172) [documentation](https://github.com/emanlove/robotframework-selenium2library/blob/get-set-window-size/src/Selenium2Library/keywords/_browsermanagement.py#L184) with an example. Do you think this is clear? If not, do you have any suggestions for explaining the usage of these keywords.

**Comment by ombre42** [comment]
The documentation is clear. Here's my thoughts (you asked!).

For Set Window Size, the argument names are in single quotes instead of back quotes.
Here's two alternatives to consider:
Sets the `width` and `height` of the current window.
Sets the `width` and `height` of the current window to the specified values.

Example for Get Window Size could be just: | ${width} | ${height}= | Get Window Size |. The extra code adds clarity to Set Window Size, but not to Get Window Size.

Both examples use the values for SVGA (also the values in the Selenium doc), but the values for height and width are swapped.

I think it is odd Se returns a dict instead of a tuple. Are they going to add depth in the future? :P

**Comment by ombre42** [comment]
was in 1.4 release and left open
