### ISSUE TITLE
Support 'data-' attributes as locators for SeleniumLibrary

### ISSUE THREAD

**Issue by youtah** [robotframework/SeleniumLibrary#1474]
The data attribute is a well defined attribute in the HTML5 specification.

It would be nice to have a '_shortcut_' in SeleniumLibrary, so we could use it as a locator. 

**For an Example:**
If we had an element such as: `<div data-automation="helptext">ABC 123</div>`
Instead of using something like: `css:div[data-automation="helptext"]`
or instead of: `//*[@data-automation="helptext"]`

We could do something like this instead: `data:automation:helptext`

_Submitted as per discussion in the seleniumlibrary channel in the RobotFramework Slack workspace._

**Comment by aaltat** [comment]
So middle part, between the `:`-characters, of the locator matches the attribute key after the `-` character. And later part matches the attribute value. It can be done. 

Because Selenium API does not have native support for data attributes, most likely easiest is to convert the locator as a xpath internally.

**Comment by pekkaklarck** [comment]
Yesh, xpath conversion is a good idea. Very easy to implement. Could then later be replaced with a native Selenium method if such a method is added.

Should this get `good first issue` and possibly also `hacktoberfest` labels?
