### ISSUE TITLE
"Table Should Contain" does not work properly

### ISSUE THREAD

**Issue by Pawci3oo** [robotframework/SeleniumLibrary#1482]
Example code:
*** Settings ***
Library    SeleniumLibrary    #4.0.0

*** Variables ***
${url}    https://www.w3schools.com/html/html_tables.asp
${customer_table}    //table[@id='customers']

*** Test Cases ***
Sample test
    Open Browser    ${url}    browser=chrome
    Maximize browser window
    Element Should Be Visible    ${customer_table}
    Table Should Contain    ${customer_table}    Each

## Expected behavior and actual behavior

Expected: FAIL
Actual: PASS

If there is given text on the page and even I provide ID of table for this keyword, then this keyword returns True. (table does not contain text)
`Table Should Contain` is useless in that case because I can also use `Page Should Contain` to find text on the page. In my project, I have two tables on the page where one record is moved to the second table and I need to verify that.

## Environment

Browser: Chrome 77.0.3865.90
Browser driver: ChromeDriver 2.42.591088
Operating System: Windows 10 17763.740
Libraries 
- Robot Framework: 3.1.2
- Selenium: 3.141.0
- SeleniumLibrary: 4.0.0
- Interpreter: Python 3.7.4

**Comment by aaltat** [comment]
Please update the ChromeDriver, it is pretty old compared to the Chrome and try does it resolve the problem.

**Comment by Pawci3oo** [comment]
No changes.
Current version: ChromeDriver 77.0.3865.40

**Comment by aaltat** [comment]
I can reproduce the problem, need to investigate more closely where the problem is.

**Comment by aaltat** [comment]
Found the bug, it is in [table element finder](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/tableelement.py#L197) and Selenium documentation [explains](https://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webelement.WebElement.find_elements_by_xpath) why it happens. Good catch, it has been there since 3.0 release.

**Comment by Pawci3oo** [comment]
I found that bug because I did upgrade my framework (RF and python). I also changed Selenium2Library to SeleniumLibrary and a lot of my tests are failing since this upgrade.

When I can expect a fix? :)

**Comment by aaltat** [comment]
Already fixed locally. Bug also revealed that that there is many other bugs in the same class and I am fixing all of those.

**Comment by Pawci3oo** [comment]
I understand. Anyway thanks :)

**Comment by pekkaklarck** [comment]
Wow, the bug has been there for some time. These keywords apparently aren't used that much since nobody has noticed this earlier. Or then there are lot of tests out there that pass when they shouldn't... I would say the fix should go already to SL 4.0.1 if such a release is done.

**Comment by aaltat** [comment]
There is bunch of test, but not for this particular case :-) . The internal xpath matched all elements in page and not only elements in the table. If your page was large one, there definitely has been performance hit. But that should now be fixed in the PR. 

I am also considering to make release to just to get this one out. I think release should be 4.1 because master branch contains some improvements, like #1464

**Comment by aaltat** [comment]
The fix is merged to master. Could you @Pawci3oo install from the GitHub repo: `pip install git+https://github.com/robotframework/SeleniumLibrary.git` and try does it also fix your problem? If it does, I will do a pre-release (4.1), most likely in next weekend.

**Comment by aaltat** [comment]
Fixed in #1485

**Comment by Pawci3oo** [comment]
I have run a few tests and it is working, but I would like to run all the tests. I will give you answer tomorrow :)

**Comment by Pawci3oo** [comment]
All tests return correct results, so I confirm that it is fixed :)
Thanks
