### ISSUE TITLE
`Press Keys    id=end_time    5` does not work  date element

### ISSUE THREAD

**Issue by chenrui333** [robotframework/SeleniumLibrary#1507]
We are trying to deprecate `Press Key`, but find it does not quite work with `date` element.

**Comment by aaltat** [comment]
Well what:  `does not work` actually mean? Here are some hints what is good to me to know:

## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version

**Comment by chenrui333** [comment]
- Robot Framework: 3.1.2
- Selenium: 3.141.0
- SeleniumLibrary: 4.1.0
- Interpreter: python 3.8.0

We actually figured it out that `Press Key` replacement to `Press Keys` is not that direct.

After updating it to `Press Keys    None    BBBB`, it works for us.

That is the fix diff for reference:
```
     Wait Until Keyword Succeeds                 5 times     1s     Set Focus To Element                                id=rsvp_close_offset_timeOfDay
-    Wait Until Keyword Succeeds                 5 times     1s     Press Keys                            id=rsvp_close_offset_timeOfDay    9
+    Wait Until Keyword Succeeds                 5 times     1s     Press Keys                            None    9
```

**Comment by aaltat** [comment]
Press Keys has bug in in the released version: https://github.com/robotframework/SeleniumLibrary/issues/1489 which may also affect. But it's is fixed in the master code line.

**Comment by aaltat** [comment]
Ah and now I remember. `Press Key` is quite close to the `Input Text` keyword, both use the same Selenium API, but `Press Key` some special handling for the some characters. Therefore if one does not need the Selenium special keys, it might be better to use `Input Text` keyword. But if there is a need for the Selenium special keys, then it's better to use the `Press Keys` keyword.

The Selenium method used by `Press Keys` keyword actually clicks on the element, to gain focus. In some cases, like for buttons, it might not be the desired way and it might cause some other problems. It also looks like that this is not documented and it probably should be.

**Comment by chenrui333** [comment]
> Therefore if one does not need the Selenium special keys, it might be better to use Input Text keyword. But if there is a need for the Selenium special keys, then it's better to use the Press Keys keyword.

That is very good takeaway, we do have some usage for the special keys. But I did see some are using them for `input text`.

Very good to know.
