### ISSUE TITLE
Support of list of locator-strings to use different strategies and WebElement as entry point.

### ISSUE THREAD

**Issue by Snooz82** [robotframework/SeleniumLibrary#1512]
**Situation:**
Some stuff only xpath can do.
- parant selection or grand parents
- text() contains
Some stuff only css can do.
- input:checked for checkboxes and radio

**Problem:** 
in the Moment its not possible to combine css with xpath.
And it is also not possible to get an element, and then search with this element as entrypoint.
Like:
1. get checkbox that is checked by css,
2. get an Element that has a specific text that is a child of the grand parent of the checked one.

```html
<div>
  <div>
    <input  type="checkbox">
  </div>
  <span>acc:  bla bla bla</span>
</div>
```

**Requested Feature:**
Support Lists as possible Locator Strategie.

`${text}=    Get Text    ["css:input:checked", "xpath:../../span[starts-with(text(),'acc:')]"]`

It shall also be possible to use a WebElement as first element in the list.
```
${element}=    Get WebElement    css:input:checked
${text}=    Get Text    [${element}, "xpath:../../span[starts-with(text(),'acc:')]"]
```

This would allow also to get Elements relative to previosly found elements.
This is required when you want to work with shadow-DOM/WebComponents...

**Comment by badari412** [comment]
If no one has started working on this, I would like to. My plan is to implement it this way:

```
Click Cancel Button Using List Of Locators
    ${scalar}=    Create List    tag:form    name:cancel_button
    Click Button    ${scalar}
    Value Should Be Cancel
```

Any thoughts/suggestions?

**Comment by Snooz82** [comment]
We where working a lot on Browser library project the last months.

There it is not a list, but locators can be concatenated with `>>`.

I do like this much more, because you can just write these selectors in RobotFramework.
Lists always have to created in variables section or with keywords.
It is not trivial to replace something within a list and so on.
So a single string would be much better.

I would like to see a new locator strategy in SeleniumLibrary.

`smart: .class-of-css >> //some/xpath >> .css`

**Comment by aaltat** [comment]
I also like the `>>` as a separator. It needs some more work, but would be easier to use than list.

**Comment by divfor** [comment]
> **Situation:**
> Some stuff only xpath can do.
> 
> * parant selection or grand parents
> * text() contains
>   Some stuff only css can do.
> * input:checked for checkboxes and radio
> 
> **Problem:**
> in the Moment its not possible to combine css with xpath.
> And it is also not possible to get an element, and then search with this element as entrypoint.
> Like:
> 
> 1. get checkbox that is checked by css,
> 2. get an Element that has a specific text that is a child of the grand parent of the checked one.
> 
> ```
> <div>
>   <div>
>     <input  type="checkbox">
>   </div>
>   <span>acc:  bla bla bla</span>
> </div>
> ```
> 
> **Requested Feature:**
> Support Lists as possible Locator Strategie.
> 
> `${text}= Get Text ["css:input:checked", "xpath:../../span[starts-with(text(),'acc:')]"]`
> 
> It shall also be possible to use a WebElement as first element in the list.
> 
> ```
> ${element}=    Get WebElement    css:input:checked
> ${text}=    Get Text    [${element}, "xpath:../../span[starts-with(text(),'acc:')]"]
> ```
> 
> This would allow also to get Elements relative to previosly found elements.
> This is required when you want to work with shadow-DOM/WebComponents...

you may see https://github.com/robotframework/SeleniumLibrary/pull/680 for some idea

**Comment by badari412** [comment]
Thanks! I think I know what I should do, but just to be clear, the usage of the new strategy will be as follows:

```
Click Cancel Button By Smart Locator
    Page Should Contain Button   smart: tag:form >> name:cancel_button
    Click Button   smart: form_name >> cancel_button
    Value Should Be Cancel
```

Please correct me if I am wrong.

**Comment by pekkaklarck** [comment]
I like `>>` a lot as well. Lists could have some benefits as well but `>>` is easier to use and ought to work fine in most cases and using same syntax as Browser is definitely a plus too. Support for lists could be added separately if needed. Either way, the title of this issue should be updated.

How common is `>>` in locators otherwise? Is it valid e.g. in CSS? If it's rare, smart locators could be recognized simply by them containing `>>` or perhaps ` >> ` with spaces around. Having explicit `smart:` prefix is a good idea anyway similarly we support `xpath:` while also automatically recognizing `//`.

**Comment by aaltat** [comment]
Instead of using `smart:`, would it be better to use `multiple:`. It would better describe what it actually does. 
Example this `multiple:css:article >> css:.bar > .baz >> css:span[attr=value]` would be split to three css locators: `article`, `bar > .baz` and `span[attr=value]`. 

Also it would be good to support ` >> ` as is, when it is inside of quotes. Example this  would result as valid xpath selector `xpath://*[contains(text(),"some >> text")]` and it would not be valid split as two invalid locators.

**Comment by pekkaklarck** [comment]
I'm not sure is `smart:` the best prefix but `multiple:` doesn't sound that good either. What about `mixed:` or `mix:`? Does Browser uses some prefix?

`>>` possibly appearing in locators themselves is a problem. Trying to see is it inside quotes may be somewhat complicated, though. Some alternatives how to handle that:
- Just use ` >> ` (require spaces) and then make parsing more intelligent if there are concrete needs. If the `>>` support is added in a major release that ought to be OK.
- Require each "sub locator" to start with an explicit locator strategy.
- Make `default:` behave so that `>>` has no special meaning. Then there would be an easy workaround.

**Comment by aaltat** [comment]
I think from code point of view, starting each sub locator with locator strategy is good option. Something like this 
`mixed:css:article >> css:.bar > .baz` would work. but `mixed:css:article >> .bar > .baz` would be treated as single locator (because `.bar` does not contain locator strategy. )

Also it would be easy to explain the documentation and most likely users would understand it correctly.

**Comment by pekkaklarck** [comment]
If we require each sub locator to start with an explicit strategy, using `mixed:` or other prefix probably wouldn't be necessary.

**Comment by badari412** [comment]
IMHO, the name of the strategy should somewhat depict as to what it does, for e.g. the name "hierarchy:" denotes that the strategy can be used get the elements using their parents or grandparents.

Also, we can support both ` >> ` separated locators and also the list way of denoting the locators(${scalar}=    Create List    tag:form    name:cancel_button). Just in case ` >> ` fails, users can still use the second way.

**Comment by aaltat** [comment]
@pekkaklarck  Yes, most likely separate strategy is not needed and this would be good: `css:article >> css:.bar > .baz`. And it would be easier to document. Also I do not believe that it is likely that someone would have locator that would already have something like like ` >> css:` (spaces included) in the middle of their locator. 

@badari412 Yes, we can also support lists, that should not be too much of extra to implement in the same go.

**Comment by aaltat** [comment]
Remember to give credit for @badari412 for the implementation.

**Comment by aaltat** [comment]
There is really small, but it still possible, that this change is backwards incompatible.
