### ISSUE TITLE
Register Keyword To Run On Failure

### ISSUE THREAD

**Issue by DusanAtanackovic** [robotframework/SeleniumLibrary#1558]
I am not sure if it's an issue or wrong usage of the keyword, but i can't find a solution after searching the internet over last few days.
The problem is next.
There is one application, containing 3 sub-applications. Each of the sub-applications are tested with separate test case, but since they are all part of that one "big" application there are some common functions that are used. One of them is for authenticating the user with inserting credentials. In that  process there is **Register Keyword To Run On Failure  AnotherMethod**, while in that "AnotherMehod" are Log and Capture Page Screenshot along with credentials thing.
Now what happens, in one of the sub-apps, for instance sub_app1, there is loading screen with some image , "image_1.png" for exapmle, but when tests are finished and i check the result it happens , occasionaly, that sub_app1 is marked as PASS, and for instance sub_app2 as FAILED, on some other keyword , after authentication is done, but there is a screenshot made by "AnotherMethod" from sub_app1.

I know it may be confusing so to try to simplify.
APP:
    - sub_app1  PASS (has some loader image)
    - sub_app2  FAIL on some other keyword, not auth
    - sub_app3  PASS (no images in this part)

Result, screenshot is made containing loader image fom sub_app1.
If anyone had simmilar problem, or knows how to fix it, please tell me, or give me your opinion of what might be wrong. This kind of issue is repeating day after day in a random time, with a different sub-applications, i just made an example above, and it's not predictable how or why it happens.

**Comment by aaltat** [comment]
So did I get correctly that you have problems with screen shots. For you, sometimes screen shot in different reports are actually pointing to same picture although they should point to different pictures? Or was it something else and if it was could you explain what the problem actually is?

**Comment by DusanAtanackovic** [comment]
No, what is happening sometimes is next:
Lets say there are 3 apps A,B and C, and three test TA, TB and TC matching their apps. Problem occurs when TA and TC passes and TB fails for example, but screenshot that is made (which should be made on keyword failure) can be made only in TA since it is part of app A. But, obviously TA passed, but TB failed instead which then shouldn't be possible for screen shot to be made. Sorry for typos, if any, writting with a phone. If further explanation is needed  please say i will make more detail analysis once i got home.

**Comment by aaltat** [comment]
I don't quite grasp what you are trying to say, but was it something like this. TA and TC passes, but TB fails. The screen shot is which is taken on TB failure, doesn't show picture from application B, but it shows application A. Was that correct understanding?

**Comment by DusanAtanackovic** [comment]
Yes that is correct, with one addition, function calling Capture Page Scr... is called in all 3 tests, since it is inside log in function.

**Comment by aaltat** [comment]
This can happen from many reasons, example you might be combining test results with `rebot` or are using `pabot`. Or perhaps you are using some other ways to capture screen shot than SeleniumLibrary. Or perhaps you are using fixed filenames when SeleniumLibrary takes the screen shot.

In the SeleniumLibrary screen shot have unique file name, if the file name contains `{}`, when the file is written to the disk. But example post processing multiple outputs, like with pabot, if the file name is not unique across all runs, random overwriting screen shot can happen. Also that context is not controlled by SeleniumLibrary and therefore it can not be fixed (if problem is in the post processing, lots of assumptions) in the SeleniumLibrary code. 

There could be simple solution for your problem, if you don't need the files be separately available. In SeleniumLibrary 4.2 it's possible to embed the screen shot directly to the [log.html](https://github.com/robotframework/SeleniumLibrary/blob/master/docs/SeleniumLibrary-4.2.0.rst#add-ability-of-embedding-screenshots-as-base64-encoded-images-in-the-1497-rc-1). This should ensure that files are never overwritten, because they don't anymore exist. The down side is that size of the output.xml and log.html will grow.

**Comment by DusanAtanackovic** [comment]
I am not using pabot, and i am sure that rebot is not a problem, since this issue dates much before i started using rebot.
 File name containes { } , so file names are unique.
Is there any other keyword except this Register Keyword To Run On Failure which i can try?
Or i can try with Register Keyword To Run On Failure inside every keyword in the test, with same unique name pattern of course. Can you tell me your opinion?
Thank you.

**Comment by aaltat** [comment]
As a quick solution, I would go with the embedding feature. But to investigate issue further, I would need a simple example that I can also run and which demonstrates the problem. Or if that is not possible, then would it be possible to see parts of the log.html where the problem is.

**Comment by DusanAtanackovic** [comment]
Sorry for late response, i was waitting to see if there would be any changes (but there's no any).
Unfortunatelly, i am not able to provide you any log/example due to company policies.
I guess i need to brute-force it. Thank you for your time and help.

**Comment by DusanAtanackovic** [comment]
Ok, i have managed to see exception with screenshoting, It seems it is Fatal Error exception that caused confusion.
