### ISSUE TITLE
Press Keys only presses the period key once

### ISSUE THREAD

**Issue by SchloTech** [robotframework/SeleniumLibrary#1570]
# Prerequisites
- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
I am attempting to load test a guacamole instance by playing youtube videos.  Since I cannot use selectors I have been able to use Press Keys to send keyboard commands to the instance:

Press Keys  none  ALT+F2  #opens up application finder in Ubuntu
Press Keys  none  firefox youtube.com/watch?v=T4zpQvGg8rs  # goes to youtube video in firefox
Press Keys  none  SPACE  # press space to play the video
Sleep  30  # an arbitrary amount of time to sleep
Press Keys  none  ALT+F4  # closes the browser

Then it loops back through to the top but enters a different URL.  The issues is the second URL the '.' before the com doesn't get entered.  I have tried everything I can think of and cannot get this to work.

## Error messages and additional information

One of the most frustrating parts is there is no error message and in the logs.html file I check the press keys command and it says it's entering all the information, including the '.'

## Expected behavior and actual behavior

I'm expecting the robot to enter the entire URL and not skip the '.' before the 'com' in the URL.

## Environment
This is where it gets a little tricky.  I'm using a chrome browser V81 but running a guacamole instance of ubuntu 16.04 Xfce with firefox installed with the latest version.

- Robot Framework 3.1.2 
- Selenium: Version 3.141.0
- SeleniumLibrary: Version 4.3.0
- Interpreter: Python Interpreter 3.6

**Comment by aaltat** [comment]
Actually, I am amazed that it work that well out the browser context in the first run. But Selenium and therefore SeleniumLibrary keywords are meant to work inside of the browser and you are seeking a solution that works in a desktop level. I do not have any idea where to start trouble shoot the problem or how to help you on the matter. The best advice is: if your goal is to automate desktop application it would be better to find library that is actually indented to desktop automation.

Because this is outside of the SeleniumLibrary scope I am closing this issue. For further support, please see: https://github.com/robotframework/SeleniumLibrary#support
