### ISSUE TITLE
How to turn off the prompt "Chrome is under the control of automatic test software"

### ISSUE THREAD

**Issue by Nmzb** [robotframework/SeleniumLibrary#1582]
${options}=    Evaluate    sys.modules["selenium.webdriver"].ChromeOptions()    sys,selenium.webdriver
    @{arg2}    Create List    enable-automation
    Call Method    ${options}    add_experimental_option    useAutomationExtension    False
    Call Method    ${options}    add_experimental_option    excludeSwitches    @{arg2}
    Create WebDriver    Chrome    chrome_options=${options}
    Go To    ${login_url}

Return error
InvalidArgumentException: Message: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse excludeSwitches
from invalid argument: must be a list

**Comment by aaltat** [comment]
Instead of using Create WebDriver keyword, I would look [Open Browser](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Open%20Browser) keyword and the `options` argument. But because this is support case and not an enhancement or bug report issue, I am going to close this issue. For more support see: https://github.com/robotframework/SeleniumLibrary#support

**Comment by Nmzb** [comment]
Hello, I changed the method of the open browser keyword and options parameter to open the browser, but the options parameter did not take effect。
I want to disable chrome pop-up notifications。
${num}    SetVariable    ${2}
    &{prefs_temp}    Create Dictionary    notifications=${num}
    &{prefs}    Create Dictionary    profile.default_content_setting_values=&{prefs_temp}
    Open Browser    https://facebook.com    chrome    options=add_experimental_option('prefs',${prefs})
