### ISSUE TITLE
Is it possible to pass in a parameter to a Javascript file?

### ISSUE THREAD

**Issue by technigirl** [robotframework/SeleniumLibrary#1595]
Hello,

This isn't really an issue so much as a question that I haven't been able to find an answer to anywhere.  I have some Javascript which I am executing as a file, and I need to pass in some text.  I would like to pass it in as the value of ${text}, here is an example:

${text}    Set Variable     mytext
${result}     Execute Javascript    path_to_file/file.js
Log ${result}   

I have not been able to find a way to pass in ${text} to file.js using ARGUMENTS or any other method.  Is there a way to do this?  If there is not, I can file a feature enhancement, but I first would like to know if it's already possible.  Thank you so much!

**Comment by aaltat** [comment]
If the `code` argument points to a file, keyword simply reads the content of the file and pass the content to the underlying Selenium API. Therefore arguments are not for the file but for the JavaScript code in the file.

But because this is indeed support request, I am closing this issue (issue tracker is reserved for bugs and enhanced request.) For more support see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

**Comment by technigirl** [comment]
Hi @aaltat thank you for the response.  Given that when I do try to pass the argument using ARGUMENTS, and it doesn't seem to get passed properly, could it be a bug?

**Comment by aaltat** [comment]
It's possible, library is (most likely) full of different kinds bug's. Specially in edge case's.

To debug problem further, I would remove SeleniumLibrary and Robot Framework out of the picture. It is pretty easy to call the underlying Selenium [execute_script](https://pythonbasics.org/selenium-execute-javascript/) method and I would experiment how it should work. Once your JavaScript works with Selenium, I would bring back SeleniumLibrary. If the JavaScript then does not work, it would proof that there is a bug in the SeleniumLibrary.
