### ISSUE TITLE
[Question] How to handle lifetime management within a plugin?

### ISSUE THREAD

**Issue by rasjani** [robotframework/SeleniumLibrary#1598]
# Preface
* Have a plugin for SeleniumLibrary
* Plugin will start a thread to handle some things that should happen in the background.

This leads to hanging robot execution at exit because the thread is still running. An issue that i see with this is there aint no clear events when my code should stop the thread execution.

# Possible approaches ? 
* I could add LISTENER, but that feels a bit dirty since the plugin itself is not the main "library" (and thus, it might not even work).
* __del__ of the plugin doesnt seem to get called at end of execution.
* offload starting and stopping of separate process to the person/scripts running the tests.

Essentially the scenario is that i want to attach a proxy running in separate thread to a specific driver instance and kill that specific proxy when the driver is closed. This would be straight forward if webdriver.$BrowserName classes could be overwritten as there there is quit() method when a browser is closed.

Any other ideas ?

**Comment by aaltat** [comment]
Have not tough about this problem, because SeleniumLibrary is a single threaded application. So when WebDriver is created, plugin attach/creates a proxy to that WebDriver instances. And when WebDriver `quit()` is called, plugin would need to be notified so that it can stop the proxy. 

Closing browser is done in the [WebDriverCache](https://github.com/robotframework/SeleniumLibrary/blob/fd033f87e15e978dfd2006e60fdf6292bbf3de30/src/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py#L327), by the calling [quit()](https://github.com/robotframework/SeleniumLibrary/blob/fd033f87e15e978dfd2006e60fdf6292bbf3de30/src/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py#L379). There might be multiple browser opened by the SL. would it be enough the be notified when WebDriverCache is empty (all browser are closed) or would you need notification from each WebDriver instance separately? 

Another solution could be that [run_keyword](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py#L467) and do something when closing browser(s) keywords are called.

**Comment by aaltat** [comment]
@rasjani is there something more that you would like to discuss or enhance in the SeleniumLibrary? Or can we close the issue?

**Comment by rasjani** [comment]
@aaltat the question was really answered so this can be closed..

Actually, i can get the "lifetime" management via eventfiringwebdriver. It gets initialized on per created driver basis and then i can wire before_quit() to terminate the proxy.  Problem with this approach is that i then need to juggle with context because the plugin and the listener are not same instances but i got that already in the code so, i guess more wont hurt :D

**Comment by aaltat** [comment]
That is a good solution. Good thinking.
