### ISSUE TITLE
[Question] How to execute javascript with my webElement?

### ISSUE THREAD

**Issue by cgl22** [robotframework/SeleniumLibrary#1599]
There are two elements that overlap.I 'click element'.And received this error:
`ElementClickInterceptedException: Message: element click intercepted: Element <button class="btn btn-success btn-sm" ng-show="selectedClassify.label === 'waitConfirm' &amp;&amp; (!buttonConfig || buttonConfig &amp;&amp; buttonConfig.confirmScheme == 1)" ng-click="confirmBtn(row)">...</button> is not clickable at point (768, 581). Other element would receive the click: <footer class="infi-footer display-none ng-scope display-block" ng-if="!notFooter &amp;&amp; !hideLayout" ng-class="{true: 'display-block'}[!notFooter &amp;&amp; !hideLayout]">...</footer>
  (Session info: headless chrome=80.0.3987.163)
Stacktrace:
#0 0x55817bb9b7a9 <unknown>`

I want to fix it like this:
`WebElement ele = driver.findElement(By.xpath("element_xpath"));
JavascriptExecutor executor = (JavascriptExecutor)driver;
executor.executeScript("arguments[0].click();", ele);`
or this:
`WebElement myelement = driver.findElement(By.id("navigationPageButton"));
JavascriptExecutor jse2 = (JavascriptExecutor)driver;
jse2.executeScript("arguments[0].scrollIntoView()", myelement); `

I find the keyword "Execute Javascript" in docs. But it has no parameter about webElement.
How to execute javascript with my webElement?

**Comment by aaltat** [comment]
The [Execute JavaScript](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Execute%20Javascript) documentation says:

Starting from SeleniumLibrary 3.2 it is possible to provide JavaScript arguments as part of code argument. The JavaScript code and arguments must be separated with JAVASCRIPT and ARGUMENTS markers and must be used exactly with this format. If the Javascript code is first, then the JAVASCRIPT marker is optional. The order of JAVASCRIPT and ARGUMENTS markers can be swapped, but if ARGUMENTS is the first marker, then JAVASCRIPT marker is mandatory. It is only allowed to use JAVASCRIPT and ARGUMENTS markers only one time in the code argument.

The argument parts can be anything what Selenium accepts, which also includes WebElements. Because this was unclear for you, do you have an idea how to improve the documentation?

**Comment by cgl22** [comment]
@aaltat I only noticed the Arguments, and didn't look at the Documentation carefully.Its my mistake.Thank you for your patient answers.
