### ISSUE TITLE
No browser is open issue | FAIL | KeyError: 'sessionId'

### ISSUE THREAD

**Issue by Babug01** [robotframework/SeleniumLibrary#1607]
Hello, I'm looking a help to solve "no browser is open" issue.

Below are my environment and library details
## Environment
Browser: Chrome, version:  83.0.4103.61
Browser driver: chromedriver, version: 83.0.4103.39
Operating System: Windows server 2012 R2
Libraries
Package                                              Version
--------------------------------------- -------
pip                                                        19.2.3
python                                                  3.7.7
robotframework                                   3.2.1
robotframework-extendedselenium2library 0.9.1
robotframework-selenium2library         3.0.0
robotframework-seleniumlibrary           3.3.1
selenium                                               3.141.0
setuptools                                            41.2.0
urllib3                                                  1.25.9

When I run the test cases, I'm getting No browser is open issue | FAIL | KeyError: 'sessionId' error in Jenkins CI.

log.html
![image](https://user-images.githubusercontent.com/42318503/83579388-6a198e00-a539-11ea-8d52-d5855d7767e0.png)

Could you please help me to fix this issue

**Comment by aaltat** [comment]
I am not able to help you because I don't maintain or use the ExtendedSelenium2Library you are using. Also the SeleniumLibrary version is so old that support is not offered for that version.

This issue tracker is reserved for enhancements and issues, but your problem is clearly a support request. Therefore I am closing this issue. For more support, please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support Also for the next time, use the `--loglevel trace` from command line to produce the full stack trace, so that it's easier to see where in the code error happens.
