### ISSUE TITLE
Selenium2Library import false to RobotFramework (REDI editor)

### ISSUE THREAD

**Issue by karelf** [robotframework/SeleniumLibrary#1619]
Hi all.
I have installed Selenium2 library with Robot framework and Ride and have configured corresponding Path variables.
When import Selenium2Libray, the library name was red,
and send command:

PS C:\Python27\lib\site-packages\Selenium2Library> python -c "import Selenium2Library"
PS C:\Python27\lib\site-packages\Selenium2Library> python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

            x = Selenium2Library.Selenium2Library()
            Traceback (most recent call last):
            File "", line 1, in
            NameError: name 'Selenium2Library' is not defined

I can't find the mistake, please advise

**Comment by aaltat** [comment]
1) Please note that `Selenium2Library` is not anymore maintained and users should move to `SeleniumLibrary`. Therefore I do not provide support for Selenium2Library. 
1) Python 2 has reached end of life at April 2020 and users should migrate to Python 3 as soon as possible. 

That being said, this should work:
````
C:\Python27\> python 
>>> import Selenium2Library
>>> x = Selenium2Library.Selenium2Library()
````

For more support please https://github.com/robotframework/SeleniumLibrary#support

Also because this support request for something which is not supported by me, I will close this issue.
