### ISSUE TITLE
Support holding shift and control when using `Mouse Over`

### ISSUE THREAD

**Issue by krassowski** [robotframework/SeleniumLibrary#1639]
I would like to be able to test a feature that triggers when the user hovers over a specified element with a modifier key pressed, e.g. <kbd>Ctrl</kbd>. This essentially the same as #905, but for `Mouse Over` rather than for `Click Element`. Would adding an optional argument for `Mouse Over` be in scope?

**Comment by aaltat** [comment]
Hmmm, by quickly looking at Selenium API, I don't see clear way to do it. You could also try with experimenting Selenium action chains and see is there solution for for you. If you find solution we could consider implementing it SL side.

**Comment by krassowski** [comment]
I see. Thank very much you for a quick reply! Before posing I skimmed this [Stack Overflow question](https://stackoverflow.com/questions/17756532/how-to-hold-key-down-with-selenium) and my impression was that it is achievable - but I understand that it might not be a clean/reliable solution.

**Comment by aaltat** [comment]
That is pretty low level stuff and although it might work, I am little bit reluctant to have it. Mainly because it is not in the public API. But luckily its pretty easy to build a plugin and implement that. For more about plugin please see https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst

**Comment by aaltat** [comment]
Not going to implement this one, closing
