### ISSUE TITLE
Not supported syntax in __init__.pyi

### ISSUE THREAD

**Issue by doyou89** [robotframework/SeleniumLibrary#1685]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/MarketSquare/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Warning message can be seen when defining a sub class of `SeleniumLibrary` as below:
```python
from SeleniumLibrary import SeleniumLibrary
class MyCls(SeleniumLibrary):
    def __init__(self, timeout=5.0, implicit_wait=0.0, run_on_failure=None, screenshot_root_directory=None,
                 plugins=None, event_firing_webdriver=None):
        super().__init__(timeout, implicit_wait, run_on_failure, screenshot_root_directory,
                         plugins, event_firing_webdriver)
```

## Error messages and additional information

IDE shows "unexpected argument" warning on all parameters except `timeout` of `super().__init__()`.

When mouse over `super().__init__`, IDE shows the definition of `__init__` as below:
```python
def __init__(self, timeout: int = 0) -> None
```

## Expected behavior and actual behavior

In `__init__.pyi` file, `__init__` defines as below:
```python
def __init__(self, timeout = 0:00:05, implicit_wait = 0:00:00, run_on_failure = 'Capture Page Screenshot', screenshot_root_directory: Optional[str] = None, plugins: Optional[str] = None, event_firing_webdriver: Optional[str] = None): ...
```

IDE said `timeout = 0:00:05` is not supported syntax.
This line may should be:
```python
def __init__(self, timeout = 5, implicit_wait = 0, run_on_failure = 'Capture Page Screenshot', screenshot_root_directory: Optional[str] = None, plugins: Optional[str] = None, event_firing_webdriver: Optional[str] = None): ...
```

## Environment

Browser: N/A
Browser driver: N/A
Operating System: N/A
Libraries
- Robot Framework: 3.2.2
- Selenium: 3.141.0
- SeleniumLibrary: 5.0.0
- Interpreter: python 3.8 & 3.9
IDE: pycharm & vscode

# Feature requests

**Comment by aaltat** [comment]
There is bug, but your IDE is correct when it complains. Because the [\_\_init__.py](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py#L424-L432)
contains:
```
    def __init__(
        self,
        timeout=timedelta(seconds=5),
        implicit_wait=timedelta(seconds=0),
        run_on_failure="Capture Page Screenshot",
        screenshot_root_directory: Optional[str] = None,
        plugins: Optional[str] = None,
        event_firing_webdriver: Optional[str] = None,
    ):
```
As can been, `timeout` and `implicit_wait` are defined as Python [timedelta](https://docs.python.org/3/library/datetime.html#timedelta-objects) objects. But the [\_\_init__.pyi](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.pyi#L3) contains
```
def __init__(self, timeout = 0:00:05, implicit_wait = 0:00:00, run_on_failure = 'Capture Page Screenshot', screenshot_root_directory: Optional[str] = None, plugins: Optional[str] = None, event_firing_webdriver: Optional[str] = None): ...
```
And as can be seen, `timeout` and `implicit_wait` are defined in very wrong way and that is a bug. 

**Some explanation.** 
The typehint for  `timeout` and `implicit_wait` are defined as `timedelta` because then Robot Framework does [automatic conversion](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#supported-conversions). It helps to get grid of some code conversions in the SL side. 

Both the argument accepts also [objects](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/utils/types.py#L31) that are in [time format](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#time-format) supported by Robot Framework. We could enhance the `typehint` if RF is still able to do the conversion for us correctly.
