### ISSUE TITLE
AttributeError: 'Selenium2Library' object has no attribute '*FireFox'

### ISSUE THREAD

**Issue by sskhan** [robotframework/SeleniumLibrary#169]
I have python 2.6 and I just installed selenium2 trying to run my test case and getting following error:
#  pybot myFirstTest.txt 
# myFirstTest :: This is your first test                                        

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
Go To Google Page [Documentation] Go to google page and search som... | FAIL |
## AttributeError: 'Selenium2Library' object has no attribute '*FireFox'

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
Open Selenium Page [Documentation] TestCase for open Selenium page    | FAIL |
No browser is open

**Comment by ombre42** [comment]
See the browser names in the [keyword documentation](http://rtomac.github.com/robotframework-selenium2library/doc/Selenium2Library.html#Open Browser)
Use ff or firefox for Firefox instead of *FireFox.
And don't forget to turn off auto update as Selenium usually does not work with the very latest Firefox.

**Comment by sskhan** [comment]
I tried and now its giving me following error:

# myFirstTest :: This is your first test                                        

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
Go To Google Page [Documentation] Go to google page and search som... | FAIL |

## AttributeError: 'NoneType' object has no attribute 'rfind'

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
Open Selenium Page [Documentation] TestCase for open Selenium page    | FAIL |

## No browser is open

myFirstTest :: This is your first test                                | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed

**Comment by ombre42** [comment]
hmmm....neither Selenium2Library or Selenium use rfind
I bet that error is occuring inside Robot Framework due to your test data not being parsed correctly.
Perhaps copying/pasting from a blog post led to format issue?
To see a stacktrace of the failure you can run Robot Framework with these arguments:
--logLevel DEBUG
For support you are better off posting to [user group](http://groups.google.com/group/robotframework-users) for Robot Framework.
You can attach logs and test data to forum post so that others can try to reproduce or analyze your issue.
Without seeing the test you are running I can only guess where things went wrong.

**Comment by sskhan** [comment]
I am trying to run the code on following link:
http://www.wallix.org/2011/07/26/how-to-use-robotframework-with-the-selenium-library/
in common.txt I change Browser to ff instead of chrome

**Comment by sskhan** [comment]
Please any one I am really not able top figure whats the prob is. I remove the proxy and check even then not able to make it work

**Comment by emanlove** [comment]
Unable to reproduce. If this is still an issue please try emailing the [mailing list](https://groups.google.com/d/forum/robotframework-users).

**Comment by ombre42** [comment]
This was fixed in 1.4 by [232](https://github.com/rtomac/robotframework-selenium2library/pull/232)
