### ISSUE TITLE
Compare two tables using SeleniumLibrary

### ISSUE THREAD

**Issue by anilreddy** [robotframework/SeleniumLibrary#1719]
Hi,

I need a way to compare two tables containing similar details using Selenium Library. For example I have table like below:

https://www.w3schools.com/html/html_tables.asp
In the above table there are headers and columns I need to first convert them into maps like this

Country is key and values are like below:

```python
{
"Country": "Germany", "Mexico", "Austria", etc.,
}
```
Is there a keyword for it?
and then compare both tables like maps.

I know it is a issues page but am unable to find answers in stack overflow. Can you please tell me a way

https://stackoverflow.com/questions/58523962/how-to-extract-a-table-data-and-and-keep-it-in-a-key-value-pair-using-robotframe?noredirect=1#comment103373645_58523962

Thanks,
Anil Reddy Gaddam

**Comment by rasjani** [comment]
Construct suitable selector that returns all td elements. Iterate over each and store the values to list. But you will most likely get better answers in community forums at https://forum.robotframework.org or rf slack. 

And because this is support request, I am closing this issue. Issue tracker is reserved for bug reports or enhancement request.
