### ISSUE TITLE
Add Keywords and/or Extensions for Sauce Labs

### ISSUE THREAD

**Issue by joshmgrant** [robotframework/SeleniumLibrary#1725]
Hello. I would like to suggest adding some kind of integration with Sauce Labs with the Seleniumlibrary. 

Here's an example of how to use Sauce Labs with SeleniumLibary now: 

https://github.com/saucelabs-training/demo-python/blob/master/examples/robotframework/desktop_web/Tests/resource.robot

After some discussion with @aaltat, there were a few possible approaches: 

- Add keywords to the SeleniumLibrary directly for use with Sauce Labs. This may not be suitable since connecting a cloud service isn't a "pure" Selenium feature. 
- Create an [extension of the SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst#plugins), which may be more work but might be more suitable for the task here.

I'm open to either of these approaches. Thanks so much!

**Comment by BrewerJack** [comment]
What would be gained by doing this as opposed to other approaches?  Your example shows how it is almost trivial to add that functionality to test suites, why not add a SauceLabs library separate from the Selenium library?  I think the mixing of functionality would be a mistake, especially since not everyone uses SauceLabs.

**Comment by joshmgrant** [comment]
Great point @BrewerJack, particularly this: 

> Your example shows how it is almost trivial to add that functionality to test suites

This is true, but many Sauce users struggle with getting the right capabilities set up (which ones to include, what are the values, users forgetting some, etc). Plus the Selenium remote URLs are Sauce specific and sensible "defaults" could be set up for easier usage for Sauce users. 

I'd like to provide a nicer user experience for users who want to use SeleniumLibrary with Sauce but a whole library might be too much. In most cases, keywords would be 95% the same and no new ones would be added, except for connecting to the remote Selenium URLs, starting a browser session, and closing a browser session (probably). I'm trying to figure out the best way to do this without creating too much overhead/maintenance.

**Comment by rasjani** [comment]
@joshmgrant  Personal opinion, i'd prefer to not have anything outside of real upstream aka Selenium directly integrated into SeleniumLibrary itself (as you noted in 1.) but i guess this is something i need to clarify with @aaltat  before saying hard no.

Anyway, since this is a "new feature" that wont be backported to older SeleniumLibrary versions, my gut feeling is that using a plugin system should be flexible enough. Since its introduction, there hasn't been any major issues regarding maintenance at least with SeleniumTestability.  If you need direct consultation, feel free to ping on selenium slack (same nick there) 

Anyway, few questions:

If i read the linked resource correctly,  there are few things "needed" for Sauce Labs integration:

* Passing of valid data via desired_capabilities that contains auth and runner data .. 
* Running sauce specific javascript at the end of the test execution to mark the run as either passed or failed ..  I assume this pass fail in the example is related to `build` property in above ?
* Are there other scenarios where these custom sauce:* javascripts are either required or not mandatory but helpful for the testing in some form ? 

Anyway, more I think about this, the more i feel that maintaining this sort of functionality  would be better to be done as SL plugin .. 

And im going off a bit in a tangent but this proposal made me think about one idea i've had since or even before SL had a plugin system  - so ping @aaltat / @pekkaklarck  etc ? 

Current implementation of plugins in SL requires explicitly to declare those in Library statement. This can lead to scenarios where where some parts of the whole execution, there are selenium instances where SL does not have plugin keywords available and some parts where they are - i guess we have discussed this with at least Tatu .. 

To counter this, if SL would actually scan possible available plugins[0] at the instantiation time and each plugin would handle it's own configuration by say, envs/config files or such .. There would be no painful "why oh why this doesn't work" if introducing plugins into existing projects and it would also serve a purpose of providing such features like Josh is now proposing to be more easier to integrate - just `python -mpip install rfslp-saucelabs` and maybe provide a sort of blacklist feature that quarantees that non wanted or conflicting plugins  won't be initialized.. 

[0] https://packaging.python.org/guides/creating-and-discovering-plugins/

**Comment by pekkaklarck** [comment]
For me this sounds more like a plugin functionality than core SL functionality. A great thing with plugins is that they can be developed (and maintained) independently from SL. This means they aren't tied to its release schedule etc. and also that SL maintainers don't get extra work.

Enhancing SL plugin system so that it would use Python's plugin API as suggested by @rasjani sounds like a really good idea to me.

**Comment by joshmgrant** [comment]
Alright, based on this discussion (thank you all for the input!) I'm thinking that the best way forward is to create a Sauce Labs plugin instead of either adding keywords directly to the SeleniumLibrary or writing a Sauce Labs library. 

I'm cautiously optimistic this won't be too difficult. I'll close this request. Thanks!

**Comment by emanlove** [comment]
@joshmgrant If you want a collaborator on building that plug-in I can assist you.
