### ISSUE TITLE
Run Keyword And Ignore Error - disable  screenshots

### ISSUE THREAD

**Issue by PapsOu** [robotframework/SeleniumLibrary#1735]
# Prerequisites

- [x] I have searched for similar issues in open tickets and cannot find a duplicate.
- [x] The issue still exists against the latest released version of SeleniumLibrary.
- [x] This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- [x] You are not using the Java Selenium2Library: https://github.com/MarketSquare/robotframework-seleniumlibrary-java
- [x] Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

```robot
*** Test Cases ***

Test Example

    Go To                               https://www.google.com/

    Run Keyword And Ignore Error        Click Element                           //wrong_xpath_locator

    Run Keyword And Ignore Error        Click Element                           //input[@type="search"]
```

## Error messages and additional information

![image](https://user-images.githubusercontent.com/5792207/122734210-2b5a9100-d27e-11eb-9762-bead2a67d1d6.png)

## Expected behavior and actual behavior

When using keyword `Run Keyword And Ignore Error` (`Run Keyword And Ignore Error        Click Element                           //wrong_xpath_locator`), the keyword `Capture Page Screenshot` should not be called.

## Environment

Browser: `Chromium Version 86.0.4240.111`
Browser driver: `Robot Framework 4.0 (Python 3.9.0 on linux)`
Operating System: through docker : `python:3.9.0-alpine3.12`
Libraries : see https://github.com/ppodgorsek/docker-robot-framework

# Feature requests

May be it should be useful to add an argument to the keyword `Run Keyword And Ignore Error` in order to keep capturing active, and the default would disable capture of the error.

**Comment by aaltat** [comment]
I think what you want, can be achieved with listener and keeping track of the `Run Keyword...` status and configuring the library. But looking issue from the library perspective, the library does not know the parent keywords, because RF core does not provide such functionality out of the box. Keywords are just called as methods from the library, with the arguments it needs in the method call. There is not extra meta or context information available and therefore library can not do this out of the box. 

Therefore I am going to close this issue, because such feature is out of the scope of the SeleniumLibrary and feels something which could be build as a listener or as plugin for the SeleniumLibrary.
