### ISSUE TITLE
Selenium Library keywords undefined in VS Code

### ISSUE THREAD

**Issue by mizzPpY** [robotframework/SeleniumLibrary#1736]
I have installed the following packages:
- robotframework==4.0.3
- robotframework-pythonlibcore==3.0.0
- robotframework-seleniumlibrary==5.1.3
- selenium==3.141.0
- webdrivermanager==0.10.0

I also installed extension Robot Framework Language Server v0.18.0 in VS Code, however all the Selenium library keywords are displayed as "Undefined keyword" in the editor. 
![image](https://user-images.githubusercontent.com/70636744/123801106-85adbe80-d91c-11eb-8676-472f6ece4304.png)

It is working fine when execute the robot files, but is really difficult to write test cases when no intellisense for Selenium keywords and the entire files seems like full of error due to undefined keywords. Is there any thing I missed or I can add so that VS Code can recognize the keywords from Selenium Library?

## Environment
Operating System: Windows 10 64-bit
Libraries
- Robot Framework: 4.0.3
- Selenium: 3.141.0
- SeleniumLibrary: 5.1.3
- Interpreter: Visual Studio Code Version 1.57.1

**Comment by aaltat** [comment]
No idea, you need to consult plugin [project](https://github.com/robocorp/robotframework-lsp) how debug these kind of problems or ask in [community](https://github.com/robotframework/SeleniumLibrary#community)

Because test are working fine this is not problem with SeleniumLibrary and I will close the issue.
