### ISSUE TITLE
How replace desired_capabilities for Browserstack integration

### ISSUE THREAD

**Issue by anthonyOSF** [robotframework/SeleniumLibrary#1876]
Hello, 

Since desired_capabilities are deprecated, i would like to know which syntax i should use now

**Code Before**
 Open Browser    ${URL}  |  ${BROWSER}  | remote_url=${RemoteURL} | desired_capabilities=project:myprojectname,name:${TEST_NAME},browser:${BROWSER}

The seleniumlibrary documentation tells us to use the argument option, can you give me an example?

_SeleniumLibrary 6.2.0
RobotFramework 6.1.1_

Thanks a lot

**Comment by emanlove** [comment]
@anthonyOSF Going to try to give first a partial answer and explain later so you have something to start working on. Pressed on a few things at the moment and might not get back to this for a day or so ..

Short answer .. from [here](https://github.com/browserstack/python-selenium-browserstack/blob/main/scripts/local.py#L40) and [here](https://www.selenium.dev/selenium/docs/api/py/webdriver/selenium.webdriver.common.options.html#selenium.webdriver.common.options.ArgOptions.set_capability) and a few [other places](https://www.browserstack.com/automate/selenium-4#selenium4-examples) including [here](https://robotframework.slack.com/archives/C07PKKCTF/p1700185588382519?thread_ts=1697794943.942079&cid=C07PKKCTF) I believe it should start to look like

```robotframework
Open Browser ${URL} | ${BROWSER} | remote_url=${RemoteURL} | options=set_capability("bstack:options", {'projectName' : 'myprojectname', 'sessionName' : '${TEST_NAME}'})
```

In the above I don't use the last desired_capabilities of browser as I could not seem to find how Browserstack is shifting the previous desired capabilities to options for this specifc value using [this document](https://www.browserstack.com/automate/selenium-4). There is [browserName](https://www.selenium.dev/documentation/webdriver/drivers/options/#browsername) - _noting that the python selenium bindings choose to go with the underscore instead of camel case spelling of all these options_ - but I think this is handle by using the Chrome Options class which SeleniumLibrary does internally. Gouing to hand this off now and let you do so debugging and trying out .. will come back later with some more explanation of how I got here .. have a good day! :)

**Comment by anthonyOSF** [comment]
Hello @emanlove, thx a lot ! it was exactly what i needed ! 
Thank you for your quick and precise response.
