### ISSUE TITLE
Press Key dosen't work

### ISSUE THREAD

**Issue by luislu** [robotframework/SeleniumLibrary#198]
I want to use keyword "Press Key" to simulate pressing "enter" function, but it dosen't work 

**\* Settings ***
Library           Selenium2Library

**\* Test Cases ***
T1
    Open Browser    http://baidu.com    chrome
    Input Text    id=kw    test
    Sleep    5s
    Press Key    id=kw    \13

**Comment by ombre42** [comment]
The documentation for Press Key shows using a backslash for the key
argument. In order to send the backslash correctly, you must escape the
backslash with another backslash due to RF's syntax (see
http://robotframework.googlecode.com/hg/doc/userguide/RobotFrameworkUserGuide.html?r=2.7.7#escaping
).
I think this has tripped up just about everyone, including me.

Your suite file should look like this:

```
*** Settings ***
Library           Selenium2Library

*** Test Cases ***
T1
    Open Browser    http://baidu.com    chrome
    Input Text    id=kw    test
    Sleep    5s
    Press Key    id=kw    \\13
```

This test performed the search for me.

**Comment by luislu** [comment]
Thanks for your replying.
I just follow the press key introduction in keyword document.

**Comment by WillDev10** [comment]
Thanks to poster who created this. Saved me a lot of time and hassle. Can't believe it's _still_ open though. :-(

**Comment by ombre42** [comment]
#200 describes the fix for what this issue was about
