### ISSUE TITLE
Fail to Start IE in a remote Machine?

### ISSUE THREAD

**Issue by cookie314** [robotframework/SeleniumLibrary#223]
Hi, guys,
I'm using Selenium Gird to do our test.  
I can start IE on local (just set the IEDriver dir in PATH), I can start firefox on a remote machine(use selenium remote server). But when I want to start IE on a remote machine, it say that:
 The path to the driver executable must be set by the webdriver.ie.driver system property
I google it, I know how to use java to start this, but I'm using seleniu2library, how the set this? Help!!!!!!!!!!
Thank you!!

**Comment by ombre42** [comment]
You do not need to use Java and set webdriver.ie.driver if the standalone server can find the server using the PATH variable. I would double check that the server is really on the path for the standalone server.
If you are setting the path via the System Properties, remember that:
- changes are not reflected in running processes or new processes launched from existing processes since they inherit their environmental variables from their parent process (e.g. launched by Jenkins slave agent)
- if you are setting the user variable PATH, make sure the process launching Selenium server is running under the same user
  However you are launching the node, put a call to launch IEDriverServer.exe with no path instead of Selenium and see if the server is launched successfully

To simplify things, you can test launching the browser by:
1. navigate to http://localhost:4444/wd/hub
2. click Create Session
3. select internet explorer
4. click OK
5. check for exception in console window or see if IE was launched

**Comment by cookie314** [comment]
@ombre42 
Great！With your help, it's much easier to do troubleshooting. The root cause is that I didn't re-start the instance, so the process is a child-process, and the environmental variables didn't change actually.
Thank you very much! You're patient~
