### ISSUE TITLE
ChromeDriver process not exited after Close Browser

### ISSUE THREAD

**Issue by finnhughes** [robotframework/SeleniumLibrary#267]
I'm creating my browser with
`Create WebDriver  Chrome  chrome_options=${options}`
And after my tests I call `Close Browser`
And can see the browser object is being closed in the log
`DEBUG - Closing browser with session id 1108d82972ba48ae17398c425cbae183`

However ps shows that chromedriver is still running, I think it should have been closed?

I'm using chrome_options to set debuggerAddress so that chromedriver can connect to a remote instance of chrome and for all I know that could have an impact?

```
${options}=  Evaluate  sys.modules['selenium.webdriver'].ChromeOptions()  sys, selenium.webdriver
${debug}=  Create Dictionary  debuggerAddress  localhost:${port}
${options._experimental_options}=  Set Variable  ${debug}
```

Robot Framework 2.8.3
Selinium2Library 1.5.0

**Comment by j1z0** [comment]
Actually this is supposed to work this way. It's expensive to start up chrome driver and chrome driver is not actually the web browser it's the selenium remote server for chrome. Thus chrome driver won't get killed with close browser. 

Cheers,
Jeremy

**Comment by finnhughes** [comment]
Thanks, I mistakenly thought that I was getting a new chromedriver each time I ran the test but I guess that I had some left over processes from earlier debugging.

**Comment by ombre42** [comment]
@finnhughes I run into this a lot when doing ad hoc things. Try to remember to put Close All Browsers in or as the suite or test teardown. If you kill the RF process (e.g. hitting stop twice in RIDE), you may have leftover processes. Each webdriver gets its own chromedriver instance/process that should exit when you execute Close Browser/Close All Browsers. Jeremy is probably thinking of the Selenium standalone server, which does stay running. This issue was about a "local" Chrome browser.
