### ISSUE TITLE
Window keywords fail if window.id is an unexpected type

### ISSUE THREAD

**Issue by pr0chz** [robotframework/SeleniumLibrary#270]
Example:
`Select Window     name=view_more_data`

Result:
`TypeError: object of type 'bool' has no len()`

This also applies to other functions regarding working with windows. OS Windows 7, versions used:

```
robotframework-selenium2library (1.5.0)
selenium (2.39.0)
```

Tested on Firefox and IE, both broken.

Problems seems to reside in function get_current_window_info in webdrivermonkeypatches.py. If you erase `len(att)` in:

```
        atts = [ att if att is not None and len(att) else 'undefined'
            for att in atts ]
```

it starts to work ok. Not sure if it does not brake anything else though.

**Comment by HelioGuilherme66** [comment]
Hi,

I have tested in Linux CentOS 6.5 (x64bit), Firefox, and no problems here.
Attached test and logs.

Hélio

**Comment by ombre42** [comment]
I suspect the problem might be with the window ID. It is not part of any specification AFAIK. Probably used because popular frameworks use window.id.
Could you please run something like this to see which attribute is a bool?

```
    @{attribs}=    Execute Javascript    return new Array(window.id, window.name, document.title, document.url);
    :FOR    ${attrib}    IN    @{attribs}
    \    ${type}=    Convert To String    ${attrib.__class__}
    \    Log    ${type}: ${attrib}
```

Also are you able to reproduce this on different websites?

**Comment by pr0chz** [comment]
I guess your suspicion is right:

```
INFO    Executing JavaScript: return new Array(window.id, window.name, document.title, document.url);
INFO    @{attribs} = [ False | view_more_data | title | url | None ]
```

I have not tried to reproduce problem elsewhere and I guess it'll work as the cause seems to be boolean instead of window.id. Window is created from js like this:

```
window.open('view_more_data.jsp?id_call=1234','view_more_data','location=0, menubar=0, directories=0, toolbar=0,status=0, width=600, height=410, scrollbars=yes, resizable=yes')
```

**Comment by HelioGuilherme66** [comment]
In my test the window name is set onload.

## See below my tests:

testing.html

<HTML>
<HEAD>
<TITLE>Main Page</TITLE>

<script language="JavaScript" type="text/javascript">
function makeFrame() {
   ifrm = document.createElement("IFRAME");
   ifrm.setAttribute("src", "file:./view_more_data.html");
   ifrm.setAttribute("name","view_more_data" );
   ifrm.style.width = 640+"px";
   ifrm.style.height = 480+"px";
   document.body.appendChild(ifrm);
}
// Popup window code
function newPopup(url) {
    popupWindow = window.open(
url,'popUpWindow','height=700,width=800,left=10,top=10,resizable=yes,name=view_more_data,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes')
}
</script>

</HEAD>
<BODY><p><a href="#" onMouseDown="makeFrame()" name="Go">GO!</a></p>
<a href="JavaScript:newPopup('file:./view_more_data.html');">View More
Data</a>
</BODY>
</HTML>

---

view_more_data.html

<HTML>
<HEAD>
<TITLE>Data Page</TITLE>
</HEAD>
<BODY onload="window.name = 'view_more_data'; ">

<P>Data</P>

<QUOTE>
Data    Values <br>
1    22 <br>
2    33 <br>
3    44 <br>
4    55 <br>
5    66 <br>
</QUOTE>
</BODY>
</HTML>

---

testing.txt

**\* Settings ***
Suite Teardown    Close All Browsers
Library           Selenium2Library

**\* Test Cases ***
Open Test Page
    Open Browser    file:///tmp/testing.html

Simple test
    Click Link    name=Go
    Click Link    View More Data
    Select Window    Main Page    #selects main window
    Sleep    5 seconds
    Select Window    Data Page
    Capture Page Screenshot    data_page.png
    Sleep    5 seconds
    Select Window    Main Page
    Capture Page Screenshot    main_page.png
    Sleep    5 seconds
    Select Window    name=view_more_data
    Run Keyword And Expect Error    \*    Select Window
name=unexistent_window

---

**Comment by ombre42** [comment]
@HelioGuilherme66 Trying to reproduce your issue, I saw a problem in Chrome and put a simplified test under #213.  If the error you are not getting is not _"WebDriverException: Message: u"unknown error: 'name' must be a nonempty string..."_ with Chrome, could you please provide more detail - error message, Selenium version, driver version, and traceback?

**Comment by ombre42** [comment]
@pr0chy Thanks for providing more information. I renamed the issue accordingly. Get Window Titles, etc. would have the same issue.

**Comment by ombre42** [comment]
I am thinking of changing
`atts = [ att if att is not None and len(att) else 'undefined' for att in atts ]`
to
`atts = [ unicode(att) if att is not None and len(unicode(att)) else 'undefined' for att in atts ]`
rather than what was proposed in #272
All of these attributes should be strings, except for window.id, which could be anything. I still have no idea where window.id came from. Select Window could not use this value in SeleniumLibrary or Selenium2Library. So what is or was the point of Get Window Identifiers in SeleniumLibrary or Selenium2Library????

**Comment by boakley** [comment]
I did a little more debugging of this and discovered some very odd behavior that I don't understand. Consider this line of code in get_current_window_info:

```
    id_, name, title, url = self.execute_script("return [ window.id, window.name, document.title, document.URL ];
```

I'm finding that sometimes this won't return a list of four elements. Instead, it returns a single WebElement object. Then, the later code fails because it tries to iterate over the single WebElement object when it expects a list. I don't understand why `self.execute_script("return [ ...]")` is returning a WebElement, however.  That makes no sense, but I have zero familiarity with the selenium bindings, so maybe it's acting as designed?

I added a pdb breakpoint and was able to observe that any call that looked like `return [...]` always returned an instance of a WebElement. Here's some of the output from that session:

```
(Pdb) self.execute_script("return window.id") 
u'unique'
(Pdb) self.execute_script("return [ window.id, window.name]")
<selenium.webdriver.remote.webelement.WebElement object at 0x0368AAF0>
```

A fix that worked for me is to fetch each item individually. It's less efficient, but since you rarely iterate over a bunch of windows in a loop, the inefficiency is tolerable:

```
def get_current_window_info(self):
    id_ = self.execute_script("return window.id")
    name= self.execute_script("return window.name")
    title= self.execute_script("return document.title")
    url= self.execute_script("return document.URL")

    id_ = id_ if id_ is not None else 'undefined'
    name, title, url = (att if att else 'undefined' for att in (name, title, url))
    return self.current_window_handle, id_, name, title, url
```

I am unable to duplicate this with a simple case. Perhaps there's a deep bug somewhere that causes `execute_script` to return a WebElement?

**Comment by ombre42** [comment]
Bryan, thank you so much for all that information. Unfortunately, I have seen wonky [behavior like this](https://code.google.com/p/selenium/issues/detail?id=4999) before.
Probably a bug in the server-side of Se. Which browser/driver verion did you see this behavior in?
Originally I considered not getting or returning `window.id` in `get_current_window_info`, but then thought someone might be calling `get_current_window_info` in a library extension and so took what I thought was the safer route.

In light of your observations, I'm thinking of changing it to `return self.current_window_handle, "not fetched", name, title, url` and not even fetch the window id, which is only used by `Get Window Identifiers`, which can iterate over the windows on its own.

**Comment by boakley** [comment]
We are seeing the behavior with IE 9. It's the only browser we're trying
right now.

I don't think the id is the culprit here. Like I said, the entire list is
coming back as a single WebElement. From a pdb prompt I did
`self.execute_script("return [ 1, 2 ]")` and that also came back as a
WebElement. Very odd. It seems like `self.execute` was converting any list
to a WebElement.

I wish I could duplicate it, but so far we can only trigger it in parts of
our application. Some of our popups don't exhibit this behavior, but I
can't see any significant differences between the popups that work that
those that don't. It would be a good exercise to rewrite our test as a pure
python/selenium test to see if it's a selenium issue, but I just don't have
the bandwidth.

**Comment by ombre42** [comment]
Thanks Bryan. I guess I'll just leave it as is. We have problems with IE8 where once you go to a particular page, Input Text stops working in that window and we have to set text via Execute Javascript and use Simulate. 
I also have had to use scrollIntoView when Selenium failed to scroll for me. I extracted out a standalone page to demonstrate the issue to the Selenium team, but the standalone page will not reproduce it >:(
Probably does not make you feel better, but at least know you are not alone is struggling with strange IE/Selenium behavior.

**Comment by boakley** [comment]
Instead of leaving it as-is, can you implement the change I suggested? That
is, getting each value individually? It's a tiny performance hit but seems
to make the keyword more stable.

**Comment by pekkaklarck** [comment]
This keyword could also be enhanced to allow selecting what info to return similarly as [Process.get_process_result](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/Process.py#L655).

**Comment by boakley** [comment]
I realize this issue is closed (without being fixed?), but I got sidelined with an illness before I could post this, and then forgot all about it. We have a monkeypatch that seems to work around this issue quite nicely. Any chance you could add this to the next release of Selenium2Library?

We replace get_current_window_info with the following code, which is the barely-slower-but-more-robust suggestion I made in an earlier comment, which is to fetch the values individually:

```
def _patch_270(self):
    '''This fixes Selenium2Library issue 270 
    https://github.com/rtomac/robotframework-selenium2library/issues/270
    '''

    # it's more efficient to get this data in one call to self.execute_script
    # but we're observing that under some circumstances that doesn't
    # work. Getting the values individually seems to work better.
    id_ = self.execute_script("return window.id")
    name= self.execute_script("return window.name")
    title= self.execute_script("return document.title")
    url= self.execute_script("return document.URL")

    id_ = id_ if id_ is not None else 'undefined'
    name, title, url = (att if att else 'undefined' for att in (name, title, url))
    return self.current_window_handle, id_, name, title, url
```

**Comment by just-be-dev** [comment]
I got a notice on Twitter that this issue hasn't been fixed. I'm going to reopen it and take a look at @boakley's last suggestion.

**Comment by markussammallahti** [comment]
I found out the reason for this issue.

I had input element on a page that had attribute id with value id.

```
<input type="hidden" id="id" />
```

This element is assigned to _window.id_ and therefore it has unexpected type. In my case the error was "TypeError: object of type 'WebElement' has no len()".

I guess for @pr0chy the reason is that somewhere on the page in javascript code you assign boolean value to undefined variable name _id_.

```
// this sets window.id 
id = true;

// propably should be like this
var id = true;
```
