### ISSUE TITLE
'Set cookie' keyword does not work in Firefox 26.0.

### ISSUE THREAD

**Issue by tisto** [robotframework/SeleniumLibrary#273]
Software:

Ubuntu 13.10
Firefox 26.0
robotframework 2.8.4
robotframework-selenium2library 1.5.0
selenium 2.39.0

Steps to reproduce:

1) Write robot framework keyword that sets a cookie "Add Cookie  autologin  admin"

2) Reading the cookie with "Get Cookie Value" works fine.

3) Pause the execution after the keyword and go to the firefox js console to read the cookie "document.cookies"

4) "document.cookies" will be empty

See https://github.com/tisto/robotframework-djangolibrary/blob/master/DjangoLibrary/tests/autologin.robot#L34 for the full test that I used.

I tried the same setup with Chrome (32) and everything works as expected, therefore this might be a selenium/webdriver bug. Please let me know if I should file a bug report there.

**Comment by ombre42** [comment]
The problem is that when running in private mode, the cookie manager Selenium uses is disconnected from the browser - this is an upstream issue. This is affecting GCLI/Developer Toolbar (Shift+F2) as well. The solution is to use a non-default FIrefox profile that does not have in private browsing enabld until #177 is fixed. Closing as this is essentially the same issue. See more in #177
