### ISSUE TITLE
Improve Decoupling between S2L and Robot

### ISSUE THREAD

**Issue by dpsfrishberg** [robotframework/SeleniumLibrary#274]
Hi there. I'm working at a large government organization that has been evaluating Selenium2Library as our testing framework. After trying to write our own library on top of Selenium's WebDriver API for use in unittests, we discovered RF and S2L and were really impressed with S2L's modularity and with how easy it was to use S2L outside of Robot framework (i.e. with a Python unittest). Why would we want to do this? Well, to be honest, so far we've found that whatever you can do in a unittest you can do by writing keywords for your Robot test—but the design of the library is already so conducive to this that it's tempting to try to keep it that way, and we'd like to keep our options open for how we write and run our tests.

One thing we've started doing, in addition to running outside RF, is creating "page objects"--libraries that do functionality specific to our applications while using S2L to interact with Selenium. We're not subclassing S2L in our libraries (because we don't want to redefine all S2L's keywords (which would create a conflict) and expose them unless the user asks for them), and because our page objects are not conceptually inheriting from, but are more hiding S2L.

So, I noticed that one place in which the library is coupled to Robot is in keywords/_runonfailure.py. There is a call to robot.libraries.BuiltIn's class BuiltIn's run_keyword() method to run the default run-on-failure keyword. The result is that, after instantiating the Selenium2Library class (which is how we run the library outside RF), and running a unittest, on a failure, we get a warning that the "Capture Page Screenshot" keyword can't be found.

This also happens within Robot Framework, when our page object library is imported by a Robot test but S2L is not.

It seems to me my options are:
1. Just instantiate Selenium2Library with the keyword argument run_on_failure=None. But then I don't get to use the "Capture Page Screenshot" on failure.
2. If I want a screenshot on failure, I could define my own keyword, "Capture Page Screenshot", that simply calls capture_page_screenshot on my S2L instance.

OK, option 2 is great, but what if I want to allow some other S2L keyword to be called on failure? Now I've hardcoded "Capture Page Screenshot" into my library. Well, I could modify run_keyword() in my library so that if it gets the run-on-failure keyword it passes it along to the S2L library instead.

BUT now I'm sort of working around the coupling of a S2L (reasonable in itself) to RF, and I still don't have a solution that works outside RF. What if we added a "run_on_failure_method" argument that S2L would check first, then fall back to the keyword if it's specified.

I'd like to fork and open a pull request, but wanted to see if this strikes you as logical first.

**Comment by kahunacohen** [comment]
To clarify why we want to be able to run SE2Lib outside of Robot Framework...

We love Robot Framework and will, in fact, encourage our organization to write Robot tests using our page objects, but it's a much easier sell if we can tell them they can either use Robot or write Python test cases based on unittest...as long as there's one code base for our page objects, not one for Robot tests and one for unittest test cases. 

It works like this...we have a base page object class which uses get_keywords() and run_keyword to return a list of the methods in the class appending the page object's "name' attribute to the end of each method (or the name of the class if no name attribute exists, and map those keyword alias back to their real methods (without the class name appended):

```
from pageobjects.base.PageObject import PageObject

class MyPage(PageObject):
    name = "My Page"

    def open(self):
        ...

    def close(self):
        ...
    def search(self, term):
        ...
```

Results in Roboteese like this:

```
*** Resources***
Library  MyPage

***Testcases***
My Test Case
    Open My Page
    Search My Page  foo
    [Teardown]  Close My Page
```

...and unittest like this:

```
import unittest
from mypage import MyPage
class MyTestCase(unittest.TestCase):
    def my_test(self):
        self.page = MyPage().open()
        self.page.search("foo")

    def tearDown(self):
        self.page.close()
```

Again, this uses the exact same page object code. In a unittest it reads in a typical OO-way. Object, verb. In Robot Framework, since everything's sort of in a global space, it reads very procedural, but you get to reuse the same page objects, and when designing the page objects you get to take advantage of things like inheritence to model a web application's behavior.

**Comment by just-be-dev** [comment]
Thanks for your input!

This is an extremely creative usage of the library, and I'm pretty impressed. I'd be willing to review any PRs you guys put in, but otherwise I can't really spend too much development effort following this path. 

If you're interested just let me know and I'll reopen the issue.
