### ISSUE TITLE
Couple of places with 'Element is no longer attached to the DOM'

### ISSUE THREAD

**Issue by mkorpela** [robotframework/SeleniumLibrary#293]
Hi,

I visited one of my customers last friday and he had an "interesting" app under test. Anyway in some places it seems to update the DOM in a funny way (element is first there with a specific ID and then it is removed and added again).

At least two keywords caused problems:
Wait Until Element Is Visible ==> _element.py:608 _is_visible (element is first fetched and only after it is asked if it is visible)
Select From List By Value ==> _selectelement.py:345 _get_select _list (similar situation)

It might be very hard to fix this everywhere, as it seems that it is very common to first find the element and then check some property from it in a none atomic way (outside of javascirpt). But at least I'm now going to try. Any suggestions how to do this?

**Comment by mkorpela** [comment]
Some related stuff:
http://stackoverflow.com/a/17175986/308189

**Comment by ombre42** [comment]
The JSON wire protocol makes it impossible to do anything with a WebElement without knowing its ID. Getting the ID is a separate call, thus it cannot be atomic.
My solution to this problem was to extend Selenium2Library to add the ability to ignore certain exceptions during the Wait \* keywords by monkeypatching _wait_until. This can only solve the problem when using the Wait keywords. Of course if you are running into stale element exceptions, you probably need to add a Wait \* keyword to sync with the AUT and then you will not have the issue in other keywords. I suppose there may be some instances where an application continuously replaces elements of the DOM on a timer, etc., and I hope **_I**_ never have to test it.
One of the reasons I have never attempted to push this my code upstream was that my issue was due to a bug in the IE driver (since fixed) and I have not seen many people bringing up this issue.
@mkorpela Let me know if you want the code I have and I will email it to you as a workaround.

**Comment by just-be-dev** [comment]
It seems this is a corner case. If it comes back up we'll reopen the issue.
