### ISSUE TITLE
Included test files within source distibution

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#311]
It is my philosophy that the test directory should be part of the distributed Selenium2Library package. That way one can run the test files with their package and don't need to clone or download the src package to get/run these tests.

This might not be everyone's preference so i wanted to introduce the idea here and start a discussion on this idea.

**Comment by HelioGuilherme66** [comment]
I absolutely support that initiative. I can only see advantages on it because:
- It does not add much size to package (around 900KB)
- users can test their installation, setup, or environment
- users can learn a lot by studying the tests

(I am adapting the tests to pass with firefox, google-chrome and phantomjs and possibly with other browsers)

**Comment by ombre42** [comment]
I agree with everything @HelioGuilherme66 said. I think the information in BUILD.rst should go along with the tests if this happens.

**Comment by pekkaklarck** [comment]
I don't have strong opinion either way. With Robot Framework itself we haven't distributed tests because they took so much space in HTML format. Now we have converted everything to plain text format, except for test data for actually testing HTML, they take 4,4MB. It wouldn't be that bad but it's still twice as much as source code. For everyone just using `pip install robotframework` any space increase would be waste.

Another reason we don't include tests is that it is so easy to get them by cloning the repository. With Robot you only really need them when implementing fixes or enhancements, and then you should anyway clone the repo. I can see that with Se2Lib having an easy way to verify that the whole setup (RF, S2L, browsers, browser drivers) works would often be convenient, though.

By the way, we recently renamed Robot tests to use `.robot` extension instead of `.txt`. That's something I can recommend also for Se2Lib and I submitted #312 about it.

**Comment by just-be-dev** [comment]
I have no opinion on this topic. I think we should leave it however it is now and focus on bug fixes and functionality. We can reopen this issue in the future if it really needs to be addressed.
