### ISSUE TITLE
Add section on BUILD.rst about the proper PR workflow.

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#384]
Right now I'm not exactly sure how we're supposed to handle PRs. Do we want to squash the changes to have a simpler git history for master? Whatever the case, it might be useful to add a section in BUILT.rst on the proper procedure for merging PRs.

**Comment by emanlove** [comment]
What do you mean by "Do we want to squash the changes to have a simpler git history for master"? Are you talking about fast fowarding merges?

I agree we should add a note about merging PRs with maybe how to make PRs and what makes up a "good" PR.

**Comment by just-be-dev** [comment]
Some people make it a policy to issue `rebase -i` before accepting a pull request. That squashes all the changes from that branch in to one change and allows you to make a commit message for the whole thing. 

I'm not necessarily saying that we do or don't do that, I just think how we do things should be added. Mostly for clarification for myself too, since I've made a few merges and want to make sure I haven't done anything against the way it's usually done.

**Comment by emanlove** [comment]
I prefer to see changes. Usually there are not a lot and it helps gives a history and thus understanding to what changes were made. how they were made, etc. Basically it gives good insight into one's thinking. My other concern with rebase is that is an advanced git command and can cause issue if not done properly.  I know I have over time done screwy things with git so I prefer to keep it simply.  Now I don't want to avoid the advantages and power of git so I am open to changing my mind. But I do prefer to see history.

This process also includes preferring when merging a branch to use non ff merges so one can actually see the branch instead of merging all the changes into the branch one is merging into.

**Comment by just-be-dev** [comment]
Well, I agree that seeing changes are good, but it all depends on where you want to see the changes. After a PR is completed it needs to be rebased back into master anyway (if any changes have been made.) If we made it a policy to do a rebase -i before merging a PR and list the PR # in the commit comment then while looking through master you could go back and see what changes were made by looking at the PR. 

Like I said though, I'm fine if we don't do that.

**Comment by pekkaklarck** [comment]
First of all, having better contribution guidelines is definitely a good idea. It's better to have them in `CONTRIBUTING.rst` than `BUILD.rst`, though, because GitHub automatically references the former if someone is creating a PR or submitting an issue.

We have robotframework/robotframework#1805 about creating contribution guidelines and plan to actually get them done (or at least started) in RF 2.9a2. My hope is that other projects could reference them from their own guidelines with their own notes about parts that differ. Would you guys be interested to collaborate?

My personal thinking is that squashing commits is a good idea if the commit history is complex with lot of changes, reverts to those changes, etc. If the history is clean with each commit getting individual tasks done, squashing is typically not needed and can even be a bad idea. I'd like the concept of squashing explained somehow so that it's easy to point there if the reviewer considers squashing a good idea. Preferably we should just have a very short intro and links to more information. So far I've used this as a reference:
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by just-be-dev** [comment]
Ahh, you're right about that. Our BUILD file goes beyond the scope of a CONTRIBUTING document though. It actually goes into the steps needed to actually maintain the project. 

We may need to review the BUILD file and move anything that refers to general contributing over to a dedicated CONTRIBUTING file. I also can see the value in working together with the core RF team on this. Many of the sections of the CONTRIBUTING file will probably be the same across our projects. 

My view is, any commits made directly to the project should be in small logical commits. If a bug is being fixed, the whole change should be in one commit. In the case of a PR I prefer them to be squashed. A PR should be focused on doing one thing. If the scope of the PR is too large (i.e. there are multiple features) then project leads should request it be broken up into multiple PRs. 

Of course, I'm pretty flexible and willing to work with you on any of the points until we figure out a good process.

**Comment by pekkaklarck** [comment]
I agree that typically it's better to have commits squashed. I can see two exceptions for this, however:
- The whole PR implements one functionality but that functionality is really big. Having separate steps showing how the final result was accomplished would often be good. This might require squashing some intermediate commits together, though.
- The person submitting the PR isn't that familiar with Git and the PR isn't that messed up. Having few extra commits probably hurts less than asking the contributor to do extra work. This is especially true if a release is near and the PR contains useful functionality we'd really like to get in.

**Comment by just-be-dev** [comment]
I completely agree on the second point. If there's only a handful of commits it's often easier just to merge it than to try to explain how to do it correctly. 

To your first point though, I think this is where a feature branch comes in. Merging multiple squashed PRs against the different logical parts of the overall feature and the merging the whole branch in. That's the workflow I prefer for a large feature. 

Now, if someone really ambitious comes along and writes the really huge feature in one PR I wouldn't go through the trouble of having them break it down. At that point it really just depends on the amount and quality of the commits.

**Comment by aaltat** [comment]
The documentation had been updated in multiple PR and this is done. #877
