### ISSUE TITLE
Discuss transfering S2L to the Robotframework Organization

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#436]
With the formation of the Robotframework foundation and the fact that @rtomac is no longer involved with this project, I think now would be a good time to begin discussing moving the Selenium2Library under the umbrella of the Robotframework organization. 

My proposal is to see if @rtomac is willing to transfer repo ownership to RF and have the RF maintainers create a S2L team in the RF org. 

This is simply a discussion. @emanlove and @ombre42, as fellow maintainers would you be open to this move? @pekkaklarck would the core RF team/members of the RF foundation be open to this?

**Comment by rtomac** [comment]
I'm happy to transfer it, if/when that's desirable.

**Comment by pekkaklarck** [comment]
Moving S2L under `robotframework` organization on GitHub sounds good to me. It's easy to assign different different teams for different projects.

Notice that the role of the new Robot Framework association is still somewhat unclear. Similarly it is unclear what role Nokia wants to have in the future. We've started the GitHub organization while working for them as consultants, and in a sense they thus own the organization. I seriously doubt they want to run it in the future, but I need to discuss this stuff with them. Because Finnish holiday season is just starting and the persons to discuss this are very busy, there's talks probably won't happen in the near future. I don't think moving S2L under the organization needs to wait for that, though.

**Comment by just-be-dev** [comment]
Thanks for the response @rtomac! I'm glad to hear that you're open to the suggestion. 

@pekkaklarck, thanks for the input. Given the state of the ecosystem I'm assuming it would be beneficial to NSN to keep the organization in the hands of the foundation. I would like to know the details of what role the foundation plays and how NSN plans to deal with RF in the future. When you find that out please keep me informed.

**Comment by pekkaklarck** [comment]
Sure, we'll inform the community once we know more. So far we've just founded an association but haven't even yet got papers back from the office that handles them. Due to the holiday season it will take a little time before we have the first meeting and start to really plan for the future.

**Comment by just-be-dev** [comment]
When does the holiday end?

**Comment by pekkaklarck** [comment]
June is generally the holiday month in Finland, but people have holidays in different times and many are on holiday in early August.

I don't think we need to care much about the association when thinking should S2L be moved under robotframework organization here on GitHub, though. If we all agree that's a good idea, we can do it immediately.

**Comment by just-be-dev** [comment]
Okay, sounds good. Let's at least give it a few more days for @emanlove and @ombre42 to pitch in.

**Comment by just-be-dev** [comment]
Unless we hear negative feedback from someone can we go ahead and plan the move for next week sometime? 

It should be a relatively painless process. We'll just need a S2L team set up on the RF side and to have the repo transferred. @pekkaklarck, you could go ahead and set up the team when you have some spare time. I assume it'd be comprised of me, @emanlove, @ombre42, and anyone you want to add to it on the RF side. 

We probably should broadcast the move on google groups just to give other developers a heads up. The documentation should also have any references to the old location moved. 

Am I missing anything?

**Comment by emanlove** [comment]
I'm all for the concept of a larger governing body playing a role.

> Am I missing anything?

First this, ...

> Notice that the role of the new Robot Framework association is still somewhat unclear. Similarly it is
> unclear what role Nokia wants to have in the future. We've started the GitHub organization while working
> for them as consultants, and in a sense they thus own the organization. I seriously doubt they want to run
> it in the future, but I need to discuss this stuff with them.

This conversation needs to take place first before anything is moved to NSN.  The community needs to have a discussion about what role does it want of this, for this "parent" organization. You need to look at, things like, how it will be structured, what will it's role be in guiding or controlling, or influencing or ????? the future development, how will this "parent" organization be maintainable. The community should also ask whether or not NSN fits it's needs and wants for a "parent" organization or some other group. Questions like these need to be discussed by the community, both those active within and those in the larger reaches of the software, first.

Second, contributor agreements, licenses, "ownership", etc. ...

The community needs to work out some of the issues around contributions of code and the various license we have attached to the code. This is part of the first discussion and although I want to say is of minor importance, doing this will truly help the community in the long run.

There are other things I am sure I am missing that needs to be added to this list but there is one last thing to add here. Although I add it last it is the most important, by far.

Community, Community, Community!

The most important part of this software development is the community, community community. It is what makes this type of effort both work now and be sustainable in the future. Without the community, community, community there is little to make this effort succeed in the long run. But with the community, community, community we not only grow but we thrive! So an important step in this process is to grow the community.

**Comment by just-be-dev** [comment]
I wasn't necessarily meaning that the RF association or NSN would have anything to do with S2L. The core developers that maintain this library will stay the same at the very least. It's more for organizational purposes.

On the flip side of that, I do agree with some of the points you made. There's a lot of uncertainty around NSN, the association, and because of that for RF itself.

**Comment by emanlove** [comment]
Let me be clear, I don't have any uncertainty or unease about the future of Robot Framework. It has a healthy, yes small, but significant and passionate core group of developers. Also I see that group growing as more end users become contributors and maintainers of the Robot Framework open source project.

Where I am unsure is what you mean by either the Robot Framework Association or the Robot Framework Foundation. It seems that you mean the [Robot Framework GitHub group](https://github.com/robotframework). Again I have full confidence in this set of core developers and their commitment to the project. I usually associate the terms "association" and "foundation" with a formal organization or at least one that has announced itself as such. And since @pekkaklarck has said they are in the process of forming the association what I am suggesting is that we wait to that process is complete.

And yes I am suggesting putting the Selenium2Library into some sort of "Foundation". There are a lot of good reason for doing so including ensure and assisting the future growth of the project. There are also different models for how a project relates to the Foundation and the Foundation to the project. It can follow along lines of a supporting and advocating organization and (not) one of a controlling body.  (One example I would share with all is the [Plone Foundation](https://plone.org/foundation) which does not control development but supports it. For more information see [their FAQ](https://plone.org/foundation/about/faq)). NSN has role to play here and could be a great partner in this endeavour.

I hear your point about organizational purposes it just I what to know what organization you are taking about first and let the organization be formed first before we move the repository to them, which again I think we should move the repository at least to some "group".

**Comment by just-be-dev** [comment]
Ah, there was actually an announcement on twitter about the formation of an actually robotframework "association." I haven't been very consistent with my terminology (I first referred to it as a foundation). 

Ultimately though, I concede to your judgement. This isn't an issue that needs to be rushed, nor is there really any need to rush it. We can just wait until the dust settles and we figure out what role the RF association will play and how we will fit into that and then maybe we can revisit the topic of moving over to the RF Github organization. 

I'm going to start a separate issue about a CLA as mentioned in your email.

**Comment by emanlove** [comment]
See I missed [that](https://twitter.com/robotframework/status/613474696424722433) [announcement](https://twitter.com/OmeniaOy/status/613370499951931393) on the [twitter feed](https://twitter.com/robotframework). Hearing this I am even more encouraged. From the announcement it looks like there are six companies and @pekkaklarck forming the association. There is no uncertainty here in my mind.

Yes there is the question about NSN relationship but I see nothing that should give anyone doubt about the growth happening in the Robot Framework community. Again GROWTH here is the key word. So despite my arguments for taking certain steps I don't think we, the Selenium2Library, should dial back the momentum. Yes we need to take specific steps and yes we need to discuss important decision points like transfer the code in both organizational or oversights terms but these are just to ensure and support the growth. Let my words not kill the growth that is happening within ourselves and all around us but help to guide us so we can grow more. GROW, GROW GROW!

**Comment by pekkaklarck** [comment]
I agree with everything that has been said here about the importance of community. The community around Robot Framework and the ecosystem the community has built is awesome and in itself much more important than the core framework. Robot Framework core itself hasn't been that much community driven because there has been NSN sponsored team working with it, but I hope to change that in the future. Moving to GitHub has actually already made a huge impact by making collaboration via pull requests so easy.

**Comment by pekkaklarck** [comment]
I'm sorry for not keeping the community better informed about the situation around NSN (or Nokia as they nowadays again want to call themselves...) sponsoring, the recently founded association, and so on. The two main reasons have been lot of the details being open and me just being too busy with work and being dad for two hyperactive small boys. It probably would be best for me to send a mail to robotframework-users about all this, but let me anyway clarify few things here.

The association was founded by Finnish consulting companies that are selling services related to Robot Framework. Their main motivation keeping the framework maintained. It gets a lot harder to recommend an open source solution, and sell services related to it, if the project is dead. The plan is to get also other companies in. There are many big Finnish companies that use Robot Framework extensively in their big projects and seeing the framework stagnant wouldn't be good for them either. We definitely want to be able to accept also companies outside Finland, but we haven't figured out all details yet. One possibility is founding separate associations/foundations in different countries.

It's "association" and not "foundation" because in Finland founding the former is trivial and founding the latter is a big process and requires something like 40000€ initial deposit. Turning the association into a foundation is possible in the future, but we understandably wanted to start small.

Nokia is not a founding member of the association but I hope they will join. They probably have the biggest Robot Framework user base in the world (4000+ users) and the framework staying healthy is thus very important for them. People there generally also understand that they don't have resources to maintain the framework themselves, and they ought to be happy about someone else taking that responsibility. If some high-enough manager thinks otherwise, things might get more complicated, though.

robotframework organization at GitHub is not directly controlled by Nokia at all. It was initiated by me and other guys when working for them, though, so if they would ask for full control, we probably needed to give it to them. I consider that _very_ unlikely, but in that case I'd simply fork the framework and found a new organization. I'm fairly sure that majority of the community would follow as we've seen with Hudson/Jenkins and OpenOffice/LibreOffice. Once the new association gets really started, I hope we could more officially move responsibility of the robotframework organization for it.

Personally I'd be more than happy to welcome S2L the robotframework organization. As I already explained, the risk of a corporate takeover is minimal, and as a backup plan we could easily escape together.

**Comment by aaltat** [comment]
This was done, so closing
