### ISSUE TITLE
robotframework-selenium2library-1.0.0 dependency issue

### ISSUE THREAD

**Issue by apravdin** [robotframework/SeleniumLibrary#45]
robotframework-selenium2library-1.0.0 is supported by pip, while robotframework 2.6.3 is a dependency, but is not supported by pip
This is problematic

**Comment by j1z0** [comment]
Your correct. Let me work on updating the installers. 

Cheers,
Jeremy

**Comment by jussimalinen** [comment]
I changed the acceptance test status checker and doc generation to work with robot 2.7.0. Both will print an error if user tries to run them with robot < 2.7.

I have however changed the setup to use robot >=2.6.0 as dependency, because most users wont run the acceptance tests or generate the docs.

After this we should be able to support pip finally.

See the pull request.
