### ISSUE TITLE
run_on_failure handling is confusing to new users

### ISSUE THREAD

**Issue by dragonfyre13** [robotframework/SeleniumLibrary#455]
Discussed with zephraph on slack, this is a bit of a placeholder issue for run_on_failure duplication of RF's test teardown functionality, in addition to difficulties it causes with new users to robotframework and/or selenium2library.

Test teardown appears to already have the same functionality created by run_on_failure (at least at the global/import level) and pre-existing builtin keywords within robotframework duplicate the rest. Users new to robotframework anticipate that this run_on_failure keyword will be executed whenever a keyword fails, regardless of the keyword's origin in selenium2library or not. This creates significant confusion at times, and does not appear to have a well defined purpose separate from the robot framework standard functionality it duplicates.

**Comment by just-be-dev** [comment]
@pekkaklarck what do you think about this? Is run_on_failure really unnecessary? 

@emanlove, do you know any of the motivation for adding it to begin with?

**Comment by emanlove** [comment]
This code goes back a long way and listening to @dragonfyre13 comments above (as it looks like one has to register to see discussion on slack) I would venture to say it was used for browser screenshots _at the point of failure_. Reviewing the Robot Framework built-in keywords for failure they all pretty much occur at test teardown and if one has nested test suites I would think the test execution and teardown execution could get fairly complicated. So my strong suspicion is that this was designed to take a screenshot when a selenium action failed so one could see the state of the web page at the point of the failure.

The keyword documentation for Run On Failure tries to higlhight that this keywords runs "if Selenium2Library keyword fails." Maybe we want to emphasis that and say "**_Note: This keywords only runs when a Selenium2Library keyword fails**_" (which sounds a lot like what it already says. Maybe someone else has better wording for this...)

**Comment by just-be-dev** [comment]
On a slightly related note, @emanlove you should join our slack channel! (I've updated the readme of this project with a badge that links to the signup page). 

I agree with what you've said too, but shouldn't the first step after a keyword has failed be the teardown? It would explicitly require that the test author place whatever action they wanted to occur at the end of every test that they wanted it to occur in which would undoubtedly add maintenance overhead. 

Does it make sense to have this functionality where it _only_ occurs when an S2L keyword fails? Is this something that's a candidate for its own library which uses something like a library listener to run specific keywords after failure?

I'm just trying to start some dialog. This feature isn't one that I really use myself at all, so I'm not a good judge of how or when it should be used.

**Comment by emanlove** [comment]
That is one of the problem's of removing this, maintenance overhead. You have to put this in a lot of places on large suites and what is you failed to do so in some or a few. To a certain degree you do want it to fail only with Selenium2Library keywords. Again I've taken some selenium action and and it fails. What is the current state of my webpage?

Thinking this morning we could add more documentation to the introduction section too. I would be interested more in the confusion @dragonfyre13 you have heard with the keyword. Has anyone else been confused?

**Comment by aaltat** [comment]
I actually love run on failure functionality. When you have lot of libraries that interact with SUT, it comes almost impossible to keep track which keyword did fail and how to gather required info in the suite/test/keyword tear down. I am in the opposite view, all libraries should have run on failure functionality, then it comes easy to run specific keywords that garb correct information with that library.

I recall that now and then, there is a question about run on failure in the user group, but I don't think that it justifyes to remove the functionality.

**Comment by pekkaklarck** [comment]
This functionality existed already in the original SeleniumLibrary. @yanne already [enumerated on Slack](https://robotframework.slack.com/archives/selenium2library/p1437538306000076) why it was added. I'm not sure is that discussion visible for everyone so I quote him:
1. We wanted to have a screenshot whenever a Selenium test failed because the test setup we had was really slow.
2. Taking screenshots with original selenium was really slow (with IE, it was ~10s a pop), so just having Take Screenshot in Test Teardown was not an option
3. RF core did not have keywords like `Run Keyword If Test Failed` etc.

I don't know how slow taking screenshots is nowadays, but at least all other important reasons why it was added have been resolved otherwise. I still wouldn't remove the functionality, mainly because it is still useful and also because it would be backwards incompatible change. Things that could be considered:
1. Enhance documentation. This is probably a good idea anyway.
2. Disable the functionality by default. It would be easy to configure the library when importing it.
3. Change it the functionality so that you only can take screenshot, not run any S2L keyword, if a keyword fails. Something like `screenshot_on_failure=True` would be easier to document and use than the current approach. It doubt anyone actually uses any other keyword than `Take Screenshot` so this shouldn't cause much backwards compatibility problems.

**Comment by emanlove** [comment]
You apparently need to be signed in (and thus a registered user) to see the conversation in slack. I think we should without a doubt do recommendation #1 including adding information into the main introduction section. Although implementing recommendation #2 might seem like a good idea I think we would be breaking too many scripts that take this action for granted and expect it to happen by default. Also I am not sure doing this would resolve the issues @dragonfyre13 has brought up. Recommendation #3 to me is a big no no in that we don't know how people use it so it would cause backward compatibility issue.

To me this is an documentation and education issue.

**Comment by pekkaklarck** [comment]
- Taking a screenshot or running some other keyword is a really nice feature.
- Related docs have been updated heavily as part of #924.
- Having a way in Robot itself to easily run an action *only* when there's a failure would be nice, but discussion about such functionality belongs to Robot's tracker, not here.
- If such functionality would be added to Robot, then we could consider what to do with SL's run-on-failure functionality.
