### ISSUE TITLE
1.7.2 is not compatible with robotframework 2.8.4 anymore.

### ISSUE THREAD

**Issue by gotcha** [robotframework/SeleniumLibrary#476]
because 2.8.4 does not have `RobotNotRunningError` which is added in 2.8.5

**Comment by gotcha** [comment]
When this type of incompatibility is introduced, it should be stated in `setup.py`

**Comment by just-be-dev** [comment]
That dependency will be resolved in the next release. It wasn't intentional.

**Comment by gotcha** [comment]
I know you know. I filed the issue in order to help other people understand their issue.

**Comment by just-be-dev** [comment]
It's fixed in master. I just don't have a windows machine with me to do a new build.

**Comment by pekkaklarck** [comment]
If you haven't been able to upgrade to newer RF versions due to DateTime library introduced in RF 2.8.5 that conflicts with Zope2 DateTime module, you should be now finally be able to upgrade to RF 2.9. It was just released and it contains a fix to this bug:
https://github.com/robotframework/robotframework/issues/1737

**Comment by just-be-dev** [comment]
1.7.3 should be released on Saturday and will resolve this issue.

**Comment by gotcha** [comment]
@pekkaklarck Yup, using RF 2.9 release is compatible again with Plone/Zope2. Then I can use 1.7.2 without issue.

**Comment by pekkaklarck** [comment]
It's great that Plone/Zope2 people can finally upgrade their RF installations! There have been lot of enhancement since 2.8.4.

**Comment by just-be-dev** [comment]
This is fixed for 1.7.3.
