### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by davidjb** [robotframework/SeleniumLibrary#479]
Are there any plans for this library to look at supporting Python 3?  The biggest blocker appears to be the fact that robotframework itself isn't yet Python 3.x compatible (though there is a Py3 fork available on PyPI; https://github.com/robotframework/robotframework/issues/1506).

For this package, though, it looks as though there'd need to some changes around the packaging (ez_setup.py), and minor changes to the syntax (exception handling, printing, relative imports), and the big one -- having a conditional statement in `setup.py` to choose between `robotframework` and `robotframework-python3`; all other dependencies appear Python 3 compatible.  With only those changes required, supporting 2.7 and 3.x seems reasonably straightforward, though I'm not intimately familiar with the code base.

Thoughts?

**Comment by emanlove** [comment]
Feel free to submit a pull request. My only concern is that we maintain support for Python 2.7 (and possibly 2.6).

**Comment by pekkaklarck** [comment]
Python 3 support would be great. I agree with @emanlove that Python 2.7 must be supported also in the future. Python 2.6 is not too much extra work on top of that (as long as dependencies support it) but because it is [officially retired](https://www.python.org/download/releases/2.6.9/) I'm not sure is that worth any effort. We haven't yet decided are we going to support it with Robot Framework itself in RF 3.0 anymore.

Another decision to make is what is minimum Python 3 version to support. I'm thinking about Python 3.3 because it supports `u'foo'` syntax (PEP-414) that makes it easier to write Python 2 compatible code.

**Comment by aaltat** [comment]
I guess we should somehow discover the dependencies which each external RF library requires. For Selenium2Library, we depend on decorator, selenium, docutils and RF itself. 

The only external library that does not clearly say it supported 3.X version is docutils, but it claims to be Python 3 compatible. Decorator has best support for Python version, from 2.6 to all the way to 3.5. Selenium also nice support Python 2.6, 2.7, 3.2 and 3.3. 

But I guess that the bottom line is that change for Python 3.X is coming and the RF core them should lead the change and the rest of us will/should follow. So choose wisely. But perhaps this would be place for a wider audience and should be discussed with the whole user group people. 

Personally I have not coded with Python 3.X or read anything that would allow me to form an opinion to any direction from Python 3.X. 

But @zephraph, I think that support for Python 3 requires a major version change, should we change the label to 2.0?

**Comment by pekkaklarck** [comment]
In general I think its each projects own decision to select what Python versions they support. The Python world is moving slowly but steadyly towards Python 3 so supporting it is a good idea, but nobody can mandate it. For projects that are used only with Robot Framework supporting Python versions not supported by RF itself doesn't obviously make much sense (unless there is a need to support older RF versions that support older Python versions).

For Robot Framework core I explained my position already in my previous comment. Here are the main points:
- RF 3.0 will support Python 3. It will hopefully be releases still this year.
- There is no plan to drop Python/Jython/IronPython 2.7 support in the foreseeable future.
- Python 2.6 support will probably be dropped at some point, possibly already in RF 3.0.
- Python 3.0-3.2 will not be supported because they do not support `u'foo'` syntax and they have very limited user base.

**Comment by just-be-dev** [comment]
I moved this over to the 2.0 milestone as @aaltat suggested. Hopefully we can synchronize this with RF's 3.0 release. 

As far as what we support, I'm going to follow your lead @pekkaklarck. I think if it's not too much trouble then we should probably try to maintain support for 2.6 though.

**Comment by aaltat** [comment]
To take more steps towards Python 3 direction, should we first enhance the CI to build with Python 3? When that is done, it would be easier to support and track the progress of Python 3 comparability.

**Comment by wingyplus** [comment]
Hi, I interesting this issue. What can I help to make this to done?

**Comment by aaltat** [comment]
The easiest way is to take part of the code (or all of the code) and make it work with Python 2.7 and Python 3.3. When you are happy with the results, send a pull request with GitHub. The small parts are liked more because it makes the review process easier. Also cleaning the code, to make it more readable is a plus.

**Comment by wingyplus** [comment]
Thanks for information. I will python3 on travis first, fix it and send pr.

**Comment by HelioGuilherme66** [comment]
That is already fixed in [myfork release](https://github.com/HelioGuilherme66/robotframework-selenium2library/releases/tag/v1.8.0b3), PR #562.

**Comment by aaltat** [comment]
The CI stuff is done by @drobota in the CI branch. He has already done some work for it, which all is not in the CI branch. Therefore you could contact him before doing anything in twice.

**Comment by wingyplus** [comment]
@HelioGuilherme66  Great! 👍  I will test it. 

@drobota Can you share progress on ci branch. May I help you?

**Comment by aaltat** [comment]
I think status is in #621

**Comment by aaltat** [comment]
We have spilt this to multiple different issues and therefore closing this one. The Python 3 support should happen in release 2.0 and it should be next release

**Comment by Netardent** [comment]
In Python version 3.5.2  and Robot Framework version 3.0.1....i have tried to install robotframework-selenium2library, but have problem on installation:

Collecting robotframework-selenium2library
  Downloading robotframework-selenium2library-1.8.0.tar.gz (118kB)
    100% |################################| 122kB 126kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "...\pip-build-6g6zkqc5\robotfra
mework-selenium2library\setup.py", line 7, in <module>
        from ez_setup import use_setuptools
      File "...\pip-build-6g6zkqc5\robotfra
mework-selenium2library\src\ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in ...\pip-build-6g6zkqc5\robotframework-selenium2library\

**Comment by aaltat** [comment]
Selenium2Library is not yet compatible with Python 3. The next release, version 2.0, from Selenium2Library will bring support for Python 3. There is a fork from the project, which provides currently support for Python 3. If I recall correctly it's this one: https://github.com/HelioGuilherme66/robotframework-selenium2library

**Comment by arvk26** [comment]
When selenium2Library 2.0 is going to release? Any approx date?

**Comment by aaltat** [comment]
No, not really. It's done without any company support and therefore progress is slow. Pekka is helping a lot, but he also does it in his own time.

We are also cleaning the code base and making changes to the architecture. This hopefully in the future allows more frequent releases and easier maintenance.

**Comment by arvk26** [comment]
I understand. Thanks

**Comment by pekkaklarck** [comment]
Yeah, cannot make promises because we have our own jobs, families, etc.. But I _hope_ we get S2L 2.0 w/ Py3 support out in February, latest in March.

**Comment by Tset-Noitamotua** [comment]
@aaltat you said
> We have spilt this to multiple different issues and therefore closing this one. The Python 3 support should happen in release 2.0 and it should be next release

Can you add links please. I would like to contribute and trying to figure out where to start.

**Comment by aaltat** [comment]
There might be something missing but most of the needed improvements should be in issue tracker 2.0 milestone.

**Comment by Tset-Noitamotua** [comment]
ok found it: [issue tracker 2.0 milestone](https://github.com/robotframework/Selenium2Library/milestone/17)

**Comment by vinaybajaj** [comment]
Hi Team,

Today, i was trying to install Selenium2Library for python 3.X. I go through so many blog and everywhere it is mentioned that it is not compatible with Python3.x.  Is there any further updates on new updates of selenium2library? 

Thanks in advance!

**Comment by aaltat** [comment]
The latest news are posted in the user group: https://groups.google.com/forum/m/#!topic/robotframework-users/McYQ81MakM8
