### ISSUE TITLE
Press Key keyword no longer works with strings

### ISSUE THREAD

**Issue by deaglejv** [robotframework/SeleniumLibrary#489]
Following example results in error (actual variable names replaced):

Press Key    ${EnterSomething}    test-something

This will error with message: ValueError: Unknown key named 'test-something'

**Comment by just-be-dev** [comment]
@deaglejv, the update we made to the `Press Key` keyword in 1.7.3 had some unintended consequences. For now, I recommend rolling back to 1.7.2 if it's time critical, but we're definitely working hard to get a patched release out. 

The issue isn't that the `-` doesn't work, but rather that `Press Key` no longer accepts a string of characters to be pressed. This is mostly my fault for missing that detail in the code review. 

As I said, we'll have a patch out ASAP. Sorry for any inconvenience.

**Comment by just-be-dev** [comment]
There's a few solutions that I can think of off the top of my head. 
- Check to see if a string with length > 1 matches a special key. If so, use the special key. Otherwise just send the string.

``` robotframework
Press Key   text_field    q          # The letter 'q'
Press Key   nav_console   ARROW_UP   # Named ARROW_UP key
Press Key   login_button  \\\\13     # ASCII code for Enter key
Press Key   custom_input   mystring  # String to be entered
```
- Make the special keys all some sort of variable that's built into the global context. 

``` robotframework
Press Key   nav_console   ${SELENIUM_KEYS.ARROW_UP}   #Arrow up key
```
- Add a new keyword that just performs `send_keys`

``` robotframework
Send Keys   custom_input   mystring   # String to be entered
```
- Add a optional argument that can take a string

``` robotframework
Press Key   custom_input   text=mystring   # String to be entered
```

I'm up for hearing any other suggestions as well. 

/cc @pekkaklarck, @emanlove, @HelioGuilherme66, @aaltat

**Comment by pekkaklarck** [comment]
I think I'd just revert the change done in earlier version. This is so severe regression that a fix is needed ASAP and I doubt we can come up with a good design that quick.

**Comment by pekkaklarck** [comment]
Possible new design should be backwards compatible with 1.7.1 and earlier. Bigger changes require deprecation in 1.8 first and may not be a good idea even then.

**Comment by aaltat** [comment]
I agree with @pekkaklarck. Let's revert back the changes. It gives us time to consider what we need to do. Also I fear that jumping to new code, will lead to more problems than it will solve.

If we decide to make the changes, let's review the current test and make corrective actions to prevent this from happening. 

Then deside what the keyword should do, how to change it and when to change it. Write test to cover the new functionality. Write code, refactor and polish. Send pull request, do review... Like normal iterative process. When things are do with enough thinking (slow enough), one then achieves better results with great speeds.

**Comment by just-be-dev** [comment]
I'll get to work on this asap.

**Comment by emanlove** [comment]
Agree with @pekkaklarck and @aaltat

**Comment by aaltat** [comment]
When reading the history, it seems that we need to do something with these commits:
cdb336009852492a03a512964d54fbded2b621a8-Hélio Guilherme-Merge pull request #3 from zephraph/press_key_#275
46c052e1044f9aee72373a7561f69ca37f10c50c-zephraph-Fixes suggested by pekka
d1f592e5fcad64acccff7aa533aafd2ef3ed1b55-Helio Guilherme-Deprecates the use of backslash escaping for ASCII and NAMEioGuilherme66-Add named keys to Press Key.

Also commit:
353b2dfb3eadb2f43ae92b8a6fc9ec388dd64a49-zephraph-Fix documentation, small bugs                             

should be looked more closely, because it because it touches _element.py

@zephraph how it does look by your eyes? 

Or one way is to checkout tag 1.7.2 and then cherry pick commit which are only needed, but looking the history, that is quite long list.

**Comment by just-be-dev** [comment]
You know, looking back through the documentation, this wasn't actually a documented feature. 

Here's the description put in 1.7.2:

> Simulates user pressing key on element identified by `locator`.
>         `key` is either a single character, or a numerical ASCII code of the key
>         lead by '\\'.

**Comment by pekkaklarck** [comment]
Yes, this was an undocumented feature. It was also untested which was the main reason we didn't notice it when making changes. I consider breaking the feature still a bug because the original behavior was reasonable and we cannot expect users to read docs in such detail. It would probably be a good idea to update docs and add at least one test for it.

**Comment by just-be-dev** [comment]
Fixed in 1.7.4. 

I'm going to work on a strategy for mitigating the risk of this happening again in the future.

**Comment by Tset-Noitamotua** [comment]
Named Keys (e.g. ENTER) are not working with `Press Key` in recent version 1.7.4, too?

**Comment by aaltat** [comment]
And that is correct behaviour with that release. The issue #498 contains more information about the improvements intended to support new "Press Keys" keyword.

**Comment by Tset-Noitamotua** [comment]
Hope named keys will come back soon in the future. They are so much more intuitive to use and ways better to read.

**Comment by yao450860487** [comment]
what's the format when use keyword "press key" with "ctrl+t" ? I met no need locator,but locator is a mandatory parameter

**Comment by yao450860487** [comment]
what's the format when use keyword "press key" with "ctrl+t" ? I met no need locator,but locator is a mandatory parameter
