### ISSUE TITLE
New `Press Keys` keyword with clean support for special keys

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#498]
The current `Press Key` keyword has a severe limitation that pressing special keys like tab requires using escaped ASCII codes like `\\09` (double escaping needed because `\` itself is an escape character in Robot's data) and not all special keys (e.g. arrows) are supported. 

Issue #275 proposed adding support for WebDriver's [special keys](http://selenium.googlecode.com/git/docs/api/py/webdriver/selenium.webdriver.common.keys.html) like `ARROR_UP` to `Press Key` and it was implemented by PR #474 in version 1.7.3. Unfortunately this change broke undocumented (and tested) feature in`Press Key` to allow pressing multiple keys (#489). Such a backwards incompatible change was not considered a good idea, especially in a minor release, and changes were reverted in 1.7.4.

The general consensus in the comments of the aforementioned issues and pull requests  tracker and on the Slack channel seems to be the following:
- Adding support for named special keys is an important enhancement.
- It is a good idea to support pressing multiple keys (and `Press Key` that actually supports it is badly named).
- `Press Key` behavior should not be changed in backwards incompatible manner.

As a result the consensus seems to be that we want to add new `Press Keys` keyword that supports named keys. There is no consensus about lower level design decisions, though, but we can discuss about them in the comments of this issue.

**Comment by Tset-Noitamotua** [comment]
@pekkaklarck 
Referring to your comment in #496:

> I think it would make sense to accept *keys, I'd rather have use just `'+'` and not `' + '` as a separator ...

***keys would result in a syntax like this:**
`Press Keys | CONTROL | ALT | DELETE`
`Press Keys | CONTROL | A`
`Press Keys | CONTROL | C`
`Press Keys | CONTROL | + | + | +`  ... 

**`'+'` would result in a syntax like this:**
`Press Keys | CONTROL+ALT+DELETE`
`Press Keys | CONTROL+A`
`Press Keys | CONTROL+C`
`Press Keys | CONTROL++++`  (first problem case) 

**There as `' + '` leads to a clean and easy syntax (in my opinion):**
`Press Keys | CONTROL + ALT + DELETE`
`Press Keys | CONTROL + A`
`Press Keys | CONTROL + C`
`Press Keys | CONTROL + +++`  ...

**Comment by pekkaklarck** [comment]
@Tset-Noitamotua: I don't mean exactly that. I would allow `CONTROL+X` (and would also add alias `CTRL+X`) as a single argument. Supporting `*keys` would make it possible to use `| X+ | CTRL+X |` (press keys `X`, `+` and `CTRL+X`) without it being ambiguous like `| X+CTRL+X |`.

I will explain my reasoning with examples later. Getting RF 2.9.1 too a bit more time than I anticipated and I don't have free time until later tonight.

**Comment by aaltat** [comment]
I think we should consider the use case of the keyword. What are needs and user scenarios for the keyword. 

The below is trying to demonstrate how the keyword is used, do not look the syntax.  
Would you like to use it like this:

```
| Press Keys | //xpath1 | CTRL+A |
| Press Keys | //xpath1 | CTRL+C |
| Press Keys | //xpath2 | CTRL+V | 
```

Or wold this be good:

```
| Press Keys | //xpath1 | CTRL+A | CTRL+C |
| Press Keys | //xpath2 | CTRL+V | 
```

What I am trying to ask, is there good enough usage case, to justify to make the keyword work that multiple key combinations, to a same element, can be passed as arguments to same keyword (the later example). Or would it be more easier to read/write/maintain, from Robot Framework data point of view, one key combination for with single keyword (the former example). 

For me, it looks quite tempting to do multiple key combination in a single pass and I can think many usage cases for it. But I also know the (some) nature of the web world. There are plenty of timing issues, which can and will happen if the key combination are given too fast. And if careful polling is not, sometimes even sleep, performed between key combinations. Because of the timing issues, I do not see point of allowing multiple key combinations within a single keyword. And therefore I vote for single combination in one keyword.

What do others think?

**Comment by Tset-Noitamotua** [comment]
:+1:  for single combination in one keyword

**Comment by Tset-Noitamotua** [comment]
... but I'm still excited about Pekka's examples for `| X+ | CTRL+X |` :)

**Comment by pekkaklarck** [comment]
Here's finally my proposal.
1. Normal keys should be supported directly. Examples: `f` (one key), `FOO` (three keys).
2. Escaped ASCII codes (e.g. `\\09`) supported by `Press Key` should not be supported. They are hard to read, hard to use (double escaping), add complexity to code, and simply have no benefits over named keys.
3. WebDriver's [named special keys](http://selenium.googlecode.com/git/docs/api/py/webdriver/selenium.webdriver.common.keys.html) (e.g. `CONTROL`, `END`) should be supported. They should, however, be supported **only** when used alone or separated with `+` that is used as a modifier separator (more about that later). This avoids named keys accidentally matching something like `BEND` or `AALTO` and also simplifies implementation because there is no need to scan the whole string for named keys.
4. Common aliases should be added to named keys when appropriate. For example, `CTRL` should be an alias for `CONTROL`.
5. It should be possible to pass multiple keys also as separate arguments. This makes it possible to use `| E | N | D |` (`|` used as argument separator) if you want to press those three keys and not single key `END`.
6. The separator between modifiers and keys should be `+` with no spaces around. Multiple modifiers should be supported and they should affect all remaining characters in that argument but not subsequent arguments. Examples:
   
   ```
   | CTRL+C |           # Hold `CTRL` and press `C`.
   | CTRL+ALT+DEL |     # Hold `CTRL` and `ALT` and press `DEL` key.
   | CTRL+XC |          # Hold `CTRL` while pressing keys `X` and `C`.
   | CTRL+X | CTRL+C |  # Same as the above.
   | CTRL+X | C |       # Hold  `CTRL` while pressing `X`, then release `CTRL` and press `C`.
   ```

**Comment by Tset-Noitamotua** [comment]
@pekkaklarck 
I agree mostly with 1. - 4. 

But one single key should not be supported: `Press Keys | //xpath | C` does not make sense.
Multiple single keys without modifiers should not be supported,  too. In that case `Press Key` or `Input Text` should be used - see example below.

> '5. It should be possible to pass multiple keys also as separate arguments. This makes it possible to use | E | N | D | (| used as argument separator) if you want to press those three keys and not single key END.'

I would prefer 
`Press Key | //xpath | E`
`Press Key | //xpath | N`
`Press Key | //xpath | D`

or simply 

`Input text | //xpath | END`

to realise that. 

Or do you think of pressing and holding that keys down simultaniously? Then may be special keywords like `Hold Key(s)` and `Release Key` should be introduced? In Selenim this is already implemented so it should not be that hard to bring it to S2L.

> '6. ...
> CTRL+X | C |         # Hold  `CTRL` while pressing `X`, then release `CTRL` and press `C`.'

For me it is more obvious what the next two keywords do instead of the one above:
`Press Keys | //xpath | CTRL+C`
`Press Key    | //xpath | C`

**Comment by pekkaklarck** [comment]
Thanks for comments @Tset-Noitamotua. Could you please clarify these points:
- Why wouldn't single key like `C` alone make sense? Notice that part of my plan is deprecating and later removing `Press Key` altogether. Needing to use a different keyword depending do I want to press `A` or `AB` would be really weird. It would especially annoying if I got a variable `${chars}` somewhere and needed to check its length to know what keyword to call.
- Why are you against `*keys`? I would prefer `| E | N | D |` over needing to use the same keyword three times and it would be especially handy if I had variable `@{chars}`. Only negative point I see with it is that it isn't possible to add new arguments to the keyword later, but I don't see any reason additional arguments would be needed.

**Comment by just-be-dev** [comment]
In the long term, I'd like to deprecate the ability for `Press Key` to take in a string. That was an undocumented feature and I feel like it really doesn't function how one would expect `Press Key` to function. 

As for `Press Keys` I like having each key being an argument with `+` as a separator.

``` robotframework
Press Keys | //xpath | CTRL+C | CTRL+V
```

I think we can split the key string on the separator and trim the keys so you can have spaces or not. That can be left up to preference. I also think being able to optionally set the separator would be a bonus. 

``` robotframework
Press Keys | //xpath | sep=- | CTRL-+ |
```

That's not a necessary feature, but it could be useful. It's a little ugly though, I'll admit. 

Finally, typing multiple characters should be handled by a new keyword call `Send Keys`. This is the method selenium uses to do keypresses in general and I feel like it would be natural for new users. 

``` robotframework
Send Keys | //xpath | Hello World
```

**Comment by pekkaklarck** [comment]
@zephraph:
- I don't see why `Press Key` supporting multiple keys should be deprecated. I would rather deprecate the whole keyword if we can have one that supports all use cases in clean way.
- You cannot simply split from `+` because you may have literal `+` there too (e.g. `CTRL++`). You need to split from the first `+` and check is the left side a valid modifier. If it is, split the reminder from the first `+` and  repeat.
- I see no additional benefits in supporting more than one separator. The above algorithm should handle all special cases without a need for escaping or having alternative separators. Having just one separator is easier to use, understand and document. I don't really care is the separator `+`, `-`, `^`, or something else, though.
- I'm -1 for adding separate `Send Keys` and `Press Keys`. I don't really care is the new keyword named `Send Keys` or `Press Keys`, though.
- I'm -1 for optional spaces around the separator. `CTRL+${SPACE}` is a pretty common shortcut and needing to escape it somehow would be annoying. Not allowing spaces would also make the implementation easier.

**Comment by just-be-dev** [comment]
I see your point about the separator. That's valid, we can just go with that. 

Currently, people are using `Press Key` to send a string to custom inputs. It mimics typing. They can't use `Input Text` because that keyword tries to clear out the input box (it assumes that it's being used on an `input` element). We need to address this functionality, but I don't want to stuff it into `Press Keys`.

**Comment by pekkaklarck** [comment]
Could you clarify what would be the difference between `Send Keys` and `Press Keys`? They sound _very_ similar.

**Comment by pekkaklarck** [comment]
Regardless what new keyword(s) is implemented, adding `clear=True` to `Input Text` would probably be a good idea.

**Comment by just-be-dev** [comment]
`Send Keys` does the same thing as `Input Text` but without the clear. So maybe just adding the clear would be the best route to take.

**Comment by HelioGuilherme66** [comment]
Updated Wiki page with features definition from this issue (and more of my own).
[Features-Under-Development](https://github.com/rtomac/robotframework-selenium2library/wiki/Features-Under-Development)

**Comment by HelioGuilherme66** [comment]
The proposed acceptance tests for `Press Keys` are at [zkeyboard.robot](https://github.com/HelioGuilherme66/robotframework-selenium2library/blob/new_press_keys/test/acceptance/keywords/zkeyboard.robot). You can checkout my branch [new_press_keys](https://github.com/HelioGuilherme66/robotframework-selenium2library/tree/new_press_keys) ~~(please ignore textfields.robot it was prepared for `Press Key` accepting named keys)~~.

**Comment by aaltat** [comment]
@HelioGuilherme66 instead of the wiki, would the [gist](https://gist.github.com/) be better place? 

But are we targeting to combine the keywords? That sounds good for me, but we need to create a plan for it and let others also know the plan. But could we try to agree how the new keyword should work.

I agree with @pekkaklarck point that supporting multiple key combinations is useful, like: 
`| CTRL+X | C |`. I only fear that it will lead to problems on timing side but I think we can revisit the problem if an timing issue occurs. Also allowing multiple arguments solves nicely confusion with [webdriver.common.keys](http://selenium.googlecode.com/git/docs/api/py/webdriver/selenium.webdriver.common.keys.html) problem, without need of escaping. Example which one user means if he wants to send `END`

For most of the part I am happy and if all others are too, we could write some test to cover the happy path and see where it leads us.

**Comment by Tset-Noitamotua** [comment]
> Why wouldn't single key like C alone make sense? Notice that part of my plan is deprecating and later removing Press Key altogether. Needing to use a different keyword depending do I want to press `A` or `AB` would be really weird.

I think pressing a single key with a keyword that is called 'Press Keys' doesn't fit realy good just because the one ist singular and the other plural. I´m against removing 'Press Key' because I like the clear distinction between the two. I would use 'Press Key' for pressing one and only one key in the sense 'press and release'. And 'Press Keys' should be dedicaded to pressing key combinations which are used for common keyboard shortcuts like 'CTRL-A', 'CTRL-C' and so on.

> It would especially annoying if I got a variable ${chars} somewhere and needed to check its length to know what keyword to call.

I would not use 'Press Keys' to do `AB` or `END` because that is the job of 'Input Text' keyword. (again: 'Press Keys' should be dedicaded to pressing key combinations which are used for common keyboard shortcuts.)

> Why are you against `*keys`? I would prefer | E | N | D | over needing to use the same keyword three times and it would be especially handy if I had variable @{chars}. Only negative point I see with it is that it isn't possible to add new arguments to the keyword later, but I don't see any reason additional arguments would be needed.

Of corse there may be the use case where one want to press a sequence of single keys but I think this will be very rarely the case so that it will hurt not that much if you have to use the same keyword three times.  That's why I think 'Press Keys' should be designed mainly for the usage of commonly used keyboard shortcuts.

**Comment by Tset-Noitamotua** [comment]
In case you decide to allow pressing more than one single key and multiple key combinations than may be a delay option will make sense. e.g.

`Press Keys | CTRL+A | CTRL+C | delay=3` where delay is time in seconds.

**Comment by HelioGuilherme66** [comment]
Added `delay=` to Press Keys definition at [Wiki](https://github.com/rtomac/robotframework-selenium2library/wiki/Features-Under-Development#press-keys)

**Comment by Cronax42** [comment]
To make a case for allowing single key presses, suppose a UI that takes single key presses as shortcut keys, for instance in a menu. In such a case it seems counter-intuitive to use `Input Text` as you're not actually inputting text into a field.

**Comment by aaltat** [comment]
Removed 1.8 scope because of lack of time

**Comment by vineel258** [comment]
Any update on this issue?

**Comment by edimistra** [comment]
Will this be added to Selenium2Library anytime soon?

**Comment by aaltat** [comment]
No-one has seen this important enough to make a PR. But before the PR we should agree on the design and that is still open. Do you have input on the matter?

**Comment by TedMusk** [comment]
Will this be added to Selenium2Library anytime soon?

**Comment by aaltat** [comment]
No-one has seen this important enough to make a PR. But before the PR we should agree on the design and that is still open. Do you have input on the matter?

**Comment by Tset-Noitamotua** [comment]
oh, there was a PR ... but it was not good enough ;-)

Tatu Aalto <notifications@github.com> schrieb am Mo., 6. März 2017 um
11:07 Uhr:

**Comment by MarkJB** [comment]
I've recently had the need to test a numeric input control. The increment/decrement controls aren't rendered in some browsers and (ignoring the reasons for that) I needed to test the number formatting when using the ARROW_UP and ARROW_DOWN keys.

My two pennies worth: I'm all for a single keyword that supports special keys, but would it be easier to implement a 'Press Special Key(s)' (or 'Press Control Key(s)) keyword that supports only the [named webdriver keys](https://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.keys.html)?

**Comment by aaltat** [comment]
Would you have time to write some use cases how you would like the keyword to work?

**Comment by MarkJB** [comment]
My current need is only for a single named key, i.e.

`Press [Special] Key(s) | //xpath | ARROW_UP`
`Press [Special] Key(s) | //xpath | ARROW_DOWN`
`Press [Special] Key(s) | //xpath | TAB`

Though I guess the original proposal is more appropriate when considering modifier keys and non named keys...

`Press [Special] Key(s) | //xpath | SHIFT | TAB` or `Press [Special] Key(s) | //xpath | SHIFT+TAB`
`Press [Special] Key(s) | //xpath | CTRL | c`  or `Press [Special] Key(s) | //xpath | CTRL+c`

**Comment by petsan** [comment]
How would i send the actual ESCAPE key? TIA

**Comment by frankvanderkuur** [comment]
Hi all,  I'm currently working on a project where I need the ARROW key's to work. That made me stumble over this issue.  Just my two cents, but what would be the problem with designating a prefix for these specials keys? Something like: Keys.ARROW_DOWN or Keys.ENTER? 

It makes it absolutely clear you are using the special keys mapping and it is very similar to many other solutions in other software. I wouldn’t create a new keyword for it if there is no absolute need for it, since we are still sending 1 key. 

For now I’ve fixed it in exactly this way in my local version, but since I have to deploy it for a few hundred employees here, I would rather have it fixed is the framework itself :-)

**Comment by ShAnsari** [comment]
When will this be add to the Selenium2Library?
I am trying to execute: 
`Press Key  | CONTROL  +  SHIFT  +  i`

Is there any way to do this?

**Comment by aaltat** [comment]
No one has seen this important enough to drive for the design. Currently we are focused to get the next release out with Python 3 support and this is not planned to be in that release. But if we could agree on the design and someone writes a PR, there is a chance that the enhancement could make it to the next release.

Because this gets asked quite regularly, perhaps thinking on the design is good idea. I agree on Pekka design in here: https://github.com/robotframework/Selenium2Library/issues/498#issuecomment-135882795

I also want this to be included:
1. When sending multiple key combinations, like `| CTRL+A | CTRL+C |` I want user to be able to define delay between the key combinations. By default delay should be really small or zero.
2. User should be able to decide will keyword clear the text in the element or not.

**Comment by aaltat** [comment]
Also it's worth considering should we also support sending keys without a `locator`

**Comment by fredweb75** [comment]
It was on dev 1 year ago... I'm looking forward for this feature to be available in Selenium2Library. This should have been part of PressKey tho... Will it be there soon?

**Comment by aaltat** [comment]
The status is same as in my previous message. The next step would, for someone else than me, be draft acceptance test cases, to make sure that we agree on the design. Then the implementation could start by someone and in some point we would have PR.

**Comment by berkis** [comment]
Hi everyone, what is the actual state of this issue please? So many commnets but cant see the resolution. Is it already implemented in sellenium2library? Or how can I track when the functionality (press multiple keys, e.g. CTRL+Z, CTRL + S) will be released? It is esential for upcomming work on my test cases. Thank you :)

**Comment by aaltat** [comment]
If you feel that this is important for you, then please consider contributing. Currently this is out of scope of the 3.0.0 release. The next step would, for someone else than me, be draft acceptance test cases, to make sure that we agree on the design. Then the implementation could start by someone else than me and in some point we would have PR.

**Comment by berkis** [comment]
OK, how can I contribute, what exactly can I do about this? I am very very new to this forum and all this stuff, but I am willing to contribute best I can. What do you mean by PR?

**Comment by Tset-Noitamotua** [comment]
@berkis PR = pull request

[github pull request youtube](http://lmgtfy.com/?q=github+pull+request+youtube)
[how to github pull request](http://lmgtfy.com/?q=how+to+github+pull+request)

;-)

**Comment by aaltat** [comment]
Also if the feature is important for your company, consider asking from your company could they allow to do it on working hours. Also it's possible to pay someone to do the feature: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

For contributing instructions, please first read: https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst

**Comment by berkis** [comment]
Thank you for the information provided. 
Finally, I have found a workarround for my problem which might solve it, adhoc for me - I can remap in our app combined hotkeys to only single hotkey, e.g. CTRL + B = B.. Not very smart, since you have to be carefull what chars to use in text, but fast and cheap and working :D 
As far as seleting text is concerned I have found out that javascript can be used to achieve this, more exactly createRange with possibility of defining start and end of the selection. 
So with couple of workarrounds I can proceed with buidling test cases...
...I am afraid that my company wil not be willing to pay for developing such feature but at least I know what can be done about this issue and where to track a progress.. Thank you :)

**Comment by pandabat** [comment]
You can still use my original "hack" from here if you're stuck and waiting for an official solution:

https://github.com/robotframework/SeleniumLibrary/issues/275

You may need to re-hack things after updates to the library but it will let you automate with such key presses until such time as this is formally adopted. Just be aware that you may need to update your code at that time so perhaps use a wrapper keyword for things like "Press Arrow Left" so you only need to make the change in one place instead of 50/100/1000 places.

**Comment by karthi1021** [comment]
> In the long term, I'd like to deprecate the ability for `Press Key` to take in a string. That was an undocumented feature and I feel like it really doesn't function how one would expect `Press Key` to function.
> 
> As for `Press Keys` I like having each key being an argument with `+` as a separator.
> 
> ```
> Press Keys | //xpath | CTRL+C | CTRL+V
> ```
> 
> I think we can split the key string on the separator and trim the keys so you can have spaces or not. That can be left up to preference. I also think being able to optionally set the separator would be a bonus.
> 
> ```
> Press Keys | //xpath | sep=- | CTRL-+ |
> ```
> 
> That's not a necessary feature, but it could be useful. It's a little ugly though, I'll admit.
> 
> Finally, typing multiple characters should be handled by a new keyword call `Send Keys`. This is the method selenium uses to do keypresses in general and I feel like it would be natural for new users.
> 
> ```
> Send Keys | //xpath | Hello World
> ```

For me it is throwing error as "No keyword with name 'Send Keys' found." Whether we need to include any header except the Selenium Library, Selenium2Library

**Comment by aaltat** [comment]
Currently this is in scope of the 3.3.0 release and it is not yet released. But enhancement has been postponed quite many times, so if you feel that this is important for you, then please consider contributing.  The next step would, for someone else than me, be draft acceptance test cases, to make sure that we agree on the design. Then the implementation could start by someone else than me and in some point we would have PR.

**Comment by aaltat** [comment]
This issue has really long history and understanding how the keyword should work, is really hard. Therefore this issue is replaced with issue #1250 which cleaner explanation and examples.

**Comment by jkraju789** [comment]
How to press F2 button from keyboard.

**Comment by aaltat** [comment]
Have you tried with
`| Press Keys | None | F2 |`
More details about the Selenium special keys can be found from https://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.keys.html#selenium.webdriver.common.keys.Keys.F2

**Comment by jkraju789** [comment]
I have tried with below. it's getting fail
Press key    None    //3C

**Comment by aaltat** [comment]
The `Press Key` is deprecated and does not support the all Selenium special keys. Use `Press Keys` (note the `Keys` instead of the `Key
`) which has native support for Selenium special keys. Please see the `Press Keys` keyword documentation for further details how to use the keyword.

**Comment by nikhitha-tr** [comment]
what can we give for enter key... can anyone help me in this??

**Comment by aaltat** [comment]
These kind of questions should be asked from the community https://github.com/robotframework/SeleniumLibrary#community

**Comment by rayennaat** [comment]
I want to keep pressing CTRL while i move my element by drag and drop but it doesn't work

**Comment by HelioGuilherme66** [comment]
@rayennaat You should use the Forum or Slack (or mailing list).
