### ISSUE TITLE
Get Webelements: return empty list if no elements found

### ISSUE THREAD

**Issue by postmart** [robotframework/SeleniumLibrary#523]
In case there are no elements found on a page, `Get Webelements` raises `ValueError`:

`FAIL : ValueError: Element locator 'css=.file-grid.selectable' did not match any elements.`

Is it possible to make behaviour similar to selenium `find_elements_by_` behaviour and just return empty list?

**Comment by aaltat** [comment]
Yes it is and by looking code it should not be difficult to do. See https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/keywords/_element.py#L29 and https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/keywords/_element.py#L675 If I recall correctly if `_element_find` function `required` argument is set to `False` an empty list is returned. 

I think best would it configurable and make the default so that it raises the `ValueError`. Pull request are welcomed.

**Comment by pekkaklarck** [comment]
I agree returning empty list would be more logical and consistent. I don't see why it should be configurable. Do you @aaltat have some use cases for that? I wouldn't worry too much about backwards compatibility in this case.

**Comment by aaltat** [comment]
The backwards compatibility is the only thing which makes me want it to be configurable. And not raising the error diverse from standard practice of S2L. But all these are very weak reasons and I don't feel strongly about the matter.

**Comment by emanlove** [comment]
I have an issue with the behaviour not being consistent. There are ways one can use the current functionality and if error is raised set a variable to an empty list. Or even initialize the variable as empty list first. (Just thinking of the top of my head here). But having inconsistent behaviour, I my opinion, is a really bad thing.

**Comment by aaltat** [comment]
@emanlove What about configurable behavior then. By default raise an exception and in if set to False (or something diverting from default) return a list always.

**Comment by pekkaklarck** [comment]
I agree with @emanlove that worst thing here is inconsistency. Inconsistency remains even if the behavior would be configurable but the current behavior is the default. I would be fine with just changing the behavior. It can only cause backwards compatibility issues if someone is actually relying on the error. Would probably be better not to change this in a minor release, though.

**Comment by emanlove** [comment]
I would be willing to consider that and agree this would be a major release ticket item if agreed upon.

There is another enhancement I considered with the Get WebElement(s) and that is being able to supply an optional parameter giving the root of the search. So Instead of searching from the top of the dom specify some element as root.  If you look at some of the WebDriver code and frameworks many have this ability to specify the root. This could come in handy with the Angular code. Just thought I would mention this and will open another ticket with the idea/proposal.

**Comment by just-be-dev** [comment]
Sounds like a good 1.8 candidate.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by aaltat** [comment]
This is actually now done

**Comment by pekkaklarck** [comment]
See #805 for details.
