### ISSUE TITLE
Inserting code in robotframework 

### ISSUE THREAD

**Issue by peacechan** [robotframework/SeleniumLibrary#545]
Can we insert code (python, bash, ruby etc..) into the robotframework ride.py text editor?
Or is there any other way to write code into it?

**Comment by aaltat** [comment]
Ugh

This is a Selenium2Library issue tracker, but you are talking about RIDE. Are you sure that you have you have entered the issue to the correct place? RIDE is part of the Robot Framework ecosystem, as is the  Selenium2Library, but they are totally different projects. 

If you are having a Selenium2Library problem, could you describe your problem better, because I don't understand your problem. 

If your problem is a generic  Robot Framework question, sending mail to the Robot Framework user group, could provide better answers.

-----Original Message-----

**Comment by peacechan** [comment]
I am new to this that why I am asking the question. Thanks for your response, I will try it into Robot framework user group

**Comment by aaltat** [comment]
No problem. I recall quite well when I first started using Robot Framework and all was new and very confusing. I will close the issue, but if you encounter any Selenium2Library bugs, please do not hesitate to send us bug report to this issue tracker.

For general problems/questions, in any library or in core framework, the [user group](https://groups.google.com/forum/#!forum/robotframework-users) is usually the best place to ask.
