### ISSUE TITLE
Issues with Capture Page Screenshot

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#555]
We run in an obviously well known error, which seems to be webdriver related: if a screenshot is considered to be too big (whatever that means), it throws an error:

16:16:21.698    TRACE   Return: ('FAIL', u"WebDriverException: Message: Could not convert screenshot to base64 - Error: Invalid base64 data: data:,\nBuild info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'\nSystem info: host: 'clab858node04.netact.nsn-rdnet.net', ip: '10.91.151.133', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.7.1.el6.x86_64', java.version: '1.7.0_79'\nDriver info: driver.version: unknown\nStacktrace:\n    at <anonymous class>.FirefoxDriver.prototype.screenshot (file:///tmp/anonymous7110279962792942801webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10871)\n    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h (file:///tmp/anonymous7110279962792942801webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12643)\n    at <anonymous class>.DelayedCommand.prototypee.executeInternal_ (file:///tmp/anonymous7110279962792942801webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12648)\n    at <anonymous class>.DelayedCommand.prototype.execute/< (file:///tmp/anonymous7110279962792942801webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12590)")

The big problem with that: a "capture page screenshot" is very often used as a debug aid. But when this exception occurs, the test case is being marked as failed (and stopped at that location).

In order to workaround, I need to ignore this potential situation in my test case (each an everywhere I use it), or I need to write an own keyword for that. Sure, that can be done (and I did it however), but developers tend to forget this which leads to this unnecessary failure of test cases.

Therefore I would recommend that the Selenium2Library should catch this error situation and only issue a warning then

(A minor issue: as this problem leads to the build-in recursive call of Capture Page Screenshot, we have two failure in such a situation. The standard behavior for failing Selenium keywords should be changed such that a second "Capture Page Screenshot" is not executed if the reason for the failure was the "Capture Page Screenshot" keyword itself.

**Comment by aaltat** [comment]
I think we should not suppress this kind of errors, because people relay on the current functionality. If keyword success, screen capture is created. By looking the stack trace, it looks like a selenium related problem, with Firefox. Have given a try with selenium only, can you reproduce the error?

**Comment by ombre42** [comment]
On your minor issue - Selenium2Library executes whatever keyword you register. By default, Capture Page Screenshot is registered. Checking to see if the failing keyword is the same as the registered one doesn't pass the smell test. What if the registered keyword is a user keyword that calls Capture Page Screenshot. I do not think the impact of having an extra failure when the test is already failing justifies having the code behave in a strange way like checking what keyword is registered and skipping it in some scenarios.

**Comment by aaltat** [comment]
Did you have a chance to try it with pure selenium code? Just want to know is the problem with the Selenium2Library or selenium side. If you need help with selenium side, just let us know and we can work something out.

**Comment by tarand** [comment]
Hi,

I guess a simple recurse-check would help here. On (first) entering Capture Page Screenshot it could set a (local static) flag variable. Everytime Capture Page Screenshot is entered it would check this flag variable. If already set, it would return doing nothing. Only if it is not set, it would continue. However, on return it must reset that flag variable again. I don’t think this would cause a nasty change.

Ciao,
Thomas

---

Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023  / (Soft) 8041034
thomas.arand@nokia.commailto:thomas.arand@nokia.com

**Comment by tarand** [comment]
Hi,

this problem cannot be reproduced reliably. It happens from time to time. This makes the problem so nasty.

What do you mean by “try with selenium only”?

Ciao,
                Thomas

---

Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023  / (Soft) 8041034
thomas.arand@nokia.commailto:thomas.arand@nokia.com

**Comment by aaltat** [comment]
The selenium only means, that have you tried to reproduce the problem with with [selenium python bindings](https://pypi.python.org/pypi/selenium), by writing pure python code. The Selenium2Library is a (thin) layer on top of the selenium, to expose selenium functionalities as keywords to Robot Framework. But that part of the code is quite simple and based on the error message, I do suspect that it is a compatibility issue between selenium and Firefox (version which you are using). It is recommended to use the Firefox version which is officially supported by the selenium. See the [selenium change](https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES) log for better details.

I do not agree on the recurse-check. Although your point is valid, that by default configuration if the [Capture Page Screenshot](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Capture%20Page%20Screenshot) fails, the [run on failure functionality](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Register%20Keyword%20To%20Run%20On%20Failure) will run the Capture Page Screenshot second time. Although it is not likely that the second run will succeed, it might be possible that it will succeed on second time and user have more information on the problem. Also even the run on failure functionality is suppressed automatically, on these kind of special cases,  it does not change the point that the test will fail because the keyword did fail. And as explained earlier, it is not possible to suppress the error by Selenium2Library.

As a solution to your problem, you could extend [1],[2] the Selenium2Library and write your own keyword to capture page screenshot. In this new keywords you can do whatever you want.

[1] http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#extending-existing-test-libraries
[2] http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#getting-active-library-instance-from-robot-framework

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
