### ISSUE TITLE
Issues identifying locator using index in xpath

### ISSUE THREAD

**Issue by vinaybond** [robotframework/SeleniumLibrary#567]
My xpath is matching multiple elements so I am providing index to it but it does not work. I am getting error "Element locator with prefix '(//tbody[@role' is not supported"

Here is the locator:
(//tbody[@role="presentation"])[4]

**Comment by aaltat** [comment]
Try `xpath=(//tbody[@role="presentation"])[4]`

**Comment by vinaybond** [comment]
Thanks. It worked.

**Comment by just-be-dev** [comment]
This issue is because the selector prefix for xpath is just `//`. It doesn't default to xpath. 

We could add `(//` as a prefix for an xpath selector, but my preference is that we leave it as is because it's simple. 

@aaltat if you agree we can close this ticket. If not, we should open another ticket on the xpath prefix.

**Comment by vinaybond** [comment]
"//" always work. I guess its the round bracket "(" that xpath is not able to understand. I guess xpath parser need to be enhanced here.

**Comment by aaltat** [comment]
Lets open a new issue if need arises to enhance the xpath prefix. I have always liked to be explicit and not implicit on this type of matters.
