### ISSUE TITLE
Pressing the F6 key

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#579]
I need to simulate pressing the F6 key upon a button (as the button currently has the focus). I tried

```
selLib.Press Key | ${buttonId} | \\117
```

but that doesn't select the address bar.

What can be wrong?

**Comment by pandabat** [comment]
Hi this is something that I originally raised as part of 

https://github.com/robotframework/Selenium2Library/issues/275

and which is now being handled under 

https://github.com/robotframework/Selenium2Library/issues/498

You can hack the code as I outline in 275 until such time as the guys decide on some better means to integrate this into the library properly. I wouldn't hold my breath though :) ... I raised this initally about 2 and a half years ago and the first (aborted) attempt to integrate this was over a year ago. Not much seems to have happened since.

Bear in mind that you will need to re-hack the associated file if it is overwritten by an update.

**Comment by pandabat** [comment]
You might close this issue if my hack fixes it and maybe just reference it in #498

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
