### ISSUE TITLE
Feature Request - Click Elements

### ISSUE THREAD

**Issue by Gaurang033** [robotframework/SeleniumLibrary#585]
currently, there is no keyword which clicks all the matching elements. I had few occasions where I need d it and have written down the code for it. 
if it could be used by others I could implement it. Following could be a use case for this keyword. 
1. you have multiple checkboxes or buttons and you need to click them all.

**Comment by aaltat** [comment]
I agree that this could be handy in some occasions. Have think a name for a keyword and how would the keyword work? Would you have some examples? Also could you send a pull request so that we can see the code

**Comment by Gaurang033** [comment]
Hi. 

I have code in place and I am using that as well, if you are planning to merge the code I code write few test cases for that and create a pull request in a day or two ? Do I need to open an ticket for this ?

**Comment by aaltat** [comment]
No need to open new ticket, creating pull requests should be enough.

**Comment by Gaurang033** [comment]
@aaltat I have created the pull request for the code with my other pull request. Can you please merge the code. I was thinking to contribute more to this library however I feel, the rate of merging the code from pull request is very slow. I created the pull request in march and and then code hasn't been merged yet.  :(

**Comment by ombre42** [comment]
While I really appreciate the effort in contributing to this project, I feel that his feature is not worth the addition of a new keyword as there are already so many and I think we need to be cautious about adding new ones as it makes the library harder to use. I feel bad about that since there is already a PR out on this and I have not commented before now. The goal of this keyword is readily accomplished by what I believe to be a short and obvious combination of other keywords and syntax:

```
${elems}  Get WebElements  some_locator
:FOR  ${elem}  IN  @{elems}
\  Click Element  ${elem}
```

While there are times this keyword may be really useful, there are also other keywords we could have to do similar things like `Input Texts`, `Clear Element Texts`, `Click Images`, `Click Links`, `Delete Cookies`, `Elements Should Be Disabled`, `Get Texts`, etc. If we had all of these and the many more I am not mentioning, it would make the library difficult to use. Surely the Selenium API is a bit too bare bones, but I do not think we want to go completely the other direction and have keywords for every possible use case.

**Comment by emanlove** [comment]
I second @ombre42 thoughts.
