### ISSUE TITLE
Slow/incomplete page load in the browser launched by selenium2library

### ISSUE THREAD

**Issue by vinaybond** [robotframework/SeleniumLibrary#586]
I am using selenium2library using RobotFramework. The major problem we are facing is, my tests are timing out even after setting timeout as high as 10 minutes. It happen with any browser I use. These thing works much faster If I run test manually (with all browser cache/data/cookie cleared). These are the other things I have observing for few months.

Some component are never loaded (I check the call trace using BrowserMob Proxy and we found nothing unusual)

"Click Element" does not work in many cases. Clicking on element triggers some action but that action is not always triggered in automation. Manually it works all the time.

Notes:

```
- This is happening on FF and Chrome. (IE is not working for me at all)
- App server and automation suite is in LAN so latency is not an issue
- No other heavy process is running at this time
- Issue persist even if with firefox default profile
- I tried it with different selenium versions. (2.45 - 2.52)
- I took latest driver for chrome. Broweser: FF 42+ and GC 48

```

This does not look application issue as we spent 2 month confirming that. Let me know if you need any other detail.

**Comment by aaltat** [comment]
There can be multiple reasons why the automation don't work for you and most likely you are facing multiple problems, instead of a one problem. I don't have a solution for your problems, because that would need access to your app and time to investigate the problem. But I have faced similar problems in my automation projects and I can tell the most common problems which I have faced.

1) The automatic test is too fast. Although the element is in the page, it's not ready to receive the interaction. There might be dynamic content, which is not ready and one needs to pool that before, one interacts with the element. And if interaction is done too early, nothing happens in the application side.

2) Stale element reference exception, is same as to the above mentioned problem, but it manifest in different way. Again the key is in polling.

3) Sleeping or using Selenium2Library set selenium speed. Sleeping doesn't help, it can actually make things worse. Replace the sleeping with polling and the test will be faster and rate of false alarms is smaller.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by vinaybond** [comment]
Yeh, I am still facing above issues. I request to keep this open if someone can take a look at it.

**Comment by aaltat** [comment]
If you want someone to take closer look, you have to provide more details from your problem. An example which anyone can run would be best, if it is possible to make. 

Also it seems that you have multiple problems. Perhaps it would best to focus to a single problem at the time and raise separate issues for the other problems.

So what is the biggest single problem you want to solve? How does it appear, in which keywords, do you get an errors, is something in the browser console. In which browser version this happens, what OS you are using, what selenium and Selenium2Library version you are using. Can you demonstrate the problem with a example which we can also run?

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by aaltat** [comment]
Closing because this doesn't look like a S2L issue
