### ISSUE TITLE
How to call Capture Page Screenshot keyword within robot framework listener

### ISSUE THREAD

**Issue by jagadishchandran** [robotframework/SeleniumLibrary#608]
I want to capture page screen shot for failed test cases. I want this to be implemented in Robot framework listener (end_test).  I have previously setting a suite variable from the listener (start_suite) like  BuiltIn().set_suite_variable('${Password}', xxxxx) by importing (from robot.libraries.BuiltIn import BuiltIn).  Now looking for similar solution to capture page screen shot.

**Comment by aaltat** [comment]
This issue tracker is for Selenium2Library and I think you are looking for the Robot Framework issue tracker: https://github.com/robotframework/robotframework/issues

Although it would be better to post this kind of question to the Robot Framework user group.

Closing issue because it is not Selenium2Library issue.

**Comment by jagadishchandran** [comment]
Hi Tatu

This is is capture page screen shot is a selenium2Library keyword. How to call this selenium2library function directly from a python file.

**Comment by aaltat** [comment]
This is explained in the user guide: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#getting-active-library-instance-from-robot-framework

**Comment by jagadishchandran** [comment]
Thanks Tatu,

It worked for me.
