### ISSUE TITLE
Fail to open browser after firefox 47 update.

### ISSUE THREAD

**Issue by yan0pe00** [robotframework/SeleniumLibrary#610]
Fail to open browser after firefox 47 update.

**Comment by aaltat** [comment]
It is quite common that Firefox update does break the selenium compatibility. I would try to downgrade the Firefox to latest supported version by the selenium. Which based on the selenium change log[1], seems to be version 44. Unfortunately finding the supported version from selenium change logs  is always somewhat black art. Upgrading to latest selenium[2] version is also recommended. 

Also it is wise to disable the browser automatic updates when test automation is done with browsers and only perform the updates in a controlled manner. 

But because this, I am almost sure, is a selenium issue and not a Selenium2Library issue I am closing the issue. The proper place to report this issue is in the selenium issue tracker, but I think someone already did it: https://github.com/SeleniumHQ/selenium/issues/2110

-Tatu 
[1] https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG
[2] https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES
