### ISSUE TITLE
No output even after 10 minutes

### ISSUE THREAD

**Issue by vishaltelangre** [robotframework/SeleniumLibrary#612]
Here's my stack:

```
robotframework==2.9.2
robotframework-selenium2library==1.7.4
```

This is an example Robot file I have:

``` robot
*** Settings ***
Library  Selenium2Library  10

*** Test Cases ***
Dummy Test
    Open Browser  http://google.com  browser=chrome
    # ... omitted keywords below
```

Here's how I run it:

``` sh
pybot dummy_suite.robot
```
### Trial 1:

Only this much output I see for more than 10 minutes:

```
==============================================================================

Dummy Suite                                                                        

==============================================================================
```

A blank log.xml file gets generated. No log.html and report.html generated for this trial.
And here's the gist of syslog: https://gist.github.com/vishaltelangre/2ff5ae72e5618c6142703051af8b507c#file-syslog-trial-1-txt
### Trial 2:

In trial 2, for the same test, it finishes in a few second successfully:

```
==============================================================================

Dummy Suite                                                     

==============================================================================

Dummy Test                                                                    | PASS |

1 critical test, 1 passed, 0 failed

1 test total, 1 passed, 0 failed

==============================================================================

Output:  /home/vishal/tmp/log.xml

Log:     /home/vishal/tmp/log.html

Report:  /home/vishal/tmp/report.html
```

Here's the syslog for trial 2: https://gist.github.com/vishaltelangre/2ff5ae72e5618c6142703051af8b507c#file-syslog-trial-2-txt

---

As you can see, no reason why trial 1 was not responding (for more than 10 minutes), but when retried it worked in trial 2 (just in few seconds). 

This behaviour is not reproducible, but happened so many times with me.

Can anybody help me to understand (by looking at the syslog), whether there is any issue with the pybot (or robot framework) itself or not?

**Comment by aaltat** [comment]
It doesn't even get to the phase where it would import the Selenium2Library, in the trial 1. Therefore I think this is not a Selenium2Library issue and you would get better help from Robot Framework issue tracker: https://github.com/robotframework/robotframework/issues One thing you could also look is to use the debug file from Robot Framework: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#debug-file

If that doesn't provide any additional information for the problem, you could enable the ROBOT_INTERNAL_TRACES, see more details in the user guide: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#debugging-problems

I agree that you have a problem but it also looks that it's not a Selenium2Library problem. Instead it looks like a problem in the Robot Framework or in the Python. Because of this I am closing the problem. You should raise the problem in Robot Framework issue tracker

**Comment by vishaltelangre** [comment]
@aaltat Thanks. I would report this in Robot Framework issue tracker.
