### ISSUE TITLE
Wait Until Page Loaded not found In selenium2Library 

### ISSUE THREAD

**Issue by Tibingeo** [robotframework/SeleniumLibrary#616]
Wait Until Page Loaded Not Found In selenium Library , Is there any alternative way to use this

**Comment by aaltat** [comment]
The [Webdriver](https://github.com/SeleniumHQ/selenium), also known as selenium 2 or selenium, is blocking type of API. Which means that selenium will automatically wait for the browser to report that page is loaded (that is, the “onload” event has fired in the browser). Because of this the Wait Until Page Loaded keyword does not exist in the Selenium2Library.

**Comment by aaltat** [comment]
Are you still having problems on the matter or can we close the issue?

**Comment by aaltat** [comment]
It seems that issue is resolved and therefore closing the issue. If it's not resolved send an update and we will open the issue.

**Comment by Tibingeo** [comment]
Fixed issue Execute Javascript ${element}.scrollby(0,200) Will not work on every case if element is not in viewport it will not scroll. there's efficient way to scroll the page to get element to view port .

If we are using Execute Javascript     Window.scroll(x,y) we need to specify horizontal and vertical position x,y which is difficult to find and may not be accurate .

Instead we can use the following line of code  Execute Javascript    window.document.evaluate("//xpathlocation", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scrollIntoView(true);

The above code will scroll window and get element specified in /xpathlocation to view port

**Comment by aaltat** [comment]
This looks a different problem. Please open a new issue about the new problem. Also sending mail to the Robot Framework user group might be a good solution
