### ISSUE TITLE
Reset Browser Keyword / Remove All Cookies Across Unique Domains Visited

### ISSUE THREAD

**Issue by snyderr** [robotframework/SeleniumLibrary#622]
With my companies current setup we are opening and closing browsers hundreds of times during testing. As you could imagine doing this over and over takes up a lot of unnecessary time. I currently have a semi-working version of a `Reset Browser` keyword. Currently this keyword will close all extra tabs that are open and remove all cookies from all unique domains that were visited during testing. 

One issue I came across while creating this keyword was that currently `Remove All Cookies` only removes the cookies on the current domain. I was able to work around this by storing the current domain whenever we expected a page change and then having the `Reset Browser` keyword loop through each unique domain visited and remove the cookies.

Would it be possible to add the ability to automatically keep track of all of the domains visited during the current session? Or a keyword similar to this that would remove all cookies across all the domains that were visited?

Here is what the keyword looks like so far. 

```
Reset Browser
    [DOCUMENTATION]  This keyword will reset the open browser and close all excess tabs that are open.
    ...  Goes to each unique domain that was visited during testing and delete all of the cookies.
    @{domains visited}=  Get Domains Visited  @{pages visited}
    @{pages visited}=  Create List  ${EMPTY}
    :FOR  ${domain}  IN  @{domains visited}
    \  Go to  ${domain}
    \  Delete All Cookies
    @{windows}=  List Windows
    ${total windows}=  Get Length  ${windows}
    Run Keyword If  ${total windows}==1  Return From Keyword
    :For  ${window}  IN RANGE  ${total windows-1}
    \  Close Window
    \  Select Window  main
```

**Comment by aaltat** [comment]
Ugh

I can't not think a other way to do it, because the limitation is not only
on the selenium side but there is browser security issues included.

Perhaps you could solve your problem in different ways. Because you need a
"clean" browser and opening a new browser takes too much time. Also
cleaning the browser takes time and is error prone. Perhaps it could be
possible to open few browser before hand and you could always request a new
browser from the pool. Writing a library that would always keep a pool of
browser open and could give you clean browser quickly should be possible.

-Tatu

**Comment by aaltat** [comment]
Do you still have a problem with this or can we close the issue?

**Comment by aaltat** [comment]
Because response was not received, I assume that this is not anymore an issue and I will close the issue. If you think that this is still an issue, please send an update.
