### ISSUE TITLE
"Click Element" keyword does not work in some case

### ISSUE THREAD

**Issue by vinaybond** [robotframework/SeleniumLibrary#625]
In some cases i see the "Click Element" keyword had clicked on the element but the action on that element in not triggered. When I say "keyword had clicked on element", it means it did not throw any error. In some cases I can see the dotted border (in screenshot) around the element which normally happens when we click on element. Has anyone encountered such kind of problem?

::My Questions::
1. Can it happen that selenium misses the click
2. I have put the waits for that element to be visible & enable. Assuming a possibility that corresponding JS is not loaded, in this case it should throw error which is not happening. I am capturing details via BrowserMobProxy which does not show any JS error.
   I am clueless why this is happening.

Few observation: 
- Whenever the environment is slow, this tend to happen more 
- We tried adding consecutive clicks for same element (with "Run Keyword And Ignore Error" with second "click element") and it worked.

**Comment by SteveHarrison82** [comment]
I noticed it happening with 'Click Elements' when events generated by
selenium api (in this case,  Click Element) is faster than the Browser
response

**Comment by vinaybond** [comment]
@rama-bornfree ,
You mean browser's "Click" event was not generated when Selenium Clicked on some element? If that is the case, what solution can work here?

**Comment by SteveHarrison82** [comment]
I slowed down selenium speed and reset to original value of selenium speed
after the event.

A short note: Python Selenium API at times, I find not synchronous and this
error is not avoidable and random esp in chrome

**Comment by aaltat** [comment]
If @vinaybond can see that click happens in the UI, but the action is not triggered in the application, then I would assume that this is a application problem or the test code problem and not a Selenium2Library issue. Because the selenium can be really fast and because the problem is more frequent on slow machines, I would assume that this some sort of timing issue. It feels that sometimes click is performed before the application is ready to receive the click, which is actually quite common problem. The assumption can be easily tested by temporally adding a sleep before the click. If the sleep resolved the problem, then it is a timing issue. 

To permanently solve the problem, without the sleep, you need to find the correct thing to poll. It can be other element, some hidden id or class or totally something else. Best way to find the solution is to ask from your development, which thing indicates that the page is fully loaded and is ready to receive the clicks.

But because this feels a timing problem and not a Selenium2Library issue, I am closing the issue. If someone feels that this is a Selenium2Library issue please send more details and we will re-open the issue.

**Comment by vinaybond** [comment]
Hi @aaltat (or anyone),
I am stuck here. I can see in page screenshot on which I can see the element on which I want to click. Click element keyword is also not giving any error. But the action is not triggered. As discussed, it is random and happening at multiple places. How can I handle this situation. I tried these
- I am already using waits which is passing and after that "Click Element" is executed
- Added Implicit wait (of 1s)
- Slowdown the selenium speed (.5s)
- Added hard coded sleep of .5s before click 

What do you think is missing here. How can I get rid of the problem?

-Vinay

**Comment by aaltat** [comment]
Reopened, so that better answer is given. But have do to my day job first.

**Comment by aaltat** [comment]
Sometimes, also in my application, it's not enough to wait that the element is in the DOM or even visible in the page. This is also true when the application is dynamic by using JavaScript. I did write my own element clicker library, which wait that the element is not in stale state and tries to wait that JavaScript is not anymore running in the background. By checking these two conditions, it did eliminate all the errors to which seemed to be caused by the application not receiving the click.

Unfortunately I can't directly share the library, because it's made on company's time and all code is not written by me. But I can tell how to write one.

The stale state check is based on the selenium explicit waits:  http://selenium-python.readthedocs.io/waits.html#explicit-waits. I am using `element_selection_state_to_be` check but some other check might work better in your case.

The JavaScript running is checked by executing `return jQuery.status` and making sure that the result is zero at least two times in a row.

The above did fixed the problem in my application, but I am not sure will it fix your problem. This is because a silver bullet to fix this type of problem does not exist. It took me several iterations to actually find out what was the reason for the failures. And after the understanding, it came easier to fix the problem in my case. I did have to read the logs from the application, when the no click happens. I did read the console logs from the browser also in same situation. I did capture a video and played it back with slow motion to actually see when element appears in the page and when clicking happens. I did talk to our development and ask what might the reason.

It was a quite a big hunt and required lot of effort to make it work. But it definitely paid off, because now test are more stable.

**Comment by aaltat** [comment]
Leaving the issue open, for a while at least, in case more questions arise from my high level technical jargon.

**Comment by vinaybond** [comment]
Can't the improved done in Selenium2Library itself? I dont remember facing any such issue when I did automation in Selenium WebDriver + Java. It was smooth sailing always (it was a different application though).

**Comment by aaltat** [comment]
I do not think that universal solution could be found to cover at even the most common situations. For example there are many [explicit waits](http://selenium-python.readthedocs.io/waits.html#explicit-waits) in the selenium side and it easy extend with a custom wait to support user special case. For my experience these types of things are application specific (although my experience does not cover that many different applications).

The universal thing we could do, is to user configure which explicit wait is done. But that would require rewriting huge parts of the library. It could happen, if someone sees it necessary but I do not think it will happen in the near future.

Writing libraries is not hard in Robot Framework. Also if you plan to do lot of browser based test automation, understanding selenium in deeper level has many advantages. Also you get to learn new things, which is always fun.

**Comment by vinaybond** [comment]
One question. Is there a generic way to check if the JS is loaded or not. We are not using JQuery but multiple frameworks.

**Comment by aaltat** [comment]
Well, I did in a try/expect block. Selenium will raise an exception if it can not execute JavaScript.

**Comment by aaltat** [comment]
Sometimes, also in my application, it's not enough to wait that the element
is in the DOM or even visible in the page. This is also true when the
application is dynamic by using JavaScript. I did write my own element
clicker library, which wait that the element is not in stale state and
tries to wait that JavaScript is not anymore running in the background. By
checking these two conditions, it did eliminate all the errors to which
seemed to be caused by the application not receiving the click.

Unfortunately I can't directly share the library, because it's made on
company's time and all code is not written by me. But I can tell how to
write one.

The stale state check is based on the selenium explicit waits:
http://selenium-python.readthedocs.io/waits.html#explicit-waits. I am using
`element_selection_state_to_be` check but some other check might work
better in your case.

The JavaScript running is checked by executing `return jQuery.status` and
making sure that the result is zero at least two times in a row.

The above did fixed the problem in my application, but I am not sure will
it fix your problem. This is because a silver bullet to fix this type of
problem does not exist. It took me several iterations to actually find out
what was the reason for the failures. And after the understanding, it came
easier to fix the problem in my case. I did have to read the logs from the
application, when the no click happens. I did read the console logs from
the browser also in same situation. I did capture a video and played it
back with slow motion to actually see when element appears in the page and
when clicking happens. I did talk to our development and ask what might the
reason.

It was a quite a big hunt and required lot of effort to make it work. But
it definitely paid off, because now test are more stable.

-Tatu
Send from my mobile

**Comment by vinaybond** [comment]
Two question about using Try/Catch block
1. Since my click is not working as my JS not loaded. I wonder if my browser will throw any error
2. Even if the browser throws error, How does adding try catch block in code will help as error is there in browser.

Do you know any way in which can tel if there is any JS file is yet to load or in progress.

**Comment by aaltat** [comment]
The error is raised also in selenium side and that's the try/expect waiting.

**Comment by vinaybond** [comment]
Oh ok. Somehow I never got this error. Thank for the information. BTW, Any solution to detect if the JS call completed or not on the page?

**Comment by aaltat** [comment]
Surprisingly many pages have JavaScript and therefore error is not raised by the selenium.

There is not a 100℅ sure way to detect is all JavaScript run. This is because of asynchronous nature of the JavaScript and because one script can load new scripts for running. The best way I did found was to execute `return jQuery.status` and wait that it's zero two times in a row.

**Comment by emanlove** [comment]
@aaltat has great suggestions here. I have read about others who have faced similar issues, for example [this article written by Al Scott](https://spin.atomicobject.com/2015/05/12/testing-asynchronous-behavior-javascript-selenium/). This is a problem faced by those of us who test angular sites using Robot Framework for which we have some [interesting](https://github.com/rickypc/robotframework-extendedselenium2library) [solutions](https://github.com/Selenium2Library/robotframework-angularjs). Essentially both of these are modelled after Protractor which is the end-to-end testing framework for AngularJS. At its core it has an implicit wait for angular call which is invoked for most of the selenium methods and when elements are located. [Richard Huang's implementation](https://github.com/rickypc/robotframework-extendedselenium2library) takes the approach of overwriting the Selenium2Library methods adding the wait for angular. [The other implementation](https://github.com/Selenium2Library/robotframework-angularjs) takes the approach of when you use a locator in the Selenium2Library it calls the Wait for Angular method implicitly thus resolving many of the timing issues we see in AngularJS testing.

You should take a look at these and if you have any questions about the RobotFramework-AngularJSLibrary I can help you understand what we did there. (I also [added a write-up](https://github.com/Selenium2Library/robotframework-angularjs/blob/master/TESTING.rst) in the source repository that covers most of the design and implementation).

One last note, there is an interesting project, called [ToDoMVC](http://todomvc.com/), which tries to demonstrate as many MV\* frameworks using the same simple To Do List web application. A dream project I have in mind is to show how one can test those different frameworks and in particular deal with the timing issues in each of these frameworks. This is very much a dream and I currently have no time to work on such a project but it would really cool to see these ideas of resolving the timing problem and demonstrated on this one application.

**Comment by vinaybond** [comment]
BTW, I checked our JS framework. It is WDK and it creates entire HTML page (with JS inside it) and give it to browser. So in that case, chance of my JS is not loaded is gone. Still I see clicked does not work. Any idea?

**Comment by aaltat** [comment]
At least I don't have any better ideas, at least without seeing your application. But I don't work in the consulting business and therefore I am not the correct person to ask such consulting help

**Comment by emanlove** [comment]
Have you tried a pure selenium test case? Or tried reproducing you problem with a very simple and short python unit test? There is an [example within the Selenium2Library documentation](https://github.com/robotframework/Selenium2Library/blob/master/BUILD.rst#testing-selenium).

**Comment by vinaybond** [comment]
One of my friend is facing same issues using Selenium WebDriver with Java.

**Comment by aaltat** [comment]
Or you could but a plain sleep, before the click and see does it resolve this problem. If it does then it's a timing problem. If it doesn't, then it's probably something else

**Comment by vinaybond** [comment]
We tried adding sleep but it did not help.

**Comment by emanlove** [comment]
Have you tried clicking a different element? Sometimes there is a tree of elements; a div that contains another div that contains a ... which contains the link you want to click, etc. You might try clicking something that contains or is contained by the element you want to click.

**Comment by vinaybond** [comment]
Yes I tried that. I mean I changed the locator such that it will click exact clickable element. Also, click works sometime and sometime it does not for the same element.
Any other suggestion is welcome.

**Comment by emanlove** [comment]
That is a tough situation to diagnose without much more information. Is there anything more you can describe the elements of the enviroment/page you are working with. Are you using a headless browser, which I am not too fond of because they are not the actually browser? You mention WDK, what is that (I did a Google search and have several possibilities? Assuming every time and I mean every single time one manual clicks it works? etc, etc, ...

**Comment by vinaybond** [comment]
Hi @emanlove ,
I am not using headless browser but Google Chrome & Firefox. WDK is a JS framework which prepares entire HTML pagg (including JS and CSS in it) at server and send it to browser.  About manual test, yeh, it works every single time. In fact in automation when i put 3-5 Click statement, it fails less. But when i add sleep, it did not show much improvement.

**Comment by emanlove** [comment]
The best option may be to use the ```Wait Until Keyword Succeeds``` [keyword](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Wait%20Until%20Keyword%20Succeeds). That way it it not some arbitrary sleep statement nor is it guessing whether three or five tries is the magic number.

So I am assuming you mean [EMC's Web Development Kit](https://developer-content.emc.com/developer/what_is_a_wdk_component.html) and not something like Windows Developer Kit. [There was a lot of WDKs relating to some work of web application/development out there]. EMC's WDK sounds a lot like Java Server Faces and [even it looks like](https://developer-content.emc.com/developer/downloads/wdk5_reviewer_guide7.pdf) WDK uses JSF. My guess, and it is just a guess, is that there is some sort of either AJAX going on or http calls finishing up. Although with the later I would expect some or a fair amount of stale element exceptions. The ```Wait Until Keyword Succeeds``` keyword should help. And if you find out any good flag to check with WDK whether or not it has completed it's "queue of activity" for lack of a better word then that might lead you to a good place to implicitly wait for WDK to complete any AJAX of http requests.

**Comment by vinaybond** [comment]
I already tried wait until keyword success and it passes every time.  The things is, I can see that element is clicked (via the dotted border when you click on element) but nothing happens.

**Comment by aaltat** [comment]
I have encountered a situation we the click happens but application doesn't work. In some rare cases, I have seen it once, the fault actually lies in the webpage side. The webpage may not listen the event what selenium is sending and therefore nothing happens in the application side.

Other alternative for Wait Until Keyword Succeeds is to try click in the for loop.

**Comment by vinaybond** [comment]
@aaltat, Wait Until Keyword Succeeds return true always. It wont return false since this is not the case of failed click command but something at browser/application side.

Any other suggestion?

**Comment by aaltat** [comment]
Did you try a for loop?

**Comment by vinaybond** [comment]
No. But I need to try that, what is the condition should I put?

**Comment by aaltat** [comment]
Something should happen when you click the element? Wait that to happen and exit from the loop if it happens.

**Comment by vinaybond** [comment]
This will work. But the problem is, that "next action" after click is different in each case. I have got like 1000+ suites and has got many click in each, so adding for loop is not feasible. 

Any other suggestion?

**Comment by aaltat** [comment]
It is not meant for a permanent solution, but it could provide a workaround until you find a permanent solution.

**Comment by aaltat** [comment]
@vinaybond is there something that you are wanting from us or could we close the issue?

**Comment by vinaybond** [comment]
I did not get the solution yet. But I think we can close this as from the discussion so far, it looks like nothing can be done at selenium's end.

**Comment by alexey-v-paramonov** [comment]
I have noticed that in my case this issue happened for a page that has `#` at the end of the URL.
If you remove trailing `#` selenium clicks start to work as expected.

**Comment by aaltat** [comment]
This issue is almost two years old and most likely your issue is not the same. Please open a new issue if you think that the problem is in the SeleniumLibrary.
