### ISSUE TITLE
Run Selenium2Library on Mac

### ISSUE THREAD

**Issue by mzbedat** [robotframework/SeleniumLibrary#631]
Hi,
I'm trying to Run Selenium2Library on Mac machine...

I added the following to my ~/.bash_profile:
export SELENIUM_SERVER_JAR=/Library/Python/2.7/site-packages/SeleniumLibrary/lib/selenium-server.jar

When I try to run it from terminal its working:
java -jar $SELENIUM_SERVER_JAR

But when trying to run it from robot framework I'm getting:
No executable path given, please add one to Environment Variable                 'SELENIUM_SERVER_JAR'

I tried as well to add it to ~/.profile instead of ~/.bash_profile
or
To add it to /etc/launchd.conf, but still no luck!
(I have El-Capitan version and tried most of the solutions mentioned here:
http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x)

B.R.

**Comment by aaltat** [comment]
Would you share the example test that you are using. Also could you run the test with `--loglevel trace` and send the exact stack trace?

**Comment by mzbedat** [comment]
Attached.

[final.xml.rename.txt](https://github.com/robotframework/Selenium2Library/files/413497/final.xml.rename.txt)
[log.html.rename.txt](https://github.com/robotframework/Selenium2Library/files/413496/log.html.rename.txt)

**Comment by aaltat** [comment]
I do not have Mac, so I would assume that this is some sort of environment issue because the error message. You could try [Get Environment Variables](http://robotframework.org/robotframework/latest/libraries/OperatingSystem.html#Get%20Environment%20Variables) keyword to list you environment variables. But because I am not help you better, you could try to look issue #615 or send mail to Robot Framework user group with same details.

**Comment by drobota** [comment]
I am working on mac os x and I do not have such kind of issues. But I have one question about lib folder in the s2l package. Did you create it manually? Did you run your test from cli ? 
try `env | grep SELENIUM_SERVER_JAR` to check variable.

**Comment by mzbedat** [comment]
Hi,
- The env variable exist:
  $ env | grep SELENIUM_SERVER_JAR
  SELENIUM_SERVER_JAR=/Library/Python/2.7/site-packages/SeleniumLibrary/lib/selenium-server.jar
- I didn't create the lib folder manually
- its working from cli

I know that my problem is with env settings, I had read about it and bottom line that Apple want to restrict adding system variables and making sure that it won't be easy. Because it can break their operation system.

Adding the system variable to .profile/.bash_profile/... or whatever is good for terminal. But when talking about GUI apps the issue is different.

I had tried several solutions from the web, but couldn't get lucky yet :(
maybe its the version that I have (OSX El Capitan), maybe it's something else.

Thought that maybe it's known issue to you and have clear instructions how to solve it, but seems that I need to keep digging :)

**Comment by mzbedat** [comment]
This solution worked for me:
https://github.com/ersiner/osx-env-sync

But now am getting when running my test:
unable to establish connection with the safari extension

Extension is installed, and enabled (WebDriver 2.48.0)
Safari version: 9.1.1

**Comment by mzbedat** [comment]
With 2.45 Webdriver its working fine.

**Comment by aaltat** [comment]
Because you are not the first one to have a problem with this, perhaps it
would be good to document how you did get it working. I understand that
this is a more a problem how the Mac and selenium works and strictly
(programming) thinking, this is not a Selenium2Library issue. But from the
end user point of view this is a Selenium2Library problem. Therefore would
it be good idea to provide links, example in wiki, to external documents
how to solve particular problems like this? What do other contributors
think?

**Comment by aaltat** [comment]
The documentation has been improved and there are links to the Selenium documentation and therefore I am closing the issue.
