### ISSUE TITLE
Selenium2Library keyword "Register Keyword To Run On Failure" doesn't work consistently.

### ISSUE THREAD

**Issue by arunku2x** [robotframework/SeleniumLibrary#639]
Hi,

I am facing an issue in the Selenium2Library keyword "Register Keyword To Run On Failure". As per its documentation it is supposed to invoke the registered keyword only on detecting a failure in the Selenium2Library keywords. I have registered "Capture Page Screenshot" keyword with this. Now even if the test case is passed, I could see lot of screenshots saved by Selenium2Library. This causes overall logs to be pretty huge.

Is there any solution to this issue?

As far as embedding of this keyword in Robot Framework logs is concerned, it seems to be proper. I could see  "Capture Page Screenshot" keyword invoked only on failure in Robot Framework logs.html file but in reality it gets invoked at a certain frequency as evident with the number of screenshots taken even in case of no failure.

Regards,

Arun Kumar Saini

**Comment by ombre42** [comment]
If you use Wait Until Keyword Succeeds or Run Keyword and Ignore Error, you can have failures in Selenium2Library keywords that do not cause further failures, but still there will be screen captures if that is what is registered to happen on failure. If this is the case, you can:
- use the wait keywords in  Selenium2Library in lieu of aforementioned keywords
- temporarily disable the failure mechanism by registering keyword None and restore later

If you still suspect the problem, then try registering Nothing as the keyword to run on failure at the beginning of your test. If you still see screen captures happening, then it is likely not due to the on failure mechanism.

**Comment by aaltat** [comment]
Do you still experience a problem with the library or was the problem found from somewhere else?

**Comment by arunku2x** [comment]
Thanks to ombre for pointing out the reason. Indeed screenshot were taken as some of the selenium keywords called behind Run Keyword and Return Status were failing which was expected behavior. So Selenium2Library keyword is working as expected.
