### ISSUE TITLE
how to validate that the text exists on the page, not in the HTML code

### ISSUE THREAD

**Issue by Alexey-Stepanov** [robotframework/SeleniumLibrary#643]
Yeah, we can check the text on page using the step **Wait Until Page Contains**
But this won't work in the following case:
HTML — <span>Experience</span>
CSS — text-transform: uppercase
How it looks on the page — EXPERIENCE
My step: Wait Until Page Contains EXPERIENCE
Result: FAIL    Text 'EXPERIENCE' did not appear in 5 seconds
Why? Because Experience!=EXPERIENCE

We need to check the text as it appears on the page (not in the HTML code).

**Comment by drobota** [comment]
I can bet that this issue in EDGE only. Am I correct?

**Comment by aaltat** [comment]
Could you specify the browser and it's version. Also the Selenium and Selenium2Library version are useful.

**Comment by Alexey-Stepanov** [comment]
Debian “stretch” with all latest updates
Google Chrome Version 52.0.2743.116 (64-bit)
selenium 3.0.0b2, also tried 2.32.0
robotframework-selenium2library 1.8.0

**Comment by Alexey-Stepanov** [comment]
[Here](https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/keywords/_element.py#L730) is the place where the text is searched:

```
def _is_text_present(self, text):
    locator = "xpath=//*[contains(., %s)]" % utils.escape_xpath_value(text);
    return self._is_element_present(locator)
```

**Comment by aaltat** [comment]
If you try the [Get Text](http://robotframework.org/Selenium2Library/Selenium2Library.html#Get%20Text) keyword is the text then correct?

Also would you have a public website available where this problem can be seen?

**Comment by aaltat** [comment]
Also what is the chrome driver version you are using? And the selenium 2.32.0 is rather old version. It would be good to try out the selenium 2.53.6 version.

**Comment by Alexey-Stepanov** [comment]
Get Text works fine, but is not convenient for me because I have to be attached to the locator in this case.
The bug manifests regardless of selenium version. ChromeDriver 2.23.

The bug can be reproduced as follows.
Let's assume we have a piece of code:
 < div >
                first string
                second string
 < /div >
It looks like "first string second string" on the page in browser.

Wait Until Page Contains  first string second string ---> FAIL
Wait Until Page Contains  first string ---> SUCCESS

Conclusion: Selenium2Library is searching in the HTML code which is not the expected result.

We should search the text on the page, exactly as it looks.

**Comment by emanlove** [comment]
I would have suspected the first to pass. It would be helpful if you built up a test case with a test page, something like

``` html
<html>
  <head>
  </head>
  <body>
    <div>
      first string
      second string
    </div>
    <div>first string second string</div>
    <div> first string second string </div>
    <div> first  string   second  string </div>
    <div>
      first string</br>
      second string
    </div>
  </body>
</html>
```

I would be curious to see both a Selenium2Library test case and a [pure python selenium test case](https://github.com/robotframework/Selenium2Library/blob/master/BUILD.rst#testing-selenium).

**Comment by aaltat** [comment]
The [Selenium API](http://selenium-python.readthedocs.io/api.html) does not allow the get text from all the elements, the text must be always read from a specific element from the DOM/page. In Selenium2Library, checking text from a whole DOM/page is done by using the `Wait Until Page Contains` keyword, which uses the xpath expression, which you also found.

The text in the DOM is not always the same as the user sees in the page, because it can be alternated by many things. Example by the browser, which usually normalizes text before it is shown to the user. The xpath, in the other hand, does not normalizes text but relies purely what is on the DOM. Selenium, tries to very hard to mimic a real user (and most of the time does a very good job) and returns the text as it seen the user. 

In the example the text in the div element contains new line character in the DOM. In Python string and in one line it could look like this: `first string\nsecond string`. Please note that there are many other ways to make a line break and this is only one of the possibilities. Now if you would need to check is the text present in the page one must also specify the white space, therefore in Robot Framework
you would need to this: 

```
| Wait Until Page Contains | first string\\nsecond string | 
```

This can be annoying, specially if the page is poorly coded and contains lot's of different white space characters. There are ways [remove the nasty whites pace with xpath](http://stackoverflow.com/questions/11776910/xpath-expression-to-remove-whitespace) but it does not ensure that the text would have the case which users sees in the page. 

Your problem is a real one and I also bump in to the same problem now and then. For me the case does not usually matter. If it matters, I use the `Get Text` keyword. But if you want check text the as is seen by the user and without `Get Text` keyword one can [extend the Selenium2Library](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#extending-existing-test-libraries). Example this [code](https://gist.github.com/aaltat/fb5e4de73dad82e09734460c80546e53) should work with this [test](https://gist.github.com/aaltat/80983b57fc5ba586608fc3239f4b8e3e)

Because the problem is a real one, perhaps we should do something about it. Changing the code right a way (to the direction which is in the [example](https://gist.github.com/aaltat/fb5e4de73dad82e09734460c80546e53)) can not be in the next release because the change is backwards incompatible. Change would break many users tests, including mine and it could be big job to refactor test back to working state. Also in complex pages, it may cause a performance issue (not sure about the performance problem but at least needs to checked out). One option is to create a parameter for the keyword, which changes the way how the text is verified from the page. The best option would be deprecate the old functionality gracefully and bring the new functionality in the same time available. But this needs some discussion and thinking which would be the best way to do it.

**Comment by aaltat** [comment]
Small test proves that there is performance hit and a big one, I did test with google default search page: 
- With xpath error is raised in 0.1 seconds (give or take few milliseconds)
- With looping over the elements, time is 6.5 seconds. 

So the it takes 65 more time to loop over the elements then do it with xpath. And the google search page is fairly simple one. So at least we are not going to remove the old way, because it is too big of a performance hit. But should we still do something, because the problem is a real one? Perhaps configurable option, where default one uses the xpath, for the keyword and warn users about the poor performance if the default is not used?

What do others think?

One think which comes in mind to enhance the documentation. Because if one does not know how keyword works, the behavior is unexpected.

**Comment by Alexey-Stepanov** [comment]
Another use case which is lacking in this context.
For example, I would like to implement a custom keyword **I should not see the text blablabla**
**Get Text** is useless here, because there is no such element on the page.
I need to check all elements and make sure that there is no such text.
I have no idea about locators of these elements, all I know is the text. And it should not be present.

> configurable option, where default one uses the xpath, for the keyword and warn users about the poor performance if the default is not used

I like this idea

**Comment by aaltat** [comment]
If you want a quick solution, take the code from the example and try it out. If you go for this solution, getting feedback to us would be nice thing to have. Also you can add keywords to fulfill your other needs. 

Development team focus is on building Python 3 support, improve CI and build scripts. So we cannot promise any development on your request. But if we get a pull request, I am happy to review the pull request.

**Comment by aaltat** [comment]
Closing due inactivity.
