### ISSUE TITLE
Enable Travis to run with test with different browser from sauce labs from master by using cron job

### ISSUE THREAD

**Issue by bkhouri** [robotframework/SeleniumLibrary#663]
As of commit `7930bb186f8f98c5777c2eeae67ba8865a85f408`, the contents of `travis.yml` is:

```
language: python
sudo: false
python:
  - "2.6"
  - "2.7"
install:
  #- pip install pep8 --use-mirrors
  #- pip install pyflakes --use-mirrors
  - pip install robotframework
  - pip install selenium
  - pip install decorator
  - pip install mockito
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "firefox --version"
  - "python test/run_tests.py python $BROWSER --noncritical known_issue_-_travisci"
env:
  matrix:
  - BROWSER=firefox
  #- BROWSER=ie # will be added when we have completed SauceLabs CI
  #- BROWSER=safari # will be added after #247 merged
```

The last line is `#- BROWSER=safari # will be added after #247 merged`,  however PR #247 has been merged.  Should this like be commented out?

**Comment by HelioGuilherme66** [comment]
These are old comments and they were left there as a reminder of things to do.
We are doing advanced CI changes in #621.

Or current setup in Travis does not allow (is not using OS X). It is only testing with Firefox.
As we cannot comment out for Safari browser, I am closing this issue.

**Comment by pekkaklarck** [comment]
Let's remove unnecessary/confusing comments.

**Comment by aaltat** [comment]
The CI enhancement is done in the [CI branch](https://github.com/robotframework/Selenium2Library/tree/ci?files=1). Please take a look from there.

**Comment by aaltat** [comment]
The `.travis.yml` is cleaned from the comments and there is better coverage on the selenium and RF versions side. What is missing that we should test with different browser versions too. But with Travis it is only possible to use Firefox and Chrome browsers. To run test with other browsers, like Safari and IE, we need to use Sauce Labs.

But because of the security limitations it is not possible to launch test from Travis to Sauce labs. Instead we can create crob job in Travis, to launch test against current master and with different browser from Sauce labs. Configuring that cron job and modifying `.travis.yml` to launch required browsers needs to be done.

Changed issue report title to indicate the missing cron job and Travis configuration.

**Comment by aaltat** [comment]
This is more or less done. Closing the issue.
