### ISSUE TITLE
'Screenshot' library - [ WARN ] Keyword 'Set Screenshot Directory' found both from a custom test library

### ISSUE THREAD

**Issue by Ethies** [robotframework/SeleniumLibrary#683]
When I use both the "Take Screenshot" and "Set Screenshot Directory" keywords, have to import the 'Screenshot' library. 
But system throws warning message as 
"[ WARN ] Keyword 'Set Screenshot Directory' found both from a custom test library 'Selenium2Library' and a standard library 'Screenshot'. The custom keyword is used. To select explicitly, and to get rid of this warning, use either 'Selenium2Library.Set Screenshot Directory' or 'Screenshot.Set Screenshot Directory'."

Suggestion: Can add "Take Screenshot" keyword to Selenium2Library itself to avoid the conflict. 

Please let us know your suggestions.

My example code:
......
    Click Button    id=btnSave
    Set Screenshot Directory    ${OTHER_DIR}${/}    #Path
    Take Screenshot    seleniumSC-1.jpeg    #File name
    File Should Exist    ${OTHER_DIR}${/}seleniumSC-1.jpeg
......

**Comment by Ethies** [comment]
For reference to my testcase:
I have resolved my execution case by as below:
...
    Click Button    id=btnSave
    Set Screenshot Directory    ${OTHER_DIR}${/}TC Screenshots    #Path
    ${file1}=    Capture Page Screenshot    seleniumSC-1.jpeg    #FileName
    File Should Exist    ${OTHER_DIR}${/}seleniumSC-1.jpeg
...
This uses only Selenium2Libarary.

**Comment by emanlove** [comment]
I feel this is the fault of the Selenium2Library. A good resolution would be to create a second keyword, uniquely named -maybe `Set S2L Screenshot Directory` or  since I find it bad to use abbreviations `Set Custom Screenshot Directory` which either simply calls the current Selenium2Library's  `Set Screenshot Directory` or is a copy of the code and add a depreciation notice to the current Selenium2Library's. Then eventually depreciate the first keyword over time.

**Comment by aaltat** [comment]
It's quite common, at least in my world, that library keyword names will collide. There is at least two possible solutions.

1) Prefix keyword with libraries. Example:

```
| Selenium2Library.Set Screenshot Directory | /path/to/for |
```

2) Use library search order

See the user guide for more details: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#handling-keywords-with-same-names

**Comment by aaltat** [comment]
@emanlove because this is quite typical problem in Robot Framework and there are solutions in the Robot Framework side, should we make an effort to and change the keyword name. In my world this not a problem, because I prefix all the library keywords with the library name. I do it for two reasons
1) To avoid the keyword name collision.
2) Easier to find the keyword with IDE using completion support.

**Comment by emanlove** [comment]
Some apologies are due on my part. I thought this was happening due to more recent changes, e.g. the addition of the `Set Screenshot Directory` keyword, to which this in not the case. That keyword has been in there for some time. My comments was really just trying to say that if we had new functionality to the Selenium2Library that we shouldn't add keywords similar to either the standard Robot Framework libraries nor any "popular" third-party libraries. That way we avoid this and we avoid it at the time of development and ask the question "Is this new keyword name unique and dissimilar then other keywords?" during the change request/code review process.

**Comment by aaltat** [comment]
No worries, we are a team and helping each other.

Definitely we should avoid keyword name collision with the Robot Framework standard libraries. And if it's possible to avoid collision with other libraries should it should be done, but in my opinion, the later one should not be enforced. If we would enforce the later rule we might end up choosing keyword names which are not natural in that context.

If one example tests web applications, it is likely that she/he has to perform tests with desktop browsers and mobile browsers. Then there is a need to use Selenium2Library and AppiumLibrary. In these context, using `Click Element` keyword feels natural, at least for me.

**Comment by aaltat** [comment]
But @Ethies does this solve your problem and can we close the issue?

**Comment by Ethies** [comment]
Resolved the issue
