### ISSUE TITLE
Wrong interpreter version detection when running acceptance tests.

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/SeleniumLibrary#742]
Wrong interpreter version detection when running acceptance tests.
See below, where output is `--variable PY_VERSION:python22.7`

```
[helio@localhost robotframework-selenium2library]$ python test/run_tests.py --interpreter python2 chrome
Running unit tests
.............................................................................................................
----------------------------------------------------------------------
Ran 109 tests in 0.094s

OK

Starting test execution with command:
python2 -m robot.run --doc "Selenium2Library acceptance tests with chrome" --outputdir /home/helio/robotframework-selenium2library/test/results --variable BROWSER:chrome --variable PY_VERSION:python22.7 --report NONE --log NONE --loglevel DEBUG --pythonpath /home/helio/robotframework-selenium2library/src:/home/helio/robotframework-selenium2library/test/resources/testlibs /home/helio/robotframework-selenium2library/test/acceptance
==============================================================================
Acceptance :: Selenium2Library acceptance tests with chrome                   
==============================================================================
Acceptance.Create Webdriver :: Tests Webdriver                                
==============================================================================
Create Webdriver Creates Functioning WebDriver :: LOG 2:1 INFO REG... | PASS |
```

PR is about to be proposed.

**Comment by aaltat** [comment]
Good catch, I will review the PR in near future.

**Comment by pekkaklarck** [comment]
The problem is real but apparently the `PY_VERSION` variable is only used for documentation purposes so this isn't too severe. Should definitely be fixed or alternative the whole variable should be removed.

The actual bug here is that `interpreter` is the interpreter user gave from the command line and `sys.version` is the version of the interpreter running `run_tests.py`. These two interpreters don't need to be same, and they obviously aren't if we run tests like `python2 run_tests.py --interpreter python3 ...`. This also means that the proposed fix is not correct.

If we want to get the name and version of the interpreter regardless is it given from the command line like `python`, `python2`, `python3.6`, `py -2`, `jython` or `pypy3`, the only way is executing the interpreter with `-V` option and reading the output (need to use `-V` and not `--version` if we care about IronPython that only supports the former). This is exactly what Robot Framework does in it's acceptance test runner. It has a separate `Interpreter` class that has also other related responsibilities. This interpreter name and version detection code could be just copy-pasted to S2L:s runner: https://github.com/robotframework/robotframework/blob/master/atest/interpreter.py#L31

**Comment by aaltat** [comment]
By looking the tests, the `${PY_VERSION}`  variable is not used in anywhere. Because it is not used anywhere, I think we could remove the variable and also remove the code that sets the variable. 

If it starts to look that having that variable could be useful in some situation, we can add it back.
