### ISSUE TITLE
Not able to switch to another Tab 

### ISSUE THREAD

**Issue by manju4ever** [robotframework/SeleniumLibrary#750]
I'm facing difficulty to switch to another tab. So using  **Select Window    window_title**  it's not working.
How do we switch the driver to point to another tab, is there a right way to do this ?

**Comment by aaltat** [comment]
Sometimes opening a new window takes fare bit of time and therefore the `Select Window` fails. This is specially true if you click element, which opens a new window, because the click doesn't know anything about the new window and that it should wait such event. 

As a best solution would be to make keyword that actually waits and select the window, example:
```
| Wait And Select Window | window_title | timeout=10s |
```
Would you like to build such keyword?

As a workaround, using this should work:
```
| Wait Until Keyword Succeeds | 10 | 2 | Select Window | window_title |
```
Please note that I did not check the keyword syntax and it might contain errors?

**Comment by manju4ever** [comment]
Sure thank you @aaltat , will definitely check it out and close it.

**Comment by aaltat** [comment]
Did you get the problem solved?

**Comment by manju4ever** [comment]
We used the select window by url and it worked like a charm.

Select Window    url="http://something.com"

Strategy	Example	Description
title	Select Window | title=My Document	Matches by window title
name	Select Window | name=${name}	Matches by window javascript name
url	Select Window | url=http://google.com	Matches by window's current URL
