### ISSUE TITLE
Add scroll Element into view Keyword from ExtendedSelenium2Library 

### ISSUE THREAD

**Issue by ashunshah** [robotframework/SeleniumLibrary#763]
I am using this keyword to solve the issue of floating headers/overlay menu. When using the keyword Click Element, Selenium does not consider the elements present on the z-index. The best solution is to scroll the hidden element into the view and click. Some related issue is #605

Links 
[Keyword Documentation](https://rickypc.github.io/robotframework-extendedselenium2library/doc/ExtendedSelenium2Library.html#Scroll%20Element%20Into%20View)
[Github](https://github.com/rickypc/robotframework-extendedselenium2library)

**Comment by aaltat** [comment]
If you create a pull request, then it's easier to say something about the code. But before looking the code, I need to understand the problem you are trying to solve.

But first some background information. Selenium has an auto focus feature build in to the API. Which means that generally user does not have to separately scroll element to the visible area. And selenium does actually pretty good job with the feature.

But because of the dynamic nature of web applications, the application may draw, after the focus, something on top of focused element. Therefore the interaction with the element may fail, because the application did something for the element. And user may need to build some logic on their keywords to overcome this feature in the application. Is this the problem that you are trying to solve? If it's not the problem, could you try to explain what the problem actually is and perhaps provide examples?

**Comment by ashunshah** [comment]
> But because of the dynamic nature of web applications, the application may draw, after the focus, something on top of focused element. Therefore the interaction with the element may fail, because the application did something for the element. And user may need to build some logic on their keywords to overcome this feature in the application. Is this the problem that you are trying to solve? If it's not the problem, could you try to explain what the problem actually is and perhaps provide examples?

Yes! ^ That is the problem I am trying to solve. Auto focus is not working for my application and I need to build a logic to bring the elements into view.

**Comment by aaltat** [comment]
And in high level, how you where planning to solve the problem?

**Comment by TangibleDream** [comment]
In ruby selenium I did the following

1.  focused the element I wished to scroll
2.  send_key(:arrow_down)
3.  repeat step 2 til happy

I wasn't able to get focus of the drag target in robot to do this.

**Comment by xinzx** [comment]
In my case, I want to click an element in pop-up web page, the page has an scroll bar, the element is on the down of the page, I can't click it with Click Element method in Firefox, is any suggestion?
Thanks advance.

**Comment by aaltat** [comment]
If you are seeking help, please ask in the community channels: http://robotframework.org/#support

If you are reporting a issue, please raise a new issue.

For me it feels that you should go by first option.

**Comment by aaltat** [comment]
This is done in #1083 closing the issue.

**Comment by sujit-paul** [comment]
I am able to scroll a web page horizontally or vertically successfully by using SeleniumLibrary in the robot framework. Please use Keyword (Execute Javascript)

Syntax 
window.scrollTo(xpos, ypos)

Execute Javascript window.scrollTo(0,5000) or Execute Javascript window.scrollTo(0,document.body.scrollHeight)

More details may be found on https://www.w3schools.com/jsref/met_win_scrollto.asp
