### ISSUE TITLE
Change library name from Selenium2Library to SeleniumLibrary

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#777]
With selenium moving the version 3 and therefore using Selenium2Library as a name does not fit right. Think and decide for a new name. Document changes and make the change if needed.

**Comment by HelioGuilherme66** [comment]
Proposals:

1. SeleniumLibrary
2. SeleniumXLibrary
3. (any other suggestions)

(This list will later be transformed in a poll)

**Comment by buzdu** [comment]
The logical approach to me seems - **Selenium3Library** (so proposal 2 from @HelioGuilherme66 ;) )

**Comment by HelioGuilherme66** [comment]
No, actually the whole point of this discussion is to avoid the numbering. We would have again this discussion when there is a Selenium 4. My idea was the actual SeleniumXLibrary (inspired by SikuliX).

**Comment by buzdu** [comment]
Ok, it was not obvious from the issue description.

Then, if the idea is to have this library (almost) always in line with the latest updates in the Selenium WebDriver project, my vote goes to **SeleniumXLibrary** (you can remove the no. 3 idea ;) )

**Comment by aaltat** [comment]
I am more leaning to towards `SeleniumLibrary​` but I don't feel strongly on the matter. But I feel that using a number in the name is not anymore valid case.

**Comment by arvk26** [comment]
SeleniumXLibrary seems good to me.

**Comment by emanlove** [comment]
How about WebDriverLibrary? I would have to think about this a while myself as this just came to me suddenly...

**Comment by emanlove** [comment]
... or possibly SeleniumWDLibrary?

**Comment by aaltat** [comment]
Take your time. I don't have any good suggestions either and the only thing that I feel strongly is that having number in the name is wrong.

**Comment by emanlove** [comment]
I think SeleniumLibrary is good too but the only problem there is dealing with the legacy SeleniumLibrary. When one asks for SeleniumLibrary do you mean the old SeleniumLibrary or the new one? And this may not be such a big issue because there is a version attached. I think this will be more of a communication problem than a technical one. We would need to check with yanne who seems to be the current owner of the [PyPI listing for SeleniumLibrary](https://pypi.python.org/pypi/robotframework-seleniumlibrary/2.9.2).

**Comment by pekkaklarck** [comment]
I don't think it's a problem to re-use the SeleniumLibrary name. The latest legacy SeleniumLibrary version was 2.9.2 and the new one can be 3.0. Easy to use `SeleniumLibrary<=3` if you want to install the legacy version. I doubt many people is going to use the legacy library anyway because it doesn't support the latest browsers.

PyPI isn't going to be a problem either. SeleniumLibrary has also `robotframework` as an owner and I can use it.

**Comment by vairamsvsjdo** [comment]
Any package version numbering need not follow the parent package version numbering. So it can be just that seleniumlibrary. I would merge S2L as Selenium Library version 3. 
Add selenium version support for 3 as version 4 if this is a major breaking change for S2L and too expensive to maintain backward compatibility ELSE. It will be a 3.X.

SeleniumLibrary Major version => breaking changes in its functionality or designHO, there is no major change between SeleniumLibrary supporting 

Github:
1. fork SeleniumLibrary as Selenium1Library and support is no Longer needed (I don't know how much is needed since most green browsers are supporting web driver standards and adding fixes only to that with active changes).
2. merge  Selenium2Library to SeleniumLibrary. S2L may remain a fork for SL.

**Comment by emanlove** [comment]
Or how about just SeleniumLibrary and it, SeleniumLibrary, is what ever version it happens to be and the README tells everyone what version(s) of Selenium it supports.

**Comment by vairamsvsjdo** [comment]
Yes readme will help with those supported license image shields will help. And PIP package management must say what version it supports.
But following through semver should be a norm or define what it means to major,minor,patch for S2L and follow through it.
SeleniumLibrary need not carry version tag to the package name.

**Comment by emanlove** [comment]
I believe that is defined in [PEP 440](https://www.python.org/dev/peps/pep-0440/).

**Comment by emanlove** [comment]
I think I understand what you are trying to say in your earlier comment today. One issue is there is already a [SeleniumLibrary](https://pypi.python.org/pypi/robotframework-seleniumlibrary) so we have to deal with it's last version.

**Comment by aaltat** [comment]
I think we are going to `SeleniumLibrary`name.

**Comment by aaltat** [comment]
And now it is official. I did send a mail to the user group and made it public. Next steps are to make it happen.

**Comment by aaltat** [comment]
Project is now renamed as SeleniumLibrary

**Comment by pekkaklarck** [comment]
The project is now renamed. There are still some external tasks remaining, like updating the info at http://robotframework.org, but I don't think we should use this issue to track them. I'd be ready to close this!

**Comment by aaltat** [comment]
Mee too
