### ISSUE TITLE
React Data Grid - Cannot execute Input Element keyword into filter row

### ISSUE THREAD

**Issue by xyngfei** [robotframework/SeleniumLibrary#784]
Why I cannot use input text into filter row text field?

    Open Browser    url=http://adazzle.github.io/react-data-grid/examples.html#/filterable-sortable-grid    browser=ie
    Selenium2Library.Wait Until Element Is Visible    //*[text()='Filter Rows']    30
    Selenium2Library.Click Element    //*[text()='Filter Rows']    
    Selenium2Library.Assign ID to Element    //INPUT[contains(@data-reactid,'header-filter-issueType')]    header-filter-id
	Selenium2Library.focus    //INPUT[contains(@data-reactid,'header-filter-issueType')]
	Selenium2Library.Input Text    //INPUT[contains(@data-reactid,'header-filter-issueType')]    Task 1

![image](https://cloud.githubusercontent.com/assets/17619539/24441386/f43fa764-148b-11e7-8c1b-b35806364087.png)

Window server 2012 64bits
IEDriverServer 3.3.0.0
robotframework                  3.0.2
robotframework-selenium2library 1.8.0

**Comment by aaltat** [comment]
As the error says the element is either not visible, disabled or read only. Have you checked which one of states is true for your element?

**Comment by xyngfei** [comment]
Yes, I can confirm element is visible, editable. 
The code is working perfectly fine in chrome and firefox.

**Comment by aaltat** [comment]
If the error only happens with a specific browser then there are at least two possible reasons. There is a bug in IEDriver and it reports wrong field status back to selenium. You have some IE specific implementation on your application and the error message is correct.

If the reason is former, you should report the problem to Microsoft. If the reason is later, you need to recheck the field implementation by using the IE development tools. Sometimes I have been able to overcome similar problem by using the selenium action chains: http://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.action_chains

**Comment by xyngfei** [comment]
Thanks @aaltat 

Somehow the first filter text field in data grid can be recognized, and by using selenium.webdriver.common.keys.Keys, I can simulate tab key to move the mouse cursor to another filter input text field.  

This is not a proper solution and hope 
[Press Keys Keyword](https://github.com/robotframework/Selenium2Library/issues/498) to be released soon.

**Comment by aaltat** [comment]
Because you have a workaround and the proper solution is described in the #498, do you have an problem related to this one or can we close the issue?

**Comment by xyngfei** [comment]
@aaltat, yeah, i will close this ticket. 

Thanks for your support.
