### ISSUE TITLE
Modify Get Webelements not to raise exception when no elements are found

### ISSUE THREAD

**Issue by jcyrss** [robotframework/SeleniumLibrary#805]
That modifies the behavior of  Selenium find_elements_xx.  Why does not it just return  empty list like Selenium?
And in many cases,  we need to check whether that element exists, so returning empty list is helpful

**Comment by aaltat** [comment]
I haven't made that feature and did not find anything useful from the issue tracker. I would assume that it follows more on the rest of the assert type of keywords in the library than the selenium functionality.

I can imagine a use case for the keyword to raise an exception and there is also a use case not raising a exception. Perhaps it could be configurable option not to raise an exception?

**Comment by AlexanderWhitestone** [comment]
Do you think it might be appropriate to update the element_find method to handle this case?
I think if we set the first_only and required parameters to False, it would be appropriate to return an empty list instead of raising an exception when no elements are found.
Then we could expose the required parameter to the get_webelements() method.

**Comment by aaltat** [comment]
I don't see a problem in this. I am thinking should we expose only the `required` argument or both `first_only` and `required` arguments, from `element_find` method.

If we expose only one argument, we could expose it as a separate argument, but if we decide expose both arguments perhaps we could use kwargs. If we use kwargs this needs some design. Would you like to write some examples, so that we could agree on the design?

**Comment by aaltat** [comment]
Let's change the functionality in that way keyword will not fail if the elements are not found.

**Comment by pekkaklarck** [comment]
Yeah, returning an empty list is much better than failing. It's easy to validate list is not empty with `Should Not Be Empty` if needed.

I don't think this behavior needs to be configurable in test data level. I'm not against it either but don't think it:s worth the effort.
