### ISSUE TITLE
Changing to dynamic library API caused changes how Robot Framework calls keywords with arguments

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#843]
When doing this:
```| wait until element is visible | xpath=//div | error=my text here | ``` then I get this: 
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\Selenium2Library\__init__.py", line 224, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Python27\lib\site-packages\Selenium2Library\base\robotlibcore.py", line 97, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords\waiting.py", line 143, in wait_until_element_is_visible
    self._wait_until_no_error(timeout, check_visibility)
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords\waiting.py", line 251, in _wait_until_no_error
    timeout = timestr_to_secs(timeout) if timeout else self.ctx._timeout_in_secs
  File "C:\Python27\lib\site-packages\robot\utils\robottime.py", line 48, in timestr_to_secs
    raise ValueError("Invalid time string '%s'." % timestr)
```
Added some debug logging and looks like default timeout None is converted to unicode at some point: 
`timeout: None, type: <type `

**Comment by pekkaklarck** [comment]
Converting default values to text is required by the dynamic API the lib nowadays uses. Should think how the API could be enhanced, but in this situation the lib needs to adapt. Probably handling `NONE`, case-insensitively, as meaning no timeout would be best.

**Comment by aaltat** [comment]
This needs some test in the S2L side. Perhaps implementing or importing RF `is_truthy` method would be a good idea. In any case, this is be backwards incompatible change, because in past string `None` and Python `None` where handled differently. But I think it's a chance for the better and change which can be easily deal with.

Need to think what how where to implement this one and how it's applied to the library. In same time it might be vise to fix also #719

I also agree that the API should be enhanced from Robot Framework side. It might be that API work differently based on how the arguments are used. Because if the Python `None` would be always converted to string `None` then it would always fail. Because my test relay on the S2L default timeout and do not usually provide the timeout. But this needs more investigation because this is based on my recollection.

**Comment by aaltat** [comment]
There is a difference how the API work. When my method is declared like this: 
```
from robot.utils import timestr_to_secs


default_timeout = 5


def wait_until_element_is_visible(self, locator, timeout=None, error=None):
    timeout = timestr_to_secs(timeout) if timeout else default_timeout
```
Now if I do this: 
```
| Wait Until Element Is Visible | hidden | 
```
Then timeout is passed as Python None and `default_timeout` is used. But if I do this: 
```
| Wait Until Element Is Visible | hidden | error=My error message | 
```
then timeout is passed as string None and converting it to string None to seconds fails. 

But I think we can not do anything for the problem, right now in the Robot Framework side and I need to convert values in the Selenium2Library side.

**Comment by aaltat** [comment]
Made partial fix in #845, which also supports #719,  just do demonstrate how I did plan to fix the problem. The idea is to hand pick the arguments which should be tested are they `True`. The #845 is based on the `robot.utils.is_truthy` code.

**Comment by pekkaklarck** [comment]
1. You are right that the default value is passed as string `None` only when you use some of the arguments after that. If you don't use the argument with a default value or any of the arguments after that, the keyword is just called with less arguments and functions Python default value is used. The reason is that the dynamic API ends up calling keywords using positional arguments when possible. This is by design and IIRC the reason had something to do with backwards compatibility and Java based libraries. I got some ideas how this could be enhanced.

2. Regardless how/if this is fixed on Robot side in RF 3.0.3, 3.1 or later, S2L needs to support also older versions and thus must have a workaround for the limitation.

3. In my opinion considering timeout given as string `None` is not backwards incompatible. Earlier that would have resulted in an error so it is *very* unlikely that anyone actually would use it. Supporting string `None` (preferably case-insensitively like Robot also handles `NONE` in many places) would actually be a smallish enhancement making it easier to specify a default value for timeout:

    ```robotframework
    *** Variables ***
    ${TIMEOUT}        NONE          # Works if `NONE` string is OK
    ${TIMEOUT}        ${NONE}        # Required is default values must be actual `None`

    *** Test Cases ***
    Example
        Wait Until Element Is Visible    locator    ${TIMEOUT}
    ```

4. Have you @aaltat checked are there more places where `None` is used as a default value in general and especially cases where there are arguments after that? Also those places would obviously be affected by this.

5. As far as I see, #845 is only related to #719 and doesn't affect this issue at all. #719 is definitely related and I'd like it to be fixed soon.

6. Probably we should add a utility inspired by Robot's `is_truthy` and `is_falsy` called something like `is_noney` or `is_nonethy` that returns true if the value is an actual `None` or a string `NONE` (case-insensitively).

**Comment by aaltat** [comment]
1) Ok, didn't know that one
2) True
3) You are right
4) Yes, all of the Wait* keywords use `None` and then there are few others too, like `Open Browser`.
5) I didn't get what you are trying to say
6) Because `None` is used often compared to the `False`, in S2L keywords I was thinking that S2L `is_trurhy` would also return Python `False` with string None (case insensitive)

**Comment by pekkaklarck** [comment]
With the item 5. I meant that PR #845 is more about fixing Boolean default values (i.e. issue #719) and not about handling `None` default value (i.e. this issue). Handling Boolean values better would be a nice enhancement and I'm +1 including it into the next release. Handling `None` is mainly a fix for a regression caused by the new architecture. As I already commented above, being able to pass `None` as a string `NONE` (case-insensitively) is a smallish enhancement too. Issue #719 could be extended to cover also that case.

**Comment by aaltat** [comment]
This is done in #845
