### ISSUE TITLE
Are there selenium actions of 1) mouse wheel scrolling 2) hold mouse wheel for a while?

### ISSUE THREAD

**Issue by cnyzgkn** [robotframework/SeleniumLibrary#862]
I am using selenium to simulate mouse/key actions.
Everything is OK expect I can't do these things below:
1. simulate mouse wheel scrolling to control webGL scene scale. 
note: Just want to simulate mouse middle button(wheel), not scroll the whole page up/down.
Currently Selenium already has click() for left mouse and context_click() for right mouse, but no

2. hold mouse wheel and drag-drop
drag_and_drop() is for left mouse, how can I click the mouse wheel and holding it until the drag-drop action complete?

Thank you

**Comment by aaltat** [comment]
Those things don't exist in the Selenium2Library, but it might be possible to implement your own keyword for those ones. If I would need to do such things, I would look to the Selenium ActionChains documentation: http://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.action_chains

**Comment by cnyzgkn** [comment]
@aaltat Thanks a lot for your comment.
Unfortunately I am new on python.  I don't know how to implement my own version...
It seems all action commands are implemented inside \Lib\site-packages\selenium\webdriver but I can't find where to add it. 
Could you please give some hints?

Than you

**Comment by aaltat** [comment]
How to build you own library is explained in the user guide: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-test-libraries

Also in user guide it's explained how to get the active Selenium2Library library instance from Robot Framework: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#getting-active-library-instance-from-robot-framework 

But because this is turning more a help question than a problem or feature request in the Selenium2Library, I am closing the issue. Please seek help from the Robot Framework user group [1] or from slack[2]. More support channels can be found form: http://robotframework.org/#support

[1] https://groups.google.com/forum/#!forum/robotframework-users
[2] https://robotframework.slack.com/messages/C07PKKCTF/
