### ISSUE TITLE
Enhancement - Open Element In New Window

### ISSUE THREAD

**Issue by ponkar** [robotframework/SeleniumLibrary#896]
We have often seen couple of Buttons or Links or any option need to be tested in a new tab. So I need review over this enhancement to understand what all challenges can be addressed.

I will be working to contribute with following keyword

Open Element In New Tab - Which will open the Link, Button or any locator which supports opening itself in new tab.

Comments are most welcome !!

**Comment by ponkar** [comment]
@pekkaklarck Please suggest me if I there is any thing more over this enhancement , is it worth ?

**Comment by pekkaklarck** [comment]
AFAIK Selenium doesn't support this. Please study that yourself and provide a pull request if it is possible.

**Comment by ponkar** [comment]
Yes I will come up with PR

**Comment by ponkar** [comment]
@pekkaklarck I am just figuring out how to test the python method I implemented in <Home_DIR>/SeleniumLibrary/src/SeleniumLibrary/keywords/element.py and test it in files in acceptance/tests folder

**Comment by aaltat** [comment]
Official Selenium does not support tabs: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5572 The question asked in the selenium issue tracker are valid one, does your application behaviour change if it's opened in a tab or in a new window? Also remember that user can always decide to separate the different tabs on new windows. Or user may configure the browser to open new window instead of tabs.

That being said, I know that it's possible to get tabs working at least on Chrome. But finding a universal solution that works on all browsers, also IE and Safari, might be challenging.

How to run test is explained in here: https://github.com/robotframework/SeleniumLibrary/blob/master/test/README.rst

**Comment by ponkar** [comment]
@aaltat Thanks for coming with Multiple Browser Checks. Based on your comments, I figured out that "Open In New Window" keyword works good both on Chrome, Firefox however the "Open In New Tab" doesnt work good on Firefox but works good on Chrome.

So out of 2 Keywords -

Open In New Tab, Open In New Window

I have retained only "Open In New Window" keyword and pull request for it is #897

@pekkaklarck @aaltat Please review the code and let me know

**Comment by ponkar** [comment]
We will include this enhancement in CLick Element keyword soon
