### ISSUE TITLE
Support holding shift and control when using `Click Element`

### ISSUE THREAD

**Issue by ponkar** [robotframework/SeleniumLibrary#905]
There should be an option to open link, button or any element in new Window. So Click Element keyword can be enhanced with it.
@aaltat @pekkaklarck 

If you suggest I will come up with PR to enhance click_element method

**Comment by pekkaklarck** [comment]
This is based on PR #897, right, and the idea is holding shift while clicking an element? As I commented earlier, we cannot really control what a browser does when you do that, so I wouldn't use term "open in new window" when talking about this. A generic enhancement to allow holding shift, control, and possibly other modifiers would be useful, though. I'll update the issue title accordingly.

Notice that at least I won't have time to participate in discussion related to this until we have SL 3.0 final out. Also, you don't need to refer to us using our GitHub handles. We get notifications from issues already otherwise.

**Comment by ponkar** [comment]
ok sure

**Comment by pekkaklarck** [comment]
I noticed you submitted PR #906 related to this. Although I already commented that I won't have time for this issue until SL 3.0 final is out, here are some general comment about the issue and that PR:

- The optional argument specifying which modifier to use shouldbe be something like `new_window`. Better use something generic like `hold_shift` or just `shift`. An additional argument then for control to allow holding either or both.

- Need to decided do we want to support these modifiers with all click keywords or only with the most generic `Click Element`. It would be nice to support all, but unless we come up with some really nice design that is going to require a lot of repetitive code, and documenting and testing would be an issue too.

- Using modifiers is also somewhat related to proposed `Press Keys` keyword (#498). For consistency reasons I'd like these to be designed together. I'd also consider both great additions for SL 3.1.

**Comment by ponkar** [comment]
Fine so when is 3.0 planned to rollout ? So that accordingly later to it we can sync up to understand points for redesigning the existing framework.

**Comment by pekkaklarck** [comment]
I hope we'll get SL 3.0 out soon but we don't have any real dead line. It's ready when it's ready. If you want to work with a PR already now, you can use, for example, `shift=False` and `ctrl=False` as the optional arguments.

**Comment by aaltat** [comment]
I am thinking should we support this by using variable number of arguments or by using the keywords arguments. It could be really handy to build generic solution which would map to Selenium `Keys`

**Comment by pekkaklarck** [comment]
You mean something like `SHIFT=True`? That would be generic and ought to be pretty easy to implement, but I'm not sure are there enough modifiers that actually make sense to press while clicking to make it worth it. Is there anything else than shift, control and alt? Supporting all Selenium Keys is a must with `Press Keys`.

Adding `**keys` to the signature would also have an annoying effect that `=` in all arguments to this keyword should be escaped. That would be *very* annoying when the current locator syntax requires using stuff like `css=h1`. This reminds me that we need to add an alternative to that locator syntax and we should add it in 3.0!

**Comment by aaltat** [comment]
Yes, something like `SHIFT=True`. There are many different kind of UI out there, which can use other than `Ctrl` and/or `Shift`keys when clicking element (although the `Ctrl` and/or `Shift`keys are most common ones). If/when this is going to expand in many keywords, it would be better to think more flexible solution than the current toggling of two modifiers and it would be better that the keywords signature would be somewhat similar, like using the `**keys`. 

The problem with `**keys` is a down side and definitely needs the enhancement described in #908. Also using the `**keys` is a big backwards incompatible problem, because the `css=h1` is used a lot. Example I have project where I have about 150 `Click Element` keyword which use `name=value` syntax. But at least I am happy with the change and I am willing to live with the change.

**Comment by pekkaklarck** [comment]
- Are there really any other keys that work while clicking than shift, control and alt? If not, adding generic support for all Selenium keys isn't worth it.

- The problem caused by `**whatever` is pretty severe. I wouldn't use this syntax in 3.0 unless it really brings big benefits. In 3.1 it's more acceptable as users have time to switch the the new syntax introduced by #908.

**Comment by aaltat** [comment]
When looking Chrome and Firefox supported shortcuts, the only used keys, when performing a click, are `Ctrl`, `Shift` and `Alt`. So I think we can go with that. Then the keyword syntax would look like:
```
| Click Element | locator | alt=False | ctrl=False | shift=False |
```
The order of arguments is not ideal in the example, because `alt` is least used. Perhaps `ctrl` or `shift` as first ones would be better.

**Comment by ponkar** [comment]
So the only challange I see for using ctrl is when Click Element will work on Mac OSX then it will expect COMMAND key and in case of Non-OSX Os it will work with CONTROL key

**Comment by aaltat** [comment]
At least chrome shortcut seems to use `command` instead of the `ctrl`. Also `command` is also a unique key in Selenium Keys. Implementing both `ctrl` and `command` should not that much of extra work. Testing the `command` is problematic because CI runs on Linux and I don't own a Mac. But if the logic for keys is universal we can unit test the logic and have acceptance test on for small subset of the keys.

**Comment by pekkaklarck** [comment]
Using `shift=False, ctrl=False, ...` works fine but adds quite many new arguments. Not a big problem with `Click Element` alone, but I'm not sure is it a good idea to add them to all click related keywords.

Another alternative is adding just `modifier=None` that can be used in test data like `modifier=SHIFT` or `modifier=SHIFT+CTRL`. This could easily be implemented so that all Selenium keys are supported. Should probably add at lest `CTRL` as an alias for `CONTROL`, though. Using `+` as a separator would also be compatible with ideas how to support Selenium keys with `Press Keys` keyword (#498).

**Comment by aaltat** [comment]
True, having that kind of modifier is a good option to go. Also it should be still not too difficult to implement.

**Comment by aaltat** [comment]
Then the keyword should look like this:
```
| Click Element | locator | modifier=SHIFT+CTRL |
```
I am not that familiar with the Mac keyboard but `ctrl` and `command` are different keys. I don't know how the use cases are different with those two keys, but looking the Chrome shortcut it looks like `ctrl` is replaced with `command`. So having them thigh for same alias us ok for me. And it can be always changed if it wrong decision.

**Comment by pekkaklarck** [comment]
Selenium supports both `COMMAND` and `CONTROL`, right? I'd map `CONTROL` (and possible `CTRL` alias) always to the control key and let users use `COMMAND` if needed. It's easy to handle this using variables in the data itself. Adding some new alias that matches control or command depending on the OS is possible too, but `CONTROL` should, IMHO, always mean control, not command.

**Comment by aaltat** [comment]
Miss read from my side, my bad. Pekka is correct

**Comment by ponkar** [comment]
Is any one of you going to work on this , Or shall i give a try so you guys can review it

**Comment by aaltat** [comment]
Please go ahead with the PR, our development efforts are tied on the 3.0.0 release.

**Comment by ponkar** [comment]
My Observations on chrome and fireofox browser on Mac / Unix / Win OS -

ctrl or cmd + click = Opens new tab but does not focus on new tab
ctrl or cmd + shift + click = opens new tab with focus on new tab
shift + click = Opens link in new window and focuses on new window

**Comment by aaltat** [comment]
There is a proposal for implementation, in #1139 It was easier to do an implementation, which does not restrict what [Selenium Keys](http://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.keys) is pressed when element is clicked. Therefore these are valid:
```
| Click Element | id:button | ARROW_UP | 
| Click Element | id:button | CTRL+ARROW_UP | 
```
And we leave up to the browser/applicationto react correctly to the keys and trust on users to use correct keys.

**Comment by aaltat** [comment]
@ponkar would it possible that you would try out the chance and provide feedback?

**Comment by aaltat** [comment]
Done in #1139

**Comment by ponkar** [comment]
Sure @aaltat I will check it.
