### ISSUE TITLE
Add support for `find_element` and `find_elements` in `ContextAware`

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#951]
This could be handy to remove the need to use `first_only`argument.

**Comment by pekkaklarck** [comment]
`find_elements` can be added also without touching `find_element`. In the long run I'd like `find_element` to work so that it fails if there isn't exactly one element. This would be backwards incompatible and definitely not worth the effort in SL 3.0. Adding the safe `find_elements` already now is, IMHO, a good idea.

**Comment by pekkaklarck** [comment]
This is already done.
