### ISSUE TITLE
Some checkbox keywords work also with radio buttons

### ISSUE THREAD

**Issue by Zabi-Py** [robotframework/SeleniumLibrary#962]
Kindly fix the issue for all Checkbox related keywords as to operate by its type.

For more info Refer https://groups.google.com/forum/#!topic/robotframework-users/GtgCudb5Ew0

**Comment by aaltat** [comment]
Would you mind to summer what you want to be fixed?

**Comment by pekkaklarck** [comment]
According to the code, checkbox relates keywords actually operate with any input element and don't check is the element actually a checkbox. Haven't tested this and don't know has @Zabi-Py actually encountered this in real test. 

Fixing ought to be trivial. It would be a similar change than my recent cleanups.

**Comment by aaltat** [comment]
Having restrictions has it's good and downsides. There are many ways to create html elements that look and behaves in same way but when looking from the DOM they are totally different elements or have different attributes. That being said, I really hate those kind of elements, which does not follow standard and make life hard.

I am not aware that can check box be be created in any other way than using the standard ways, but I would assume that JavaScript makes many things possible. Then there are limits set my the underlying Selenium and it's drivers which may or may be strict on the matter. In short I would follow the path which Selenium leads us, if Selenium is strict on the matter then we could be also be strict. I know that on lists like elements, Selenium is strict. On list like elements, the Selenium methods will on work only on input element which has the correct attribute set. 

As bottom line, this needs some thinking and testing. Also in list like elements, we could create similar issue and be strict on the matter.

**Comment by aaltat** [comment]
Did forget to ask, @Zabi-Py was this the problem which you wanted to be fixed?

**Comment by Zabi-Py** [comment]
@pekkaklarck Yes I encountered this in my test. @aaltat Select Checkbox method should work after identifying the element type 'checkbox' similar to Select Radio button method

**Comment by pekkaklarck** [comment]
Keywords that are affected are `Checkbox Should (Not) Be Selected` and `Select/Unselect Checkbox`. They use `_get_checkbox` helper which does `self.find_element(locator, tag='input')`. Other checkbox related keywords seem to use `tag=checkbox`.

The affected keywords use `is_selected` method on the returned element. The method has this documentation:

> Returns whether the element is selected.
> 
> Can be used to check if a checkbox or radio button is selected.

Based on this it seems that these keywords work also with radio buttons. That's definitely not good because we have separate radio button keywords and, perhaps more importantly, because other checkbox keywords are more strict. I highly prefer consistency, and in this case I'd say it's better that all checkbox keywords only work with checkboxes.
