### ISSUE TITLE
How to not wait for a page to load?

### ISSUE THREAD

**Issue by InBugsWeTrust** [robotframework/SeleniumLibrary#974]
Trying to find a way to e.g. click a button and continue with the next action without waiting for the page to load. Tried using Simulate (Simulate Event) and Mouse Down/Mouse Up but none of these helped.

Thanks a lot in advance!

**Comment by aaltat** [comment]
One can not. The underlying Selenium is blocking type of API. Selenium will wait for the onload event from browser before it allows more interactions with the browser. Also Selenium is not thread safe and therefore that doesn't work either.

If you want to change the functionality, please raise an issue to the Selenium issue tracker. And because this is a feature of the Selenium, I am closing the issue.
