### ISSUE TITLE
Inconsistency in page/frame related keyword

### ISSUE THREAD

**Issue by adwu73** [robotframework/SeleniumLibrary#98]
Page Should Contain handle only 1 level down the iframe tree, it can't detect the text in the 2nd sub level iframes.
Frame Should Contain also only handle 1 level of iframe
Page Should Contain(Not) Element don't handle sub frames at all

**Comment by emanlove** [comment]
What would one expect the behavior to be? Generally with how we have done things I would expect the following
- 'Page Should Contain' should be able to find text any number of frames and/or iframes down
- 'Page Should Contain Element' should be able to find the specified element any number of frames and/or iframes down

As for 'Frame Should Contain' I'm divided on whether it should search the current frame on down or search just the current frame. If it is only supposed to search the current frame then I would expect the keyword name to be 'This Frame Should Contain' or 'Current Frame Should Contain'.

**Comment by emanlove** [comment]
[Slightly Embarrassed] Well there is a ['Current Frame Contains' keyword](http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html#Current%20Frame%20Contains) (although no 'Current Frame Contains Element' keyword). It might be better to ask the question as to whether it is overly difficult to create a custom 'Frame (and all subframes) Should Contain' keyword. I suspect that it is... anyone?

**Comment by j1z0** [comment]
Just though I would add an alternative opinion… just to stir up the pot a bit. :)

My personal opinion is that Frames should always be a special case, page should contain and page should contain element should ignore frames unless they are active (because technically they are different pages).  You should first activate the frame and then use Frame Should Contain (which in my opinion works as designed).  A Frame Should Contain Element might be a nice edition, but if you activate a frame you can then call page should contain element I believe (it’s been a while) that it will actually work, if not I would say just add the Frame Should Contain Element, and have it just search the active Frame.

Cheers,
Jeremy Johnson

On January 16, 2014 at 11:00:12 PM, Ed Manlove (notifications@github.com) wrote:

[Slightly Embarrassed] Well there is a 'Current Frame Contains' keyword (although no 'Current Frame Contains Element' keyword). It might be better to ask the question as to whether it is overly difficult to create a custom 'Frame (and all subframes) Should Contain' keyword. I suspect that it is... anyone?

**Comment by aaltat** [comment]
I think Page Should (not) Contain, should look from hole page and all frames. 

For the Frame Shold Contain, I do not have a opinion, because I do not currently have not used those keywords. But logically thinking, there are two choises. Look only from selected frame or selected frame and all frames from below. 

Which one is better, I do not know but I would assume that it depends on the use case and on the application/webpage. Is it hard to build counter, how deep it should dig in the tree?

**Comment by aaltat** [comment]
There has not been activity for this issue for few years and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by sbrugman** [comment]
There should be a "Frame should contain element"  keyword. It is missing now and that is an issue in some cases, as "Frame should contain" does not have the same functionality.

**Comment by aaltat** [comment]
Removed 1.8 milestone because of lack of time

**Comment by pekkaklarck** [comment]
This is nowadays covered by #959 along with other frame related problems.
